// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once
#include <algorithm>
#include <array>
#include <atomic>
#include <cstdint>
#include <iostream>
#include <initializer_list>
#include <map>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using UINT = uint32_t;
using UID = uint32_t;
using HRESULT = int32_t;
constexpr HRESULT S_OK = 0;
constexpr HRESULT D3D_OK = S_OK;
constexpr HRESULT D3DERR_INVALIDCALL = static_cast<HRESULT>(0x8876086cu);
constexpr HRESULT HOST_FAILURE = static_cast<HRESULT>(0x80004005u);

enum class Commands : uint16_t {
  IDirect3DDevice9Ex_SetStreamSource = 1,
  IDirect3DDevice9Ex_SetIndices = 2,
  IDirect3DStateBlock9_Capture = 3,
  IDirect3DStateBlock9_Apply = 4,
  Bridge_Response = 5,
};
enum class Result { Success, Failure };

struct Context {
  std::vector<std::string> semantic;
  std::vector<std::string> refEvents;
  unsigned increments = 0, decrements = 0, violations = 0;
  unsigned lockEntries = 0, lockDepth = 0;
  unsigned destructionCount = 0;
  UID nextUid = 1;
  bool setterActive = false, responses = false, timeout = false;
  HRESULT response = S_OK;
  UINT hostStream0 = 0, hostIndex = 0;
  void fail(const std::string& why) { ++violations; semantic.push_back("violation:" + why); }
};
inline Context* active = nullptr;

inline void require(bool condition, const std::string& why) {
  if (!condition) throw std::runtime_error(why);
}

struct TestLock {
  TestLock() { ++active->lockEntries; ++active->lockDepth; }
  ~TestLock() { --active->lockDepth; }
};
#define BRIDGE_DEVICE_LOCKGUARD() TestLock binding_test_lock
#define ZoneScoped ((void)0)
#define LogFunctionCall() ((void)0)

// The real D3DAutoPtr is exercised against a counted lifetime adapter.
// objectRefs includes the external references, matching production's fused
// Object / Interface relationship. No heap deletion is done so an erroneous
// delete followed by resurrection can be reported deterministically.
class D3DRefCounted {
public:
  enum class Ref { Object };
  UID id;
  unsigned objectRefs = 1, externalRefs = 1;
  bool dead = false;
  explicit D3DRefCounted(UID value) : id(value) {}
  UID getId() const { return id; }
  template<Ref> void incRef() {
    if (dead || !objectRefs) active->fail("resurrection:" + std::to_string(id));
    if (active->setterActive && active->lockDepth != 1) active->fail("retain outside original lock");
    ++objectRefs; ++active->increments;
    active->refEvents.push_back("+" + std::to_string(id));
  }
  template<Ref> void decRef() {
    if (active->setterActive && active->lockDepth != 1) active->fail("release outside original lock");
    if (dead || !objectRefs) { active->fail("overrelease:" + std::to_string(id)); return; }
    --objectRefs; ++active->decrements;
    active->refEvents.push_back("-" + std::to_string(id));
    if (!objectRefs) {
      dead = true; ++active->destructionCount;
      active->semantic.push_back("destroy:" + std::to_string(id));
    }
  }
  void dropExternal() {
    require(externalRefs != 0, "external reference already gone");
    --externalRefs;
    decRef<Ref::Object>();
  }
};
#include "autoptr.inc"

struct IDirect3DVertexBuffer9 {};
struct IDirect3DIndexBuffer9 {};
struct Direct3DVertexBuffer9_LSS : IDirect3DVertexBuffer9, D3DRefCounted {
  explicit Direct3DVertexBuffer9_LSS(UID value) : D3DRefCounted(value) {}
};
struct Direct3DIndexBuffer9_LSS : IDirect3DIndexBuffer9, D3DRefCounted {
  explicit Direct3DIndexBuffer9_LSS(UID value) : D3DRefCounted(value) {}
};
template<typename T, typename U> T bridge_cast(U* obj) { return static_cast<T>(obj); }

class ClientMessage {
  Commands command;
  UID owner, uid;
  std::vector<UINT> data;
public:
  ClientMessage(Commands cmd, UID object) : command(cmd), owner(object), uid(active->nextUid++) {
    if (active->lockDepth) active->fail("message inside device lock");
  }
  UID get_uid() const { return uid; }
  template<typename... T> void send_many(T... values) { (data.push_back(static_cast<UINT>(values)), ...); }
  void send_data(UINT value) { data.push_back(value); }
  ~ClientMessage() {
    std::ostringstream text;
    text << "message:" << static_cast<UINT>(command) << ':' << owner << ':' << uid;
    for (auto value : data) text << ':' << value;
    active->semantic.push_back(text.str());
    if (command == Commands::IDirect3DDevice9Ex_SetStreamSource && data.size() == 4 && !data[0]) {
      active->hostStream0 = data[1];
    }
    if (command == Commands::IDirect3DDevice9Ex_SetIndices && data.size() == 1) active->hostIndex = data[0];
  }
};

namespace GlobalOptions {
inline bool getSendAllServerResponses() { return active->responses; }
inline UINT getAckTimeout() { return 97; }
}
namespace Logger {
inline void err(const char* error) { active->semantic.push_back(std::string("error:") + error); }
}
namespace DeviceBridge {
inline Result waitForCommand(Commands command, UINT timeout, void*, bool ordered, UID uid) {
  std::ostringstream text;
  text << "wait:" << static_cast<UINT>(command) << ':' << timeout << ':' << ordered << ':' << uid;
  active->semantic.push_back(text.str());
  if (active->lockDepth) active->fail("wait inside lock");
  return active->timeout ? Result::Failure : Result::Success;
}
inline HRESULT get_data() { active->semantic.push_back("response:" + std::to_string(active->response)); return active->response; }
inline void pop_front() { active->semantic.push_back("pop"); }
}
#include "responses.inc"

namespace l4d2_data {
inline std::atomic<bool> enabled{false};
inline void stateSet(uint16_t command, bool same, UINT bytes, bool recording, bool comparable) {
  std::ostringstream text;
  text << "diagnostic:" << command << ':' << same << ':' << bytes << ':' << recording << ':' << comparable;
  active->semantic.push_back(text.str());
}
}

class Direct3DStateBlock9_LSS;
class BaseDirect3DDevice9Ex_LSS {
public:
  template<typename T> struct Constants {
    std::array<T, 2> fConsts{}, iConsts{}, bConsts{};
  };
  struct State {
    std::array<UINT, 2> renderStates{}, streamFreqs{}, textureTypes{}, transforms{};
    D3DAutoPtr vertexDecl, indices, vertexShader, pixelShader;
    std::array<std::array<UINT, 2>, 2> samplerStates{}, textureStageStates{};
    std::array<D3DAutoPtr, 3> streams{};
    std::array<UINT, 3> streamOffsets{}, streamStrides{};
    std::array<D3DAutoPtr, 2> textures{};
    UINT material = 0, viewport = 0, scissorRect = 0;
    std::map<UINT, UINT> lights, bLightEnables;
    std::array<std::array<UINT, 4>, 2> clipPlanes{};
    Constants<UINT> vertexConstants, pixelConstants;
  };
  struct StateCaptureDirtyFlags {
    std::array<bool, 2> renderStates{}, streamFreqs{}, textures{}, transforms{};
    bool vertexDecl = false, indices = false, vertexShader = false, pixelShader = false;
    std::array<std::array<bool, 2>, 2> samplerStates{}, textureStageStates{};
    std::array<bool, 3> streams{}, streamOffsetsAndStrides{};
    bool material = false, viewport = false, scissorRect = false;
    std::map<UINT, bool> lights, bLightEnables;
    std::array<bool, 2> clipPlanes{};
    Constants<bool> vertexConstants, pixelConstants;
  };
  State m_state;
  Direct3DStateBlock9_LSS* m_stateRecording = nullptr;
  std::unique_ptr<StateCaptureDirtyFlags> m_dataKnown;
  UID getId() const { return 101; }
  #include "invalidate.inc"
};

class Direct3DStateBlock9_LSS {
public:
  BaseDirect3DDevice9Ex_LSS* m_pDevice;
  BaseDirect3DDevice9Ex_LSS::State m_captureState;
  BaseDirect3DDevice9Ex_LSS::StateCaptureDirtyFlags m_dirtyFlags;
  explicit Direct3DStateBlock9_LSS(BaseDirect3DDevice9Ex_LSS* device) : m_pDevice(device) {}
  UID getId() const { return 202; }
  static void StateTransfer(const BaseDirect3DDevice9Ex_LSS::StateCaptureDirtyFlags&,
    BaseDirect3DDevice9Ex_LSS::State&, BaseDirect3DDevice9Ex_LSS::State&);
  void LocalCapture();
  HRESULT Capture();
  HRESULT Apply();
};

#define DECLARE_DEVICE(name) \
template<bool EnableSync> class name : public BaseDirect3DDevice9Ex_LSS { \
public: \
  HRESULT SetStreamSource(UINT, IDirect3DVertexBuffer9*, UINT, UINT); \
  HRESULT SetIndices(IDirect3DIndexBuffer9*); \
};
DECLARE_DEVICE(BaselineDevice)
DECLARE_DEVICE(CandidateDevice)
DECLARE_DEVICE(SkipCommandMutant)
DECLARE_DEVICE(WrongDomainMutant)
DECLARE_DEVICE(MissingDirtyMutant)
DECLARE_DEVICE(MissingMetadataMutant)
#undef DECLARE_DEVICE

#include "BaselineDevice.inc"
#include "CandidateDevice.inc"
#include "SkipCommandMutant.inc"
#include "WrongDomainMutant.inc"
#include "MissingDirtyMutant.inc"
#include "MissingMetadataMutant.inc"
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4018)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-compare"
#endif
#include "stateblock.inc"
#ifdef _MSC_VER
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
