// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <cassert>
#include <cstdio>
#include <filesystem>
#include <map>
#include <string>
#include "config/config_document.h"
#include "bridge_settings.h"

namespace document = bridge_util::config_document;
using namespace l4d2_settings;
static std::string read(const std::filesystem::path& path) {
  std::string value; assert(SUCCEEDED(document::read(path, value))); return value;
}
static void put(const std::filesystem::path& path, const std::string& value) {
  document::File file(CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr));
  assert(file.get() != INVALID_HANDLE_VALUE);
  DWORD count = 0; assert(WriteFile(file.get(), value.data(), static_cast<DWORD>(value.size()), &count, nullptr) && count == value.size());
}
static unsigned definitions(const std::string& text, const std::string& key) {
  unsigned count = 0;
  for (size_t start = 0; start < text.size();) {
    auto end = text.find('\n', start); if (end == std::string::npos) { end = text.size(); }
    const auto line = document::parse(text.substr(start, end - start));
    if (line.valid && line.key == key) { ++count; }
    start = end + 1;
  }
  return count;
}
static void editor(const std::filesystem::path& path) {
  const std::string preserved = u8"# \u4e2d\u6587 comment\r\n\r\ncustom.option = \"\u4fdd\u7559 value\" # keep\r\n";
  const std::string original = "\xef\xbb\xbf" + preserved + "  client.testX86Server = False  # host\r\nclient.testX86Server=True\r\n# client.testX86Server = False\r\n";
  std::string edited;
  assert(document::edit(original, {{"client.testX86Server", "True"}, {"forceX64Server", "True"}}, edited) == S_OK);
  assert(edited.find(preserved) != std::string::npos && edited.find("  client.testX86Server = True  # host\r\n") != std::string::npos);
  assert(edited.find("# client.testX86Server = False\r\n") != std::string::npos);
  assert(definitions(edited, "client.testX86Server") == 1 && definitions(edited, "forceX64Server") == 1);
  assert(edited.find("forceX64Server = True\r\n") != std::string::npos && edited.compare(0,3,"\xef\xbb\xbf") == 0);
  std::string again; assert(document::edit(edited, {{"client.testX86Server", "True"}, {"forceX64Server", "True"}}, again) == S_OK && again == edited);
  assert(document::edit("# LF\ncustom = unchanged\nkey = old", {{"key","new"},{"added","True"}}, again) == S_OK);
  assert(again == "# LF\ncustom = unchanged\nkey = new\nadded = True\n");
  assert(document::edit("key = old", {{"key","new"}}, again) == S_OK && again == "key = new");
  assert(FAILED(document::edit("text", {{"key","bad\nvalue"}}, again)));
  assert(FAILED(document::edit("text", {{"key","x"},{"key","y"}}, again)));
  assert(FAILED(document::edit(std::string("\xff\xfeK\0",4), {{"key","value"}}, again)));
  put(path, original);
  assert(document::update(path, {{"client.testX86Server","True"},{"forceX64Server","True"}}) == S_OK);
  assert(read(path) == edited && !std::filesystem::exists(path.wstring() + L".tmp"));
  put(path, original);
  const auto temporary = std::filesystem::path(path.wstring() + L".tmp");
  put(temporary, "unrelated temporary");
  assert(FAILED(document::update(path, {{"client.testX86Server","True"}})));
  assert(read(path) == original && read(temporary) == "unrelated temporary");
  std::filesystem::remove(temporary);
  { // Permit reads but deny rename: failure happens after write/flush/close.
    document::File locked(CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING, 0, nullptr));
    assert(locked.get() != INVALID_HANDLE_VALUE);
    assert(FAILED(document::update(path, {{"client.testX86Server","True"}})));
    assert(read(path) == original && !std::filesystem::exists(temporary));
  }
  assert(FAILED(document::update(path.parent_path()/L"missing"/L"bridge.conf", {{"key","value"}})));
  std::filesystem::remove(path);
  assert(document::update(path, {{"key","value"}}) == S_OK && read(path) == "key = value\r\n");
  puts("PASS: preserved UTF-8/BOM/comments/unknown keys, LF/CRLF, duplicate normalization, atomic replacement and failure cleanup");
}
static void controls() {
  Controls control;
  Target configured; configured.host = Host::X86; configured.policy = l4d2_control::Policy::LearnedAggressive;
  auto runtimePolicy = configured.policy;
  Updates lastWrite;
  unsigned sets = 0, reads = 0, writes = 0;
  HRESULT runtimeError = S_OK, writeError = S_OK, readError = S_OK;
  control.read = [&](Target& result) { ++reads; result = configured; return readError; };
  control.write = [&](const Updates& updates) {
    ++writes; lastWrite = updates;
    if (FAILED(writeError)) { return writeError; }
    for (const auto& entry : updates) {
      if (entry.first == "client.testX86Server") { configured.host = entry.second == "True" ? Host::X86 : Host::X64; }
      if (entry.first == "client.pageBlockRetentionPolicy") {
        configured.policy = entry.second == "drop" ? l4d2_control::Policy::Drop : entry.second == "keep" ? l4d2_control::Policy::Keep : l4d2_control::Policy::LearnedAggressive;
      }
      for (size_t i = 0; i < 9; ++i) {
        if (entry.first == kPresenterKeys[i]) { configured.presenter[i] = entry.second == "True" ? 1u : entry.second == "False" ? 0u : static_cast<uint32_t>(std::stoul(entry.second)); }
      }
    }
    return S_OK;
  };
  control.runtime = [&](const l4d2_control::Request& request, l4d2_control::Response& response) {
    if (request.operation == l4d2_control::Operation::SetPolicy) {
      ++sets;
      if (FAILED(runtimeError)) { return runtimeError; }
      runtimePolicy = static_cast<l4d2_control::Policy>(request.value);
    }
    response.policy = runtimePolicy; return S_OK;
  };
  Request request; Response response;
  assert(control.invoke(&request, &response) == E_PENDING);
  control.initialize(configured); control.recordHost(Host::X86);
  assert(control.invoke(&request, &response) == S_OK && response.runtimeHost == Host::X86 && response.configuredHost == Host::X86 && !response.restartRequired);
  for (uint32_t i = 0; i < 3; ++i) {
    request.operation = Operation::SetMemoryPolicy; request.value = i; response = {};
    assert(control.invoke(&request, &response) == S_OK && response.configWriteSucceeded);
    assert(response.runtimePolicy == static_cast<l4d2_control::Policy>(i) && response.configuredPolicy == response.runtimePolicy && !response.restartRequired);
    assert(lastWrite.size() == 1 && lastWrite[0].first == "client.pageBlockRetentionPolicy" && lastWrite[0].second == policyName(response.runtimePolicy));
  }
  request.operation = Operation::SetHostMode;
  for (auto host : { Host::X64, Host::X86 }) {
    request.value = static_cast<uint32_t>(host); response = {};
    assert(control.invoke(&request, &response) == S_OK);
    assert(lastWrite.size() == 2 && lastWrite[0] == std::make_pair(std::string("forceX64Server"),std::string("True")));
    assert(lastWrite[1].second == (host == Host::X86 ? "True" : "False"));
    assert(response.runtimeHost == Host::X86 && response.configuredHost == host && response.restartRequired == (host != Host::X86 ? 1u : 0u));
    assert(sets == 3);
  }
  request.operation = Operation::SetReShadePresenter; request.value = 1; response = {};
  assert(control.invoke(&request, &response) == S_OK && response.presenterConfigured && !response.presenterAtStartup && response.restartRequired && sets == 3);
  assert(lastWrite.size() == 9);
  const char* expected[] = {"True","True","36","False","True","True","True","0","0"};
  for (size_t i = 0; i < 9; ++i) { assert(lastWrite[i].first == kPresenterKeys[i] && lastWrite[i].second == expected[i]); }
  request.value = 0; response = {};
  assert(control.invoke(&request, &response) == S_OK && !response.presenterConfigured && response.runtimeHost == Host::X86);
  assert(lastWrite.size() == 3 && lastWrite[0].first == kPresenterKeys[0] && lastWrite[1].first == kPresenterKeys[5] && lastWrite[2].first == kPresenterKeys[6]);
  assert(configured.presenter[4] == 1 && configured.presenter[7] == 0 && configured.presenter[8] == 0);
  request.operation = Operation::SetMemoryPolicy; request.value = 0; response = {};
  writeError = HRESULT_FROM_WIN32(ERROR_ACCESS_DENIED);
  assert(control.invoke(&request, &response) == S_FALSE && SUCCEEDED(response.runtimeResult) && FAILED(response.configResult) && !response.configWriteSucceeded);
  writeError = S_OK; runtimeError = E_ACCESSDENIED; request.value = 1; response = {};
  assert(control.invoke(&request, &response) == S_FALSE && FAILED(response.runtimeResult) && response.configWriteSucceeded && response.runtimePolicy == l4d2_control::Policy::Keep && response.configuredPolicy == l4d2_control::Policy::LearnedAggressive);
  runtimeError = S_OK; readError = E_ACCESSDENIED; request.operation = Operation::GetStatus; response = {};
  assert(control.invoke(&request, &response) == S_FALSE && FAILED(response.queryResult) && response.configuredHost == Host::Unknown);
  readError = S_OK;
  for (auto op : { Operation::GetStatus, Operation::GetMemoryPolicy, Operation::GetHostMode, Operation::GetReShadePresenter }) {
    const auto priorWrites = writes, priorSets = sets, priorReads = reads;
    request.operation = op; response = {};
    assert(control.invoke(&request, &response) == S_OK && reads == priorReads + 1 && sets == priorSets && writes == priorWrites);
  }
  const auto before = writes;
  request.operation = Operation::SetHostMode; request.value = 0; response = {};
  assert(control.invoke(&request, &response) == E_INVALIDARG && writes == before);
  request.value = 99; assert(control.invoke(&request, &response) == E_INVALIDARG);
  request.operation = Operation::SetMemoryPolicy; assert(control.invoke(&request, &response) == E_INVALIDARG);
  request.operation = Operation::SetReShadePresenter; assert(control.invoke(&request, &response) == E_INVALIDARG);
  request.version = 999; assert(control.invoke(&request, &response) == E_INVALIDARG);
  assert(control.invoke(nullptr, &response) == E_INVALIDARG && control.invoke(&request, nullptr) == E_INVALIDARG);
  puts("PASS: policy runtime+persistence, partial failures, exact Host/Presenter updates, live status, restart detection and ABI rejection");
}
int main() {
  wchar_t temporary[MAX_PATH] {}; assert(GetTempPathW(MAX_PATH, temporary));
  const auto directory = std::filesystem::path(temporary) / (L"l4d2-settings-" + std::to_wstring(GetCurrentProcessId()));
  std::filesystem::create_directories(directory);
  editor(directory / L"bridge.conf"); controls(); std::filesystem::remove_all(directory);
  return 0;
}
