// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define WIN32_LEAN_AND_MEAN
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <d3d9.h>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>
#include "color_diagnostics.h"
#include "color_backend_diagnostics.h"
#include "readback_layout.h"

void require(bool condition, const char* message) {
  if (!condition) { throw std::runtime_error(message); }
}
struct Wire {
  std::vector<uint32_t> data;
  template<typename... Values> void send_many(Values... values) { data = { static_cast<uint32_t>(values)... }; }
};
struct QueryObject {
  ULONG references = 1;
  ULONG Release() { return --references; }
};
int main(int argc, char**) {
  try {
    using namespace l4d2_color;
    record("event=DISABLED");
    require(!enabled.load() && !due(1), "diagnostics must be off by default");
    for (const auto format : { kDxt1, kDxt3, kDxt5, 21u }) {
      TextureRequest request { 1, 1, 1, 1, 0, format, 1, 0xfedcba98u };
      Wire wire; request.send2D(wire);
      require(wire.data == std::vector<uint32_t>({ 1, 1, 1, 0, format, 1, 0xfedcba98u }), "production wire order changed");
      size_t position = 0;
      const auto decoded = TextureRequest::read2D([&]() { return wire.data.at(position++); });
      require(decoded.width == request.width && decoded.height == request.height && decoded.levels == request.levels
        && decoded.usage == request.usage && decoded.format == request.format && decoded.pool == request.pool
        && decoded.resource == request.resource && position == 7, "client/host parameters differ");
      if (compressed(format)) {
        const auto storage = blockLayout(1, 1, format);
        l4d2_readback::Layout recovery;
        require(l4d2_readback::layout(1, 1, format, recovery), "small mip recovery layout rejected");
        require(storage.rowBytes == (format == kDxt1 ? 8u : 16u) && storage.rows == 1
          && storage.bytes == recovery.bytes, "minimum compressed block or recovery layout differs");
      }
    }
    const auto partial = blockLayout(5, 3, kDxt5);
    require(partial.rowBytes == 32 && partial.rows == 1 && partial.bytes == 32, "compressed ceiling layout wrong");
    require(!blockLayout(0, 1, kDxt1).bytes && !blockLayout(1, 1, 21).bytes, "invalid/noncompressed dimensions mishandled");
    Ring<unsigned, 3> queue;
    require(queue.push(11) && queue.push(22) && queue.push(33) && !queue.push(44), "queue capacity not bounded");
    unsigned output = 0;
    require(queue.pop(output) && output == 11 && queue.push(44), "queue wrap failed");
    for (const auto expected : { 22u, 33u, 44u }) { require(queue.pop(output) && output == expected, "FIFO changed"); }
    require(!queue.pop(output), "empty queue produced an item");
    Change change;
    require(change.add(5, S_OK) && !change.add(5, S_OK), "unchanged states counted as changes");
    require(!change.add(99, D3DERR_INVALIDCALL) && change.value == 5 && change.failures == 1,
      "failed setter corrupted observed state");
    require(change.add(7, S_OK) && change.calls == 4 && change.changes == 2, "state aggregation wrong");
    std::vector<uint8_t> payload(100000, 0x73);
    Digest digest; digest.add(payload.data(), payload.size()); digest.add(payload.data(), 64);
    require(digest.bytes == 100064 && digest.hashedBytes == 65536 && digest.value == hash(payload.data(), 65536),
      "payload hash sampling is not bounded");
    QueryObject object; unsigned inspected = 0;
    for (unsigned i = 0; i < 150000; ++i) {
      require(inspectTemporary<QueryObject>([&](QueryObject** result) { ++object.references; *result = &object; return S_OK; },
        [&](QueryObject*) { ++inspected; }) == S_OK, "query HRESULT changed");
      require(object.references == 1, "diagnostic query leaked a Reset-blocking reference");
    }
    require(inspected == 150000, "temporary query test did not run");
    require(inspectTemporary<QueryObject>([&](QueryObject** result) { ++object.references; *result = &object; return D3DERR_INVALIDCALL; },
      [&](QueryObject*) { throw std::runtime_error("failed result inspected"); }) == D3DERR_INVALIDCALL && object.references == 1,
      "failed query did not release returned pointer");
    try {
      inspectTemporary<QueryObject>([&](QueryObject** result) { ++object.references; *result = &object; return S_OK; },
        [](QueryObject*) { throw 17; });
    } catch (int) {}
    require(object.references == 1, "exception leaked diagnostic query reference");
    const bool capped = argc > 1;
    const char* file = capped ? "color-capped.log" : "color-test.log";
    require(initialize("client", "test-color-build", 1, file, capped ? 4096 : 4ull * 1024ull * 1024ull), "writer initialization failed");
    texture("CREATE_TEXTURE_SERIALIZED", { 1, 1, 1, 1, 0, kDxt5, 1, 42 }, 2, 1234, S_OK, 0, true);
    observe(2, State::Render, D3DRS_FOGCOLOR, 0x00aabbccu, S_OK);
    observe(2, State::Render, D3DRS_FOGCOLOR, 0x00aabbccu, S_OK);
    observe(2, State::Render, D3DRS_FOGCOLOR, 0x00ffffffu, D3DERR_INVALIDCALL);
    require(due(2) && !due(2), "snapshot limiter ignored interval");
    std::vector<std::thread> writers;
    for (unsigned i = 0; i < 4; ++i) {
      writers.emplace_back([i, capped]() {
        for (unsigned j = 0; j < (capped ? 2000u : 100u); ++j) { record("event=THREAD_TEST writer=%u item=%u", i, j); }
      });
    }
    for (auto& writer : writers) { writer.join(); }
    finish();
    std::ifstream input(file, std::ios::binary);
    const std::string log { std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>() };
    require(log.find("event=CONFIG") != std::string::npos && log.find("event=LIMITS") != std::string::npos, "log header/footer missing");
    if (capped) { require(log.size() <= 4608 && log.find("file_discarded=0") == std::string::npos, "file cap failed or saturation not exercised"); }
    else {
      require(log.find("requested_levels=0") != std::string::npos && log.find("shared_present=1") != std::string::npos
        && log.find("block_bytes=16") != std::string::npos && log.find("fallback=0") != std::string::npos, "texture evidence missing");
      require(log.find("calls=3 changes=1 failures=1") != std::string::npos && log.find("queue_dropped=0") != std::string::npos,
        "final state evidence or queue integrity missing");
      size_t lines = 0, pos = 0;
      while ((pos = log.find("event=THREAD_TEST", pos)) != std::string::npos) { ++lines; ++pos; }
      require(lines == 400, "concurrent diagnostic records were lost");
    }
    std::puts("PASS: production 2D wire roundtrip, small BC/recovery layout, bounded FIFO/hash/file, actual-change aggregation, async concurrent log/normal-exit flush and 150000 balanced temporary queries; no GPU behavior claimed.");
    return 0;
  } catch (const std::exception& error) { std::fprintf(stderr, "%s\n", error.what()); return 1; }
}
