// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Storage adapters for the unchanged production constant-update method.
#include <d3d9.h>
#include <array>
#include <cstring>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <utility>
#include "data_diagnostics.h"
#include "util_commands.h"

struct BaseDirect3DDevice9Ex_LSS {
  struct ShaderConstants {
    enum class ShaderType { Vertex, Pixel };
    enum class ConstantType { Float, Int, Bool };
    template<typename T> struct Vec4 { T data[4]; };
  };
  struct Flags {
    std::array<bool, 16> fConsts {}, iConsts {}, bConsts {};
  };
  struct StateCaptureDirtyFlags {
    std::array<bool, 16> textures {}, streams {};
    bool indices = false;
    Flags vertexConstants, pixelConstants;
  };
  struct Constants {
    ShaderConstants::Vec4<float> fConsts[16] {};
    ShaderConstants::Vec4<int> iConsts[16] {};
    uint32_t bConsts[1] {};
  };
  struct State { Constants vertexConstants, pixelConstants; };
  struct Recording { State m_captureState; StateCaptureDirtyFlags m_dirtyFlags; };
  State m_state;
  Recording* m_stateRecording = nullptr;
  std::unique_ptr<StateCaptureDirtyFlags> m_dataKnown = std::make_unique<StateCaptureDirtyFlags>();
  template<ShaderConstants::ShaderType, ShaderConstants::ConstantType, typename T>
  std::pair<HRESULT, uint32_t> commonGetSetConstants(uint32_t start, const T* input, uint32_t count) {
    return { input && start <= 16 && count <= 16 - start ? S_OK : D3DERR_INVALIDCALL, count };
  }
  template<ShaderConstants::ShaderType ShaderT, ShaderConstants::ConstantType ConstantT, typename T>
  HRESULT setShaderConstants(uint32_t startRegister, const T* pConstantData, uint32_t count);
  void invalidateDataState();
};
using ShaderType = BaseDirect3DDevice9Ex_LSS::ShaderConstants::ShaderType;
using ConstantType = BaseDirect3DDevice9Ex_LSS::ShaderConstants::ConstantType;
using Vec4f = BaseDirect3DDevice9Ex_LSS::ShaderConstants::Vec4<float>;
using Vec4i = BaseDirect3DDevice9Ex_LSS::ShaderConstants::Vec4<int>;
