// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include "data_diagnostics.h"
#include "util_commands.h"
#include <d3d9.h>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <thread>
#include <vector>

using namespace l4d2_data;
static int failures = 0;
static void check(bool value, const char* message) {
  if (!value) { ++failures; std::cerr << message << '\n'; }
}
static std::string readFile() {
  std::ifstream file("data-test.log", std::ios::binary);
  return std::string(std::istreambuf_iterator<char>(file), {});
}
int main(int argc, char** argv) {
  static_assert(D3DLOCK_READONLY == 0x10 && D3DLOCK_DISCARD == 0x2000 && D3DLOCK_NOOVERWRITE == 0x1000);
  const std::string mode = argc > 1 ? argv[1] : "normal";
  DeleteFileW(L"data-test.log");
  if (mode == "--disabled") {
    Resource resource; resource.open(Kind::Vertex, 1, 64, 64);
    resource.lock(0, 0, D3DLOCK_DISCARD, S_OK); resource.upload(64);
    Temporary temporary(64); Wire wire; wire.add(68, 64, true);
    sent(1, false, wire, true, 16); Dispatch dispatch(1, false); finish();
    check(!enabled.load() && !wire.bytes && GetFileAttributesW(L"data-test.log") == INVALID_FILE_ATTRIBUTES, "disabled path created state or output");
    return failures;
  }
  check(!initialize("client", "test-build", 5000, L"missing-directory/data.log"), "invalid output path succeeded");
  check(!enabled.load(), "failed initialization enabled tracing");
  check(initialize("client", "test-build", mode == "--periodic" ? 1000 : 5000, L"data-test.log", mode == "--cap" ? 4096 : 64ull * 1024 * 1024), "initialization failed");
  if (mode == "--periodic") {
    {
      Resource resource; resource.open(Kind::Volume, 25, 0, 0);
      resource.lock(0, 8, D3DLOCK_READONLY, S_OK, true, true);
      resource.upload(8); Temporary temporary(8);
      Sleep(1300);
      resource.upload(8);
    }
    finish();
    const auto log = readFile();
    check(log.find("event=SNAPSHOT final=0") != std::string::npos && log.find("event=SNAPSHOT final=1") != std::string::npos, "background/final snapshots missing");
    check(log.find("event=RESOURCE_LIVE kind=volume id=25") != std::string::npos && log.find("event=RESOURCE_RELEASE kind=volume id=25") != std::string::npos, "worker lost lifecycle");
    check(log.find("partial=1 lock_bytes=8 uploads=2 upload_bytes=16") != std::string::npos, "partial Volume totals differ");
    return failures;
  }
  if (mode == "--overflow") {
    auto resources = std::make_unique<Resource[]>(8193);
    for (uint32_t i = 0; i < 8193; ++i) { resources[i].open(Kind::Index, i, 4, 4); resources[i].upload(4); }
    resources.reset(); finish();
    const auto log = readFile();
    check(log.find("resource_overflow=1") != std::string::npos, "metadata overflow missing");
    check(log.find("kind=ib created=8193 released=8193 live=0 logical_bytes=0 shadow_bytes=0") != std::string::npos, "aggregate lost overflow resources");
    check(log.find("retired_dropped=6144") != std::string::npos, "retirement overflow missing");
    return failures;
  }
  Resource remaining; remaining.open(Kind::VertexShader, 88, 20, 20);
  remaining.read(0); remaining.read(20);
  {
    Resource vb; vb.open(Kind::Vertex, 10, 64, 64, D3DUSAGE_DYNAMIC, D3DPOOL_DEFAULT);
    vb.lock(0, 0, D3DLOCK_DISCARD, S_OK);
    vb.lock(4, 8, D3DLOCK_NOOVERWRITE, S_OK);
    vb.lock(0, 64, D3DLOCK_READONLY, S_OK);
    vb.lock(60, 8, 0, S_OK); // Trace the invalid range; never dereference game memory.
    vb.lock(UINT64_MAX, 0, 0, E_FAIL);
    vb.upload(64); vb.upload(8, true); vb.upload(8, false, true);
    std::vector<std::thread> threads;
    for (int i = 0; i < 4; ++i) { threads.emplace_back([&]() { for (int n = 0; n < 1000; ++n) { vb.upload(1); } }); }
    for (auto& thread : threads) { thread.join(); }
    Temporary temporary(128); Temporary moved(std::move(temporary));
    { Temporary nested(64); }
  }
  Wire wire; wire.add(4, 0, true); wire.add(12, 5, true); wire.add(68, 64, true, true); wire.add(4, 0, false);
  const auto command = static_cast<uint16_t>(Commands::IDirect3DVertexBuffer9_Unlock);
  sent(command, false, wire, true, 12); sent(command, false, Wire {}, false, 12);
  received(command, false);
  { Dispatch dispatch(command, false); backend(command, false, 64, S_OK); backend(command, true, 0, E_FAIL); }
  sent(0xffff, true, Wire {}, true, 12); sent(0xff00, false, Wire {}, true, 12); sent(900, false, wire, true, 12);
  finish(); finish();
  const auto log = readFile();
  check(log.find("event=END") != std::string::npos, "missing final footer");
  if (mode == "--cap") { check(log.size() <= 4096 && log.substr(log.rfind("event=END")).find("file_discarded=0 ") == std::string::npos, "cap or accounting failed"); return failures; }
  check(log.find("kind=vb created=1 released=1 live=0 logical_bytes=0 shadow_bytes=0 peak_shadow_bytes=64 locks=5 readonly=1 discard=1 nooverwrite=1 partial=3 lock_bytes=136 uploads=4003 upload_bytes=4080 shared_bytes=8 reserved_bytes=8 invalid=2 failures=1") != std::string::npos, "buffer lifetime/access totals differ");
  check(log.find("temporary_bytes=0 peak_temporary_bytes=192 temporary_allocations=2 temporary_freed=2") != std::string::npos, "temporary move/destruction accounting differs");
  check(log.find("data_bytes=84 blob_bytes=69 reserved_bytes=64 header_bytes=12 serialization_failures=1 publish_failures=1 handled=1") != std::string::npos, "wire/dispatch totals differ");
  check(log.find("backend_locks=1 backend_unlocks=1 backend_failures=1 backend_bytes=64") != std::string::npos, "backend results differ");
  check(log.find("kind=vertex_shader created=1 released=0 live=1 logical_bytes=20 shadow_bytes=20") != std::string::npos && log.find("reads=2 read_bytes=20") != std::string::npos, "local shadow readback missing");
  check(log.find("event=RESOURCE_RELEASE kind=vb id=10") != std::string::npos, "released resource history missing");
  check(log.find("event=RESOURCE_LIVE kind=vertex_shader id=88") != std::string::npos, "live metadata missing");
  std::cout << "Data diagnostics failures=" << failures << '\n';
  return failures;
}
