// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <d3d9.h>
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <initializer_list>
#include <stdexcept>
#include "upload_observers.h"

static void require(bool condition, const char* message) {
  if (!condition) { throw std::runtime_error(message); }
}
#undef assert
#define assert(condition) require(!!(condition), "production assertion fired")

namespace Commands {
enum D3D9Command { Bridge_Response, IDirect3DDevice9Ex_GetSwapChain,
  IDirect3DDevice9Ex_Reset, IDirect3DDevice9Ex_ResetEx };
}
struct State {
  HRESULT queryResult = D3D_OK;
  HRESULT resetResult = D3D_OK;
  bool queryPointer = true, allResponses = false, fullscreenPointer = false;
  unsigned queries = 0, resets = 0, resetsEx = 0, responses = 0;
  UINT index = 0;
  uint32_t rawPresent = 0;
  D3DPRESENT_PARAMETERS presentation {};
  D3DDISPLAYMODEEX fullscreen {};
  HRESULT response = E_FAIL;
} state;

// Only the surrounding COM objects and transport are adapters. The three Host
// switch branches and response macro are extracted verbatim. Upstream Reset
// now always replies, independently of the optional command response policy.
class FakeSwapChain {
public:
  ULONG references = 1, releases = 0;
  virtual ~FakeSwapChain() = default;
  virtual ULONG Release() {
    require(references > 1, "released the device-owned reference");
    ++releases;
    return --references;
  }
} swapchain;

class FakeDevice {
public:
  HRESULT GetSwapChain(UINT index, FakeSwapChain** output) {
    require(index == state.index && output != nullptr, "swapchain query arguments changed");
    ++state.queries;
    *output = state.queryPointer ? &swapchain : nullptr;
    if (*output) { ++swapchain.references; }
    return state.queryResult;
  }
  HRESULT Reset(D3DPRESENT_PARAMETERS* presentation) {
    require(swapchain.references == 1, "temporary query reference survived until Reset");
    require(presentation && presentation->BackBufferWidth == 1920 && presentation->Windowed,
      "Reset presentation arguments changed");
    ++state.resets;
    return state.resetResult;
  }
  HRESULT ResetEx(D3DPRESENT_PARAMETERS* presentation, D3DDISPLAYMODEEX* fullscreen) {
    require(swapchain.references == 1, "temporary query reference survived until ResetEx");
    require(presentation && presentation->BackBufferWidth == 1920 && presentation->Windowed,
      "ResetEx presentation arguments changed");
    require(fullscreen == (state.fullscreenPointer ? &state.fullscreen : nullptr),
      "ResetEx fullscreen argument changed");
    ++state.resetsEx;
    return state.resetResult;
  }
} device;

#define IDirect3DSwapChain9 FakeSwapChain
#define IDirect3DDevice9Ex FakeDevice
#define GET_RES(name, collection) auto* name = &device
#define PULL_U(name) const UINT name = state.index
#define PULL_DATA(size, pointer) do { (void)(size); pointer = state.fullscreenPointer ? &state.fullscreen : nullptr; } while (0)
namespace bridge_util {
struct Logger { static void err(const char*) {} };
}
struct DeviceBridge {
  static void get_data(void** output) { *output = &state.rawPresent; }
};
static D3DPRESENT_PARAMETERS getPresParamFromRaw(uint32_t* input) {
  require(input == &state.rawPresent, "Reset stopped decoding the original payload");
  return state.presentation;
}
static void configureOverlayPresenter(D3DPRESENT_PARAMETERS&) {}
namespace bridge_exception { static void logDiagnostic(const char*) {} }
struct SurfaceQueries {
  uint64_t count() const { return 0; }
  uint64_t mismatches() const { return 0; }
} gSurfaceQueries;
struct GlobalOptions {
  static bool getSendAllServerResponses() { return state.allResponses; }
};
struct ServerMessage {
  ServerMessage(Commands::D3D9Command command, uint32_t uid) {
    require(command == Commands::Bridge_Response && uid == 77, "response command or UID changed");
  }
  void send_data(HRESULT result) { ++state.responses; state.response = result; }
};
#include "device_reset_lifetime_response.h"

static void dispatch(Commands::D3D9Command command) {
  using namespace Commands;
  const uint32_t currentUID = 77;
  const uint32_t pD3DDeviceHandle = 7;
  const struct { uint32_t pHandle; } rpcHeader { pD3DDeviceHandle };
  const bool bDxvkModuleLoaded = true;
  bool done = false;
  switch (command) {
#include "device_reset_lifetime_host.h"
    default: require(false, "unexpected test command");
  }
  require(!done, "supported reset stopped the Host");
}

// Restoring the original unguarded Release must fail without a Windows crash
// dialog. Keep SEH in this leaf wrapper (no C++ unwinding objects); other test
// failures remain ordinary C++ exceptions caught by main.
static bool invoke(Commands::D3D9Command command) {
#ifdef _MSC_VER
  __try {
    dispatch(command);
    return true;
  } __except (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION
                ? EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH) {
    return false;
  }
#else
  // GCC does not provide MSVC SEH. Production/null-reference negative controls
  // run under MSVC CI; the portable build validates all positive branches.
  dispatch(command);
  return true;
#endif
}

static void resetState() {
  require(swapchain.references == 1, "temporary swapchain reference leaked");
  state = {};
  state.presentation.BackBufferWidth = 1920;
  state.presentation.Windowed = TRUE;
  swapchain.releases = 0;
}
static void testQueries() {
  resetState();
  state.index = 2;
  for (unsigned i = 0; i < 256; ++i) {
    require(invoke(Commands::IDirect3DDevice9Ex_GetSwapChain), "query caused an access violation");
    require(swapchain.references == 1 && swapchain.releases == i + 1, "read-only query leaked its reference");
  }
  require(state.queries == 256 && !state.resets && !state.resetsEx && !state.responses,
    "read-only query changed dispatch or reply behavior");
}
static void testReset(bool extended) {
  for (bool respond : {false, true}) {
    for (bool withPointer : {false, true}) {
      for (HRESULT result : {D3D_OK, E_FAIL}) {
        for (bool withFullscreen : {false, true}) for (HRESULT backendResult : {D3D_OK, D3DERR_DEVICELOST}) {
          resetState();
          state.allResponses = respond;
          state.queryPointer = withPointer;
          state.queryResult = result;
          state.fullscreenPointer = withFullscreen;
          state.resetResult = backendResult;
          const auto command = extended ? Commands::IDirect3DDevice9Ex_ResetEx : Commands::IDirect3DDevice9Ex_Reset;
          for (unsigned i = 0; i < 8; ++i) {
            require(invoke(command), "Reset query with a null result caused an access violation");
            require(state.queries == i + 1, "Reset did not perform exactly one query");
            require(swapchain.references == 1 && swapchain.releases == (withPointer ? i + 1 : 0),
              "Reset query reference was leaked or released twice");
            require(state.resets == (extended ? 0 : i + 1) && state.resetsEx == (extended ? i + 1 : 0),
              "backend Reset dispatch changed");
            require(state.responses == i + 1, "Reset must always return one response regardless of optional reply policy");
            require(state.response == backendResult, "Reset returned the query HRESULT instead of backend HRESULT");
          }
        }
      }
    }
  }
}
int main() {
  SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
  try {
    testQueries();
    testReset(false);
    testReset(true);
    std::puts("PASS: actual Host swapchain query/Reset/ResetEx branches; balanced temporary references, null/failed queries and mandatory backend results");
    return 0;
  } catch (const std::exception& error) {
    std::fprintf(stderr, "FAIL: %s\n", error.what());
    return 1;
  }
}
