// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include "function_logging_support.h"
#include "function_logging_production.h"

volatile bool GlobalOptions::logApiCalls = false;
volatile bool GlobalOptions::logAllCalls = false;
std::vector<CapturedLog> capturedLogs;

void _LogFunctionCall(const std::string& functionName, void* thiz) {
  capturedLogs.push_back({functionName, thiz});
}

// Keep production methods in a separate translation unit, as in the client.
// Do not enable link-time optimization for this isolated caller benchmark.
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4018) // Existing production nesting counter comparison.
#endif
#include "function_logging_production.inc"
#ifdef _MSC_VER
#pragma warning(pop)
#endif
