// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
using Device = Bridge<BridgeId::Device>;
using Module = Bridge<BridgeId::Module>;
bool threadedTest=false;
void require(bool value,const char* message) {
  if (!value) { std::fprintf(stderr,"IPC_TEST_FAIL %s pid=%lu\n",message,GetCurrentProcessId()); std::exit(2); }
}
uint32_t pattern(uint32_t sequence,uint32_t offset) { return sequence*1664525u+offset*1013904223u; }
template<typename B> void receive(uint32_t sequence,bool request) {
  require(B::waitForCommand()==Result::Success,"wait packet");
#ifdef REMIX_BRIDGE_SERVER
  const auto header=B::pop_front();
  const auto uid=B::get_data();
#endif
  require(B::get_data()==sequence,"packet order");
  const auto size=B::get_data();
  require(size==sequence%65,"size metadata");
  void* data=nullptr;
  require(B::get_data(&data)==size,"blob prefix");
  if (size) { require(data!=nullptr,"nonempty payload pointer"); }
  for(uint32_t i=0;i<size;++i) { require(static_cast<uint8_t*>(data)[i]==static_cast<uint8_t>(pattern(sequence,i)),"payload integrity"); }
  void* second=nullptr;
  require(B::get_data(&second)==8,"second blob length");
  for(uint32_t i=0;i<8;++i) { require(static_cast<uint8_t*>(second)[i]==static_cast<uint8_t>(sequence+i),"second blob integrity"); }
#ifdef REMIX_BRIDGE_SERVER
  require(uid==sequence,"UID sequence");
#endif
  // Do not release the arena while any application pointer is still being used.
#ifdef REMIX_BRIDGE_SERVER
  B::end_read_data();
  if (request) {
    typename B::Command reply(Commands::Bridge_Response,uid);
    std::array<uint8_t,64> bytes{};
    for(uint32_t i=0;i<size;++i){ bytes[i]=static_cast<uint8_t>(pattern(sequence,i)); }
    reply.send_many(sequence,size);reply.send_data(size,bytes.data());
    std::array<uint8_t,8> extra{};for(uint32_t i=0;i<8;++i){extra[i]=static_cast<uint8_t>(sequence+i);}
    reply.send_data(8,extra.data());
    require(reply.finish()==Result::Success,"reply commit");
  }
  (void)header;
#else
  (void)request;
  B::pop_front();
#endif
}
template<typename B> void send(uint32_t sequence,bool reply) {
  {
    typename B::Command command(Commands::Bridge_Response);
    if(threadedTest) { sequence=command.get_uid(); }
    const auto size=sequence%65;
    std::array<uint8_t,64> bytes{};
    for(uint32_t i=0;i<size;++i){bytes[i]=static_cast<uint8_t>(pattern(sequence,i));}
    command.send_many(sequence,size);command.send_data(size,bytes.data());
    std::array<uint8_t,8> extra{};for(uint32_t i=0;i<8;++i){extra[i]=static_cast<uint8_t>(sequence+i);}
    command.send_data(8,extra.data());
    require(command.finish()==Result::Success,"request commit");
  }
  if(reply){receive<B>(sequence,false);}
}
void CALLBACK peerExit(void*,BOOLEAN) { gbBridgeRunning.store(false,std::memory_order_release); }
int failureCases(const std::wstring& mode) {
  GlobalOptions::timeout=20;
  const size_t memory=32*sizeof(Header)+256+128*sizeof(uint32_t);
  WriterChannel writer("failedBatch",memory,32,128);
  ReaderChannel reader("failedReply",memory,32,128);Device::install(&writer,&reader);
  PROCESS_INFORMATION child{};HANDLE registration=nullptr;
  if(mode==L"peer-exit" || mode==L"normal-peer-exit") {
    wchar_t executable[MAX_PATH]{};GetModuleFileNameW(nullptr,executable,MAX_PATH);
    wchar_t arguments[MAX_PATH*2]{};swprintf_s(arguments,L"\"%ls\" %ls",executable,mode==L"normal-peer-exit"?L"normal-exit-child":L"exit-child");
    STARTUPINFOW startup{};startup.cb=sizeof(startup);
    require(CreateProcessW(nullptr,arguments,nullptr,nullptr,FALSE,0,nullptr,nullptr,&startup,&child)!=FALSE,"spawn exit peer");
    require(RegisterWaitForSingleObject(&registration,child.hProcess,peerExit,nullptr,INFINITE,WT_EXECUTEONLYONCE)!=FALSE,"peer exit registration");
    GlobalOptions::timeout=500;
  }
  const bool oversize=mode==L"oversize";
  const bool partial=mode==L"partial-timeout";
  const bool headerFull=mode==L"header-full";
  if(headerFull) {
    for(unsigned i=0;i<31;++i) { require(writer.commands->push({Commands::Bridge_Response,0,0,0})==Result::Success,"prefill Header queue"); }
  } else if(!oversize) {
    std::array<uint8_t,500> bytes{};bytes.fill(0x71);
    Device::Command complete(Commands::Bridge_Response);
    complete.send_data(1);complete.send_data(partial?400:static_cast<uint32_t>(bytes.size()),bytes.data());
    require(complete.finish()==Result::Success,"full ring valid batch");
  }
  const auto publishedBefore=writer.control->published.load();
  LARGE_INTEGER before{},after{},frequency{};QueryPerformanceFrequency(&frequency);
  FILETIME creation{},exit{},kernelBefore{},userBefore{},kernelAfter{},userAfter{};
  GetThreadTimes(GetCurrentThread(),&creation,&exit,&kernelBefore,&userBefore);
  QueryPerformanceCounter(&before);
  if(mode==L"wait-failure") { ipcInjectWaitFailure=true; }
  {
    Device::Command incomplete(Commands::Bridge_Response);
    if(partial) {
      incomplete.send_data(71);
      const auto cursor=writer.data->cursor();
      std::array<uint8_t,96> bytes{};incomplete.send_data(96,bytes.data());
      require(writer.data->cursor()==cursor,"partial failed reservation wrote payload");
    }
    if(oversize) {
      incomplete.send_data(71);
      const auto cursor=writer.data->cursor();
      require(incomplete.begin_data_blob(128*4)==nullptr,"oversize reserve null");
      incomplete.send_data(99);
      require(writer.data->cursor()==cursor,"failed batch wrote again");
    }
    require(incomplete.finish()!=Result::Success,"failed batch success");
  }
  QueryPerformanceCounter(&after);GetThreadTimes(GetCurrentThread(),&creation,&exit,&kernelAfter,&userAfter);
  if(!headerFull){require(writer.control->published.load()==publishedBefore,"failed batch publication frontier changed");}
  require(writer.control->fault.load()==1 && !Device::healthy(),"channel poison");
  { Device::Command later(Commands::Bridge_Response);require(later.finish()!=Result::Success,"later false success"); }
  Result result;
  if(headerFull) {
    for(unsigned i=0;i<31;++i) { writer.commands->pull(result,1);require(result==Result::Success,"existing Header retained"); }
  } else if(!oversize) {
    const auto first=writer.commands->pull(result,1);
    require(result==Result::Success,"existing batch retained");
    if(!partial){require((first.flags&Commands::DataFullRing) && !first.dataOffset,"full ring marker");}
  }
  writer.commands->peek(result,1);
  require(result!=Result::Success,"failed or later Header publication");
  if(registration) {
    WaitForSingleObject(child.hProcess,2000);UnregisterWaitEx(registration,INVALID_HANDLE_VALUE);
    CloseHandle(child.hThread);CloseHandle(child.hProcess);
  }
  auto ticks=[](FILETIME value){return (static_cast<uint64_t>(value.dwHighDateTime)<<32)|value.dwLowDateTime;};
  const auto wall=static_cast<double>(after.QuadPart-before.QuadPart)*1000.0/static_cast<double>(frequency.QuadPart);
  const auto cpu=static_cast<double>(ticks(kernelAfter)+ticks(userAfter)-ticks(kernelBefore)-ticks(userBefore))/10000.0;
  std::printf("IPC_NATIVE_FAULT_PASS mode=%ls wall_ms=%.3f client_cpu_ms=%.3f no-write no-header poison subsequent-failure\n",mode.c_str(),wall,cpu);
  return 0;
}
int protocolMismatch() {
  const size_t memory=32*sizeof(Header)+256+128*sizeof(uint32_t);
  WriterChannel writer("protocolForward",memory,32,128);
  ReaderChannel reader("protocolReply",memory,32,128);
  WriterChannel wrongPeer("protocolReply",memory,32,128);
  Device::install(&writer,&reader);
  wrongPeer.control->version=1;
  require(wrongPeer.commands->push({Commands::Bridge_Response,0,0,0})==Result::Success,"mismatch test Header");
  require(Device::waitForCommand()!=Result::Success,"incompatible protocol accepted");
  require(reader.control->fault.load()==1 && !gbBridgeRunning.load(),"protocol mismatch did not stop channel");
  std::puts("IPC_NATIVE_PROTOCOL_REJECTION_PASS");return 0;
}
int pinnedLifetime() {
#ifdef REMIX_BRIDGE_SERVER
  const size_t memory=32*sizeof(Header)+256+128*sizeof(uint32_t);
  WriterChannel output("pinReply",memory,32,128);
  ReaderChannel input("pinForward",memory,32,128);
  WriterChannel peer("pinForward",memory,32,128);Device::install(&output,&input);
  std::array<uint8_t,64> payload{};payload.fill(0x4d);
  auto append=[&](){
    peer.data->push(7);peer.data->push(64,payload.data());
    peer.control->published.store(peer.data->cursor());
    require(peer.commands->push({Commands::Bridge_Response,0,static_cast<uint32_t>(peer.data->get_pos()),0})==Result::Success,"pin test packet");
  };
  append();require(Device::waitForCommand()==Result::Success,"pin first wait");Device::pop_front();Device::get_data();
  Device::pinRead(7);void* pointer=nullptr;Device::get_data(&pointer);Device::end_read_data();
  const auto pinned=input.control->consumed.load();require(pinned==1,"pin earliest live payload");
  append();require(Device::waitForCommand()==Result::Success,"pin second wait");Device::pop_front();Device::get_data();
  void* later=nullptr;Device::get_data(&later);Device::end_read_data();
  require(input.control->consumed.load()==pinned,"later packet released pinned memory");
  require(static_cast<uint8_t*>(pointer)[63]==0x4d,"live pinned pointer integrity");
  append();require(Device::waitForCommand()==Result::Success,"pin release wait");Device::pop_front();Device::get_data();Device::get_data(&later);
  Device::unpinRead(7);Device::end_read_data();require(input.control->consumed.load()==input.data->cursor(),"unpin failed to release");
  append();require(Device::waitForCommand()==Result::Success,"destroy pin wait");Device::pop_front();Device::get_data();Device::pinRead(9);Device::get_data(&later);
  Device::destroyReadPins(9);Device::end_read_data();require(input.control->consumed.load()==input.data->cursor(),"destroy failed to release pin");
  std::puts("IPC_NATIVE_PIN_LIFETIME_PASS");return 0;
#else
  return 2;
#endif
}
int wmain(int argc,wchar_t** argv) {
  if(argc==2) {
    const std::wstring mode=argv[1];
    if(mode==L"exit-child" || mode==L"normal-exit-child") { Sleep(100);ExitProcess(mode==L"normal-exit-child"?0:31); }
    if(mode==L"pins") { return pinnedLifetime(); }
    if(mode==L"protocol") { return protocolMismatch(); }
    return failureCases(mode);
  }
  require(argc>=3,"arguments: guid count");
  require(gUniqueIdentifier.setGuid(&argv[1]),"session GUID");
  const auto count=static_cast<uint32_t>(std::wcstoul(argv[2],nullptr,10));
  threadedTest=argc>3;
  const size_t memory=32*sizeof(Header)+256+128*sizeof(uint32_t);
#ifdef REMIX_BRIDGE_CLIENT
  const char* forward="Forward";const char* reverse="Reverse";
#else
  const char* forward="Reverse";const char* reverse="Forward";
#endif
  WriterChannel writer(std::string("Device")+forward,memory,32,128);
  ReaderChannel reader(std::string("Device")+reverse,memory,32,128);
  WriterChannel moduleWriter(std::string("Module")+forward,memory,32,128);
  ReaderChannel moduleReader(std::string("Module")+reverse,memory,32,128);
  Device::install(&writer,&reader);Module::install(&moduleWriter,&moduleReader);
#ifdef REMIX_BRIDGE_CLIENT
  if(threadedTest) {
    std::vector<std::thread> threads;
    for(unsigned thread=0;thread<4;++thread) { threads.emplace_back([&](){
      for(uint32_t i=0;i<count/4;++i){send<Device>(0,false);send<Module>(0,false);}
    }); }
    for(auto& thread:threads){thread.join();}
  } else
#endif
  for(uint32_t sequence=0;sequence<count;++sequence) {
    const bool reply=!threadedTest && (sequence%17)==0;
#ifdef REMIX_BRIDGE_CLIENT
    send<Device>(sequence,reply);send<Module>(sequence,reply);
#else
    receive<Device>(sequence,reply);receive<Module>(sequence,reply);
#endif
  }
  // Force an ordered final response in both queues before either process exits.
#ifdef REMIX_BRIDGE_CLIENT
  send<Device>(count,true);send<Module>(count,true);
#else
  receive<Device>(count,true);receive<Module>(count,true);
#endif
  std::printf("IPC_NATIVE_TRANSPORT_PASS pointer_bits=%u packets_per_channel=%u capacity_dwords=128 device+module forward+reverse\n",
    static_cast<unsigned>(sizeof(void*)*8),count+1);
  return 0;
}
