// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Adapters control scheduling/results; extracted production code owns decisions.
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <functional>
#include <mutex>
#include <string>
#include <type_traits>
#include <vector>
#define REMIX_BRIDGE_CLIENT
#define ZoneScoped
using UINT = unsigned;
using UID = uint32_t;
namespace bridge_util {
enum class Result { Success, Timeout, Failure };
enum class LogLevel { Trace };
}
using namespace bridge_util;
#define RESULT_SUCCESS(x) ((x) == Result::Success)
#define RESULT_FAILURE(x) ((x) != Result::Success)
template<typename T> T align(T value, T alignment) { return (value + alignment - 1) / alignment * alignment; }
template<typename... T> std::string format_string(const char*, T...) { return {}; }
struct Logger {
  static bool isEnabled(LogLevel) { return false; }
  static void warn(const std::string&) {} static void info(const std::string&) {}
  static void err(const std::string&) {}
  template<typename T> static void debugLazy(T&&) {}
  [[noreturn]] static void errLogMessageBoxAndExit(const std::string&) { std::abort(); }
};
namespace logger_strings {
const char* OutOfBufferMemory="capacity"; const char* OutOfBufferMemory1="capacity";
const char* MultipleActiveCommands="nested";
std::string bufferNameToOption(const std::string&) { return {}; }
}
namespace Commands {
enum D3D9Command : uint16_t { Bridge_Response, Test };
using Flags = uint16_t;
std::string toString(D3D9Command) { return "test"; }
}
struct Header { Commands::D3D9Command command; Commands::Flags flags; uint32_t dataOffset, pHandle; };
namespace l4d2_api_wait {
enum class Metric { Serialize, BlobReserve, BlobCommit, Submit, CommandMutexWait, DataQueueWait };
struct Span { Span(Metric) {} void finish() {} }; void queued() {}
}
namespace l4d2_data {
struct Wire { size_t bytes=0, failures=0; void add(size_t n, size_t, bool ok, bool=false) { bytes+=n; failures+=!ok; } };
void sent(uint16_t, bool, const Wire&, bool, size_t) {}
}
namespace bridge_exception {
enum class Queue { Device, Module };
struct CommandScope { CommandScope(Queue,uint16_t,uint32_t,const char*) {} void setUid(UID) {} };
void recordCommand(bool,Queue,uint16_t,uint32_t,bool,UID) {}
}
bool gbBridgeRunning = true;
struct GlobalOptions { static unsigned getCommandRetries() { return 1; } static unsigned getCommandTimeout() { return 1; } };
struct BridgeState {
  enum class ProcessState { Running, DoneProcessing };
  inline static ProcessState state=ProcessState::Running;
  static ProcessState getServerState_NoLock() { return state; }
};
struct FakeData {
  size_t pos=2, capacity=8, writes=0;
  std::function<void()> onPosition;
  size_t get_pos() const { return pos; }
  size_t get_total_size() const { return capacity; }
  std::string getName() const { return "test"; }
  Result begin_batch() { return Result::Success; } size_t end_batch() { return 0; }
  Result push(uint32_t) { ++writes; pos=(pos+1)%capacity; return Result::Success; }
  Result push(uint32_t n,const void*) { writes+=1+(n+3)/4; pos=(pos+1+(n+3)/4)%capacity; return Result::Success; }
  template<typename... T> Result push_many(T... v) { (push(static_cast<uint32_t>(v)),...); return Result::Success; }
  Result begin_blob_push(size_t, uint8_t*&) { return Result::Failure; } void end_blob_push() {}
};
struct FakeSemaphore {
  unsigned waits=0; Result result=Result::Timeout; std::function<void()> onWait;
  Result wait() { ++waits; if(onWait) onWait(); return result; }
};
struct FakeCommands {
  unsigned published=0;
  Result push(Header) { ++published; return Result::Success; }
  std::vector<Commands::D3D9Command> getWriterQueueData() { return {}; }
  std::vector<Commands::D3D9Command> getReaderQueueData() { return {}; }
};
struct WriterChannel {
  int64_t consumed=3, expected=-1; bool reset=false;
  int64_t* serverDataPos=&consumed; int64_t* clientDataExpectedPos=&expected; bool* serverResetPosRequired=&reset;
  FakeData storage; FakeSemaphore semaphore; FakeCommands headers;
  FakeData* data=&storage; FakeSemaphore* dataSemaphore=&semaphore; FakeCommands* commands=&headers;
  std::atomic<bool> progress{false}; std::atomic<bool>* pbCmdInProgress=&progress; mutable std::mutex m_mutex;
  size_t get_data_pos() const { if(storage.onPosition) storage.onPosition(); return storage.pos; }
};
struct ReaderChannel { FakeCommands* commands=nullptr; };
#ifdef _MSC_VER
// Existing production narrowing/sign comparisons are evidence, not new code.
#pragma warning(push)
#pragma warning(disable: 4018 4244 4267)
#endif
// INSERT_PRODUCTION_CONTROL_FLOW
#ifdef _MSC_VER
#pragma warning(pop)
#endif
using Tested = Bridge<BridgeId::Device>;
void check(bool condition, const char* message) { if(!condition) { std::fprintf(stderr,"FAIL: %s\n",message); std::exit(1); } }
int main() {
  for(int repeat=0;repeat<1000;++repeat) {
    gbBridgeRunning=true; BridgeState::state=BridgeState::ProcessState::Running;
    WriterChannel channel; Tested::install(&channel);
    // Consume after the cached read, before registration. No notification was due.
    channel.storage.onPosition=[&]() { if(channel.storage.pos==3) channel.consumed=0; };
    {
      Tested::Command command(Commands::Test);
      command.send_data(77);
      check(channel.semaphore.waits>0,"cached progress must reproduce stale wait");
    }
    check(channel.storage.writes==2,"timeout still allowed UID and payload writes");
    check(channel.headers.published==1,"timeout still published Header");
  }
  for(auto result: {Result::Timeout,Result::Failure}) {
    gbBridgeRunning=true; WriterChannel channel; Tested::install(&channel);
    channel.semaphore.result=result;
    { Tested::Command command(Commands::Test); command.send_data(42); }
    check(channel.semaphore.waits>0 && channel.storage.writes==2 && channel.headers.published==1,
      "wait failure must reproduce write and publish");
  }
  std::puts("BASELINE_REPRODUCED stale-progress-wait=1000/1000 timeout-write-publish=YES system-failure-write-publish=YES");
}
