// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include <windows.h>
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <memory>
#include <map>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <type_traits>
#include <vector>
#include "config/global_options.h"
#include "log/log.h"
#include "log/log_strings.h"
#include "util_common.h"
#include "util_commands.h"
#include "util_circularbuffer.h"
#include "util_semaphore.h"
#include "util_ipcchannel.h"
#include "api_wait_diagnostics.h"
#include "data_diagnostics.h"
#include "exception_diagnostics.h"
#include "device_reset.h"
#define ZoneScoped
using namespace bridge_util;
std::atomic<bool> gbBridgeRunning {true};
bridge_util::Guid gUniqueIdentifier;
struct BridgeState {
  enum class ProcessState { Running, DoneProcessing };
  static ProcessState getServerState_NoLock() { return ProcessState::Running; }
};
