// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
int main(){
 const DWORD shader[2]={D3DVS_VERSION(3,0),0xffff};
 for(unsigned mode=0;mode<4;++mode){
  failSubmission=mode==0;failReply=mode==1;malformedReply=mode==2;optionalReply=mode!=0;
  auto invoke=[&](auto call){gbBridgeRunning=true;const auto before=liveResources;const auto hr=call();assert(liveResources==before);return hr;};
  Direct3DDevice9Ex_LSS<true> device;
  IDirect3DVertexBuffer9* vb=nullptr;
  assert(FAILED(invoke([&](){const auto hr=device.CreateVertexBuffer(64,D3DUSAGE_DYNAMIC,0,D3DPOOL_DEFAULT,&vb,nullptr);if(mode==3){assert(hr==S_OK);assert(vb);vb->Release();vb=nullptr;return E_FAIL;}return hr;})) && !vb);
  IDirect3DIndexBuffer9* ib=nullptr;
  assert(FAILED(invoke([&](){const auto hr=device.CreateIndexBuffer(64,D3DUSAGE_DYNAMIC,D3DFMT_INDEX16,D3DPOOL_DEFAULT,&ib,nullptr);if(mode==3){assert(hr==S_OK);assert(ib);ib->Release();ib=nullptr;return E_FAIL;}return hr;})) && !ib);
  IDirect3DVertexShader9* vs=nullptr;
  assert(FAILED(invoke([&](){const auto hr=device.CreateVertexShader(shader,&vs);if(mode==3){assert(hr==S_OK);assert(vs);vs->Release();vs=nullptr;return E_FAIL;}return hr;})) && !vs);
  IDirect3DPixelShader9* ps=nullptr;
  assert(FAILED(invoke([&](){const auto hr=device.CreatePixelShader(shader,&ps);if(mode==3){assert(hr==S_OK);assert(ps);ps->Release();ps=nullptr;return E_FAIL;}return hr;})) && !ps);
  IDirect3DStateBlock9* sb=nullptr;
  assert(FAILED(invoke([&](){const auto hr=device.CreateStateBlock(D3DSBT_ALL,&sb);if(mode==3){assert(hr==S_OK);assert(sb);sb->Release();sb=nullptr;return E_FAIL;}return hr;})) && !sb);
  gbBridgeRunning=true;
  if(mode<3){assert(FAILED(device.BeginStateBlock()) && !device.m_stateRecording);}
  else{assert(device.BeginStateBlock()==S_OK && device.m_stateRecording);assert(device.EndStateBlock(&sb)==S_OK && sb && !device.m_stateRecording);sb->Release();}
  assert(liveResources==0);
 }
 // EndStateBlock failed submission retains device ownership, never caller ownership.
 {Direct3DDevice9Ex_LSS<true> device;gbBridgeRunning=true;optionalReply=false;failSubmission=false;failReply=false;malformedReply=false;
  assert(device.BeginStateBlock()==S_OK);failSubmission=true;IDirect3DStateBlock9* sb=nullptr;
  assert(device.EndStateBlock(&sb)==D3DERR_DEVICELOST && !sb && device.m_stateRecording && liveResources==1);}
 assert(liveResources==0 && releasedResources>20);
 std::printf("IPC_API_OWNERSHIP_PASS released=%u no-failed-success no-output-reference-leak\n",releasedResources);
}
