// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
using Device = Bridge<BridgeId::Device>;
using Module = Bridge<BridgeId::Module>;
void require(bool value,const char* message) {
  if (!value) { std::fprintf(stderr,"IPC_TEST_FAIL %s pid=%lu\n",message,GetCurrentProcessId()); std::exit(2); }
}
uint32_t pattern(uint32_t sequence,uint32_t offset) { return sequence*1664525u+offset*1013904223u; }
template<typename B> void receive(uint32_t sequence,bool request) {
  require(B::waitForCommand()==Result::Success,"wait packet");
#ifdef REMIX_BRIDGE_SERVER
  const auto header=B::pop_front();
  const auto uid=B::get_data();
#endif
  require(B::get_data()==sequence,"packet order");
  const auto size=B::get_data();
  require(size==sequence%65,"size metadata");
  void* data=nullptr;
  require(B::get_data(&data)==size,"blob prefix");
  if (size) { require(data!=nullptr,"nonempty payload pointer"); }
  for(uint32_t i=0;i<size;++i) { require(static_cast<uint8_t*>(data)[i]==static_cast<uint8_t>(pattern(sequence,i)),"payload integrity"); }
  // Do not release the arena while any application pointer is still being used.
#ifdef REMIX_BRIDGE_SERVER
  B::end_read_data();
  if (request) {
    typename B::Command reply(Commands::Bridge_Response,uid);
    std::array<uint8_t,64> bytes{};
    for(uint32_t i=0;i<size;++i){ bytes[i]=static_cast<uint8_t>(pattern(sequence,i)); }
    reply.send_many(sequence,size);reply.send_data(size,bytes.data());
    require(reply.finish()==Result::Success,"reply commit");
  }
  (void)header;
#else
  (void)request;
  B::pop_front();
#endif
}
template<typename B> void send(uint32_t sequence,bool reply) {
  const auto size=sequence%65;
  std::array<uint8_t,64> bytes{};
  for(uint32_t i=0;i<size;++i){ bytes[i]=static_cast<uint8_t>(pattern(sequence,i)); }
  {
    typename B::Command command(Commands::Bridge_Response);
    command.send_many(sequence,size);
    command.send_data(size,bytes.data());
    require(command.finish()==Result::Success,"request commit");
  }
  if(reply){ receive<B>(sequence,false); }
}
int wmain(int argc,wchar_t** argv) {
  if(argc==2 && std::wstring(argv[1])==L"faults") {
    // No peer: an unpublished batch exceeding capacity must stop before Header.
    const size_t memory=32*sizeof(Header)+256+128*sizeof(uint32_t);
    WriterChannel writer("failedBatch",memory,32,128);
    ReaderChannel reader("failedReply",memory,32,128);Device::install(&writer,&reader);
    {
      Device::Command command(Commands::Bridge_Response);
      command.send_data(71);
      const auto before=writer.data->cursor();
      require(command.begin_data_blob(128*4)==nullptr,"oversize reserve null");
      command.send_data(99);
      require(writer.data->cursor()==before,"failed batch wrote again");
      require(command.finish()!=Result::Success,"failed batch success");
    }
    require(writer.commands->isEmpty(),"failed batch Header publication");
    require(writer.control->fault.load()==1 && !Device::healthy(),"channel poison");
    { Device::Command later(Commands::Bridge_Response);require(later.finish()!=Result::Success,"later false success"); }
    require(writer.commands->isEmpty(),"later Header after poison");
    std::puts("IPC_NATIVE_FAULT_PASS partial-batch oversize null-pointer no-write no-header poison subsequent-failure");
    return 0;
  }
  require(argc>=3,"arguments: guid count");
  require(gUniqueIdentifier.setGuid(&argv[1]),"session GUID");
  const auto count=static_cast<uint32_t>(std::wcstoul(argv[2],nullptr,10));
  const size_t memory=32*sizeof(Header)+256+128*sizeof(uint32_t);
#ifdef REMIX_BRIDGE_CLIENT
  const char* forward="Forward";const char* reverse="Reverse";
#else
  const char* forward="Reverse";const char* reverse="Forward";
#endif
  WriterChannel writer(std::string("Device")+forward,memory,32,128);
  ReaderChannel reader(std::string("Device")+reverse,memory,32,128);
  WriterChannel moduleWriter(std::string("Module")+forward,memory,32,128);
  ReaderChannel moduleReader(std::string("Module")+reverse,memory,32,128);
  Device::install(&writer,&reader);Module::install(&moduleWriter,&moduleReader);
  for(uint32_t sequence=0;sequence<count;++sequence) {
    const bool reply=(sequence%17)==0;
#ifdef REMIX_BRIDGE_CLIENT
    send<Device>(sequence,reply);send<Module>(sequence,reply);
#else
    receive<Device>(sequence,reply);receive<Module>(sequence,reply);
#endif
  }
  // Force an ordered final response in both queues before either process exits.
#ifdef REMIX_BRIDGE_CLIENT
  send<Device>(count,true);send<Module>(count,true);
#else
  receive<Device>(count,true);receive<Module>(count,true);
#endif
  std::printf("IPC_NATIVE_TRANSPORT_PASS pointer_bits=%u packets_per_channel=%u capacity_dwords=128 device+module forward+reverse\n",
    static_cast<unsigned>(sizeof(void*)*8),count+1);
  return 0;
}
