// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once
#include <d3d9.h>
#include <atomic>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <string>
#include "texture_creation.h"
#include "util_common.h"
#include "util_commands.h"
#include "api_wait_diagnostics.h"
using namespace bridge_util;
struct BridgeReadFailure {};
inline std::atomic<bool> gbBridgeRunning{true};
inline bool failSubmission=false, failReply=false, malformedReply=false, optionalReply=false;
inline unsigned liveResources=0, releasedResources=0, submissions=0;
struct GlobalOptions {
 static bool getSendCreateFunctionServerResponses(){return optionalReply;}
 static bool getSendAllServerResponses(){return optionalReply;}
 static uint32_t getAckTimeout(){return 10;}
};
template<class... Args> std::string format_string(const char*, Args...) { return {}; }
struct Logger {static void err(const std::string&){}};
struct DeviceBridge {
 static bool healthy(){return gbBridgeRunning.load();}
 static Result waitForCommand(Commands::D3D9Command,uint32_t,void*,bool,UID){return failReply?Result::Failure:Result::Success;}
 static uint32_t get_data(){if(malformedReply){throw BridgeReadFailure{};}return S_OK;}
 static void pop_front(){}
};
struct ClientMessage {
 ClientMessage(Commands::D3D9Command,uint32_t){}
 ~ClientMessage(){if(failSubmission){gbBridgeRunning=false;}}
 template<class...T>void send_many(T...){}
 void send_data(uint32_t){} void send_data(uint32_t,const void*){}
 UID get_uid(){return ++submissions;}
 Result finish(){if(failSubmission){gbBridgeRunning=false;return Result::Failure;}return Result::Success;}
};
#define ZoneScoped
#define LogFunctionCall()
#define BRIDGE_DEVICE_LOCKGUARD()
template<class T>T* trackWrapper(T* resource){return resource;}
// COM adapters count ownership; allocation/cleanup decisions use actual API bodies.
#define COM_REFS \
 ULONG refs=1; \
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID,void**)override{return E_NOINTERFACE;} \
 ULONG STDMETHODCALLTYPE AddRef()override{return ++refs;} \
 ULONG STDMETHODCALLTYPE Release()override{const auto left=--refs;if(!left){--liveResources;++releasedResources;delete this;}return left;} \
 HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9**)override{return E_NOTIMPL;} \
 uint32_t getId()const{return 7;} \
 void cancelServerCreation(){}
template<class I,class D,D3DRESOURCETYPE Type>struct FakeBuffer: I {
 FakeBuffer(void*,const D&){++liveResources;} COM_REFS
 HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID,const void*,DWORD,DWORD)override{return E_NOTIMPL;}
 HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID,void*,DWORD*)override{return E_NOTIMPL;}
 HRESULT STDMETHODCALLTYPE FreePrivateData(REFGUID)override{return E_NOTIMPL;}
 DWORD STDMETHODCALLTYPE SetPriority(DWORD)override{return 0;}
 DWORD STDMETHODCALLTYPE GetPriority()override{return 0;}
 void STDMETHODCALLTYPE PreLoad()override{}
 D3DRESOURCETYPE STDMETHODCALLTYPE GetType()override{return Type;}
 HRESULT STDMETHODCALLTYPE Lock(UINT,UINT,void**,DWORD)override{return E_NOTIMPL;}
 HRESULT STDMETHODCALLTYPE Unlock()override{return E_NOTIMPL;}
 HRESULT STDMETHODCALLTYPE GetDesc(D*)override{return E_NOTIMPL;}
};
using Direct3DVertexBuffer9_LSS=FakeBuffer<IDirect3DVertexBuffer9,D3DVERTEXBUFFER_DESC,D3DRTYPE_VERTEXBUFFER>;
using Direct3DIndexBuffer9_LSS=FakeBuffer<IDirect3DIndexBuffer9,D3DINDEXBUFFER_DESC,D3DRTYPE_INDEXBUFFER>;
struct CommonShader {explicit CommonShader(const DWORD*){}unsigned getMajorVersion(){return 3;}};
template<class I>struct FakeShader:I {
 FakeShader(void*,CommonShader&){++liveResources;} COM_REFS
 HRESULT STDMETHODCALLTYPE GetFunction(void*,UINT* size)override{*size=8;return S_OK;}
};
using Direct3DVertexShader9_LSS=FakeShader<IDirect3DVertexShader9>;
using Direct3DPixelShader9_LSS=FakeShader<IDirect3DPixelShader9>;
struct Direct3DStateBlock9_LSS:IDirect3DStateBlock9 {
 explicit Direct3DStateBlock9_LSS(void*){++liveResources;} COM_REFS
 unsigned m_dirtyFlags=0;void LocalCapture(){}
 HRESULT STDMETHODCALLTYPE Capture()override{return S_OK;}
 HRESULT STDMETHODCALLTYPE Apply()override{return S_OK;}
};
inline void StateBlockSetCaptureFlags(D3DSTATEBLOCKTYPE,unsigned&){}
template<bool EnableSync>struct Direct3DDevice9Ex_LSS {
 D3DCAPS9 m_caps{};Direct3DStateBlock9_LSS* m_stateRecording=nullptr;
 Direct3DDevice9Ex_LSS(){m_caps.VertexShaderVersion=D3DVS_VERSION(3,0);m_caps.PixelShaderVersion=D3DPS_VERSION(3,0);}
 ~Direct3DDevice9Ex_LSS(){if(m_stateRecording){m_stateRecording->Release();}}
 uint32_t getId(){return 1;}
 HRESULT CreateVertexBuffer(UINT,DWORD,DWORD,D3DPOOL,IDirect3DVertexBuffer9**,HANDLE*);
 HRESULT CreateIndexBuffer(UINT,DWORD,D3DFORMAT,D3DPOOL,IDirect3DIndexBuffer9**,HANDLE*);
 HRESULT CreateVertexShader(const DWORD*,IDirect3DVertexShader9**);
 HRESULT CreatePixelShader(const DWORD*,IDirect3DPixelShader9**);
 HRESULT CreateStateBlock(D3DSTATEBLOCKTYPE,IDirect3DStateBlock9**);
 HRESULT BeginStateBlock();HRESULT EndStateBlock(IDirect3DStateBlock9**);
};
