// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
using Device=Bridge<BridgeId::Device>;
void require(bool value,const char* message) {
  if(!value){std::fprintf(stderr,"IPC_PERF_FAIL %s\n",message);std::exit(2);}
}
uint64_t ticks(FILETIME value){return(static_cast<uint64_t>(value.dwHighDateTime)<<32)|value.dwLowDateTime;}
uint64_t cpuNow(){FILETIME c{},e{},k{},u{};GetThreadTimes(GetCurrentThread(),&c,&e,&k,&u);return ticks(k)+ticks(u);}
int wmain(int argc,wchar_t** argv){
  require(argc==7,"arguments guid count bytes mode capacity layout");
  require(gUniqueIdentifier.setGuid(&argv[1]),"guid");
  const auto count=static_cast<uint32_t>(std::wcstoul(argv[2],nullptr,10));
  const auto size=static_cast<uint32_t>(std::wcstoul(argv[3],nullptr,10));
  const std::wstring mode=argv[4];
  const bool batched=mode==L"batch" || mode==L"near-full";
  const auto capacity=static_cast<uint32_t>(std::wcstoul(argv[5],nullptr,10));
  const bool known=std::wstring(argv[6])==L"known";
  const uint32_t commandCapacity=32768;
  const size_t memory=commandCapacity*sizeof(Header)+256+static_cast<size_t>(capacity)*4;
#ifdef REMIX_BRIDGE_CLIENT
  WriterChannel writer("PerfForward",memory,commandCapacity,capacity);ReaderChannel reader("PerfReverse",memory,commandCapacity,capacity);
#else
  ReaderChannel reader("PerfForward",memory,commandCapacity,capacity);WriterChannel writer("PerfReverse",memory,commandCapacity,capacity);
#endif
  Device::install(&writer,&reader);
  const auto session=gUniqueIdentifier.toString();
  HANDLE ready=CreateEventA(nullptr,TRUE,FALSE,(session+"Ready").c_str());
  HANDLE start=CreateEventA(nullptr,TRUE,FALSE,(session+"Start").c_str());
  HANDLE done=CreateEventA(nullptr,TRUE,FALSE,(session+"Done").c_str());
  require(ready && start && done,"events");
  LARGE_INTEGER frequency{},begin{},end{},complete{};QueryPerformanceFrequency(&frequency);
  std::vector<uint8_t> bytes(size,0x6b);
#ifdef REMIX_BRIDGE_CLIENT
  require(WaitForSingleObject(ready,5000)==WAIT_OBJECT_0,"host ready");
  if(!batched){SetEvent(start);}
  ULONG64 cyclesBegin=0,cyclesEnd=0;QueryThreadCycleTime(GetCurrentThread(),&cyclesBegin);
  const auto cpuBegin=cpuNow();QueryPerformanceCounter(&begin);
  for(uint32_t sequence=0;mode!=L"idle" && sequence<count;++sequence){
#ifdef IPC_KNOWN_PACKET
    if(known){
      Device::Command command(Commands::Bridge_Response,0,0,bridge_data::payload(size,size?bytes.data():nullptr,sequence,size));
      require(command.finish()==Result::Success,"Client known submission");
    } else
#endif
    {
    Device::Command command(Commands::Bridge_Response);
    command.send_many(sequence,size);command.send_data(size,size?bytes.data():nullptr);
#ifndef IPC_OLD_BASELINE
    require(command.finish()==Result::Success,"Client submission");
#endif
    }
  }
  QueryPerformanceCounter(&end);const auto cpuEnd=cpuNow();QueryThreadCycleTime(GetCurrentThread(),&cyclesEnd);
  if(batched){SetEvent(start);}
  require(WaitForSingleObject(done,15000)==WAIT_OBJECT_0,"Host completion");QueryPerformanceCounter(&complete);
  const char* role="client";
#else
  SetEvent(ready);require(WaitForSingleObject(start,5000)==WAIT_OBJECT_0,"batch start");
  ULONG64 cyclesBegin=0,cyclesEnd=0;QueryThreadCycleTime(GetCurrentThread(),&cyclesBegin);
  const auto cpuBegin=cpuNow();QueryPerformanceCounter(&begin);
  if(mode==L"idle") {Result result;reader.commands->peek(result,500);require(result==Result::Timeout,"idle queue wait");}
  for(uint32_t sequence=0;mode!=L"idle" && sequence<count;++sequence){
    require(Device::waitForCommand()==Result::Success,"Host packet wait");const auto header=Device::pop_front();
#ifdef IPC_KNOWN_PACKET
    if(known){
#ifdef IPC_SEPARATE_CALLER
      // Production Device dispatch reads the common UID before switching to
      // the handler, whose known remainder excludes that UID.
      require(Device::get_data()==sequence,"Host common UID order");
      const auto packet=Device::get_packet<2>();
      require(packet.fields[0]==sequence && packet.fields[1]==size,"Host known metadata order");
#else
      const auto packet=Device::get_packet<3>();
      require(packet.fields[0]==sequence && packet.fields[1]==sequence && packet.fields[2]==size,"Host known metadata order");
#endif
      require(packet.bytes==size,"Host known blob size");
      if(size){require(packet.data && static_cast<uint8_t*>(packet.data)[0]==0x6b && static_cast<uint8_t*>(packet.data)[size-1]==0x6b,"Host known payload integrity");}
    } else
#endif
    {
    require(Device::get_data()==sequence,"Host UID order");require(Device::get_data()==sequence,"Host metadata order");
    require(Device::get_data()==size,"Host size");void* pointer=nullptr;
    require(Device::get_data(&pointer)==size,"Host blob size");
    if(size){require(pointer && static_cast<uint8_t*>(pointer)[0]==0x6b && static_cast<uint8_t*>(pointer)[size-1]==0x6b,"Host payload integrity");}
    }
    require(Device::get_data_pos()==header.dataOffset,"Host packet boundary");
#ifdef IPC_OLD_BASELINE
    benchmarkComplete();
#else
    Device::end_read_data();
#endif
    if(mode==L"slow" && (sequence%64)==0){Sleep(1);}
  }
  QueryPerformanceCounter(&end);const auto cpuEnd=cpuNow();QueryThreadCycleTime(GetCurrentThread(),&cyclesEnd);complete=end;SetEvent(done);const char* role="host";
#endif
  const auto ns=static_cast<double>(end.QuadPart-begin.QuadPart)*1e9/static_cast<double>(frequency.QuadPart);
  const auto total=static_cast<double>(complete.QuadPart-begin.QuadPart)*1e9/static_cast<double>(frequency.QuadPart);
  std::printf("{\"role\":\"%s\",\"count\":%u,\"bytes\":%u,\"wall_ns_call\":%.3f,\"cpu_ns_call\":%.3f,\"end_to_end_ns_call\":%.3f,\"cycles_call\":%.3f,\"channel_bytes\":%u,\"command_bytes\":%u}\n",role,count,size,ns/count,static_cast<double>(cpuEnd-cpuBegin)*100/count,total/count,static_cast<double>(cyclesEnd-cyclesBegin)/count,static_cast<unsigned>(sizeof(WriterChannel)),static_cast<unsigned>(sizeof(Device::Command)));
  CloseHandle(ready);CloseHandle(start);CloseHandle(done);return 0;
}
