// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include "memory_sampling_test_shared.h"
#include <cstdlib>
#include <cstring>
#include <new>

static SamplingTestState* state;
void* operator new(std::size_t size) {
  if (state && InterlockedCompareExchange(&state->failNew, 0, 0)) {
    InterlockedIncrement(&state->newAttempts);
    throw std::bad_alloc();
  }
  if (void* p = std::malloc(size ? size : 1)) { return p; }
  throw std::bad_alloc();
}
void* operator new[](std::size_t size) { return ::operator new(size); }
void operator delete(void* p) noexcept { std::free(p); }
void operator delete[](void* p) noexcept { std::free(p); }
void operator delete(void* p, std::size_t) noexcept { std::free(p); }
void operator delete[](void* p, std::size_t) noexcept { std::free(p); }

static ULONGLONG WINAPI testClock() {
  InterlockedIncrement(&state->clockReads);
  return static_cast<ULONGLONG>(InterlockedCompareExchange64(&state->clock, 0, 0));
}
static BOOL WINAPI testReference(DWORD flags, LPCWSTR address, HMODULE* module) {
  InterlockedIncrement(&state->referenceCalls);
  const bool owns = (flags & GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT) == 0;
  if (owns && InterlockedCompareExchange(&state->failReference, 0, 0)) {
    SetLastError(ERROR_MOD_NOT_FOUND); return FALSE;
  }
  const BOOL result = GetModuleHandleExW(flags, address, module);
  if (owns && result) { InterlockedIncrement(&state->acquired); }
  return result;
}
static BOOL WINAPI testSubmit(PTP_SIMPLE_CALLBACK callback, PVOID context, PTP_CALLBACK_ENVIRON) {
  InterlockedIncrement(&state->submissions);
  if (InterlockedCompareExchange(&state->failSubmit, 0, 0)) {
    SetLastError(ERROR_NOT_ENOUGH_MEMORY); return FALSE;
  }
  return TrySubmitThreadpoolCallback(callback, context, state->environment);
}
static VOID WINAPI testDeferredFree(PTP_CALLBACK_INSTANCE instance, HMODULE module) {
  InterlockedIncrement(&state->deferred);
  FreeLibraryWhenCallbackReturns(instance, module);
}
static BOOL WINAPI testFree(HMODULE module) {
  InterlockedIncrement(&state->released); return FreeLibrary(module);
}
static SIZE_T WINAPI testQuery(LPCVOID address, PMEMORY_BASIC_INFORMATION result, SIZE_T size) {
  InterlockedIncrement(&state->queryCalls);
  if (InterlockedCompareExchange(&state->blockNextQuery, 0, 1) == 1) {
    SetEvent(state->queryEntered);
    if (WaitForSingleObject(state->queryRelease, 10000) != WAIT_OBJECT_0) {
      InterlockedIncrement(&state->queryTimeout);
    }
  }
  return VirtualQuery(address, result, size);
}
static HANDLE WINAPI testOpen(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE) {
  InterlockedIncrement(&state->opens);
  // The log sink is captured in fixed storage; no disk or heap is used by it.
  return reinterpret_cast<HANDLE>(static_cast<uintptr_t>(0x1234));
}
static BOOL WINAPI testWrite(HANDLE, LPCVOID bytes, DWORD count, LPDWORD written, LPOVERLAPPED) {
  AcquireSRWLockExclusive(&state->recordsLock);
  const LONG index = state->logCount;
  if (index >= 64 || count >= sizeof(state->logs[0].text)) {
    ReleaseSRWLockExclusive(&state->recordsLock); return FALSE;
  }
  state->logs[index].thread = GetCurrentThreadId();
  std::memcpy(state->logs[index].text, bytes, count);
  state->logs[index].text[count] = '\0';
  InterlockedIncrement(&state->logCount);
  ReleaseSRWLockExclusive(&state->recordsLock);
  if (written) { *written = count; }
  return TRUE;
}
static BOOL WINAPI testFlush(HANDLE) {
  state->flushThread = GetCurrentThreadId(); InterlockedIncrement(&state->flushCount); return TRUE;
}
static VOID WINAPI testLock(PSRWLOCK lock) {
  InterlockedIncrement(&state->locks); AcquireSRWLockExclusive(lock);
}

// Compile the real header and callback. Adapters only control Win32 boundaries,
// capture logging, and inject scheduler failure; the DLL lifetime APIs are real.
#define GetTickCount64 testClock
#define GetModuleHandleExW testReference
#define TrySubmitThreadpoolCallback testSubmit
#define FreeLibraryWhenCallbackReturns testDeferredFree
#define FreeLibrary testFree
#define VirtualQuery testQuery
#define CreateFileW testOpen
#define WriteFile testWrite
#define FlushFileBuffers testFlush
#define AcquireSRWLockExclusive testLock
#include "memory_diagnostics.h"
#undef GetTickCount64
#undef GetModuleHandleExW
#undef TrySubmitThreadpoolCallback
#undef FreeLibraryWhenCallbackReturns
#undef FreeLibrary
#undef VirtualQuery
#undef CreateFileW
#undef WriteFile
#undef FlushFileBuffers
#undef AcquireSRWLockExclusive

extern "C" __declspec(dllexport) void configure(SamplingTestState* testState) {
  state = testState;
}
extern "C" __declspec(dllexport) void monitoring(int enabled) { l4d2_observation::memoryMonitoring = enabled != 0; }
extern "C" __declspec(dllexport) void sample(int force, const char* event) {
  l4d2_memory::sample(force != 0, event, l4d2_memory::Kind::Vertex, 12345, 67, 89, 21, 8);
}
extern "C" __declspec(dllexport) void deadline(ULONGLONG value) { l4d2_memory::nextSample.store(value); }
extern "C" __declspec(dllexport) int pending() { return l4d2_memory::detail::pending.load() ? 1 : 0; }
