// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include "overlay_presenter.h"
#include "steam_activity_diagnostics.h"
#include <cstdio>
#include <cstdlib>
#include <string>

static void require(bool condition, const char* reason) {
  if (!condition) { std::fprintf(stderr, "%s (error %lu)\n", reason, GetLastError()); std::exit(1); }
}
static bool enabled(HWND window, bool expected) {
  for (int i = 0; i < 100; ++i) {
    if ((IsWindowEnabled(window) != FALSE) == expected) { return true; }
    Sleep(10);
  }
  return false;
}
int main(int argc, char** argv) {
  if (argc == 3 && std::string(argv[1]) == "--child") {
    const HWND parent = reinterpret_cast<HWND>(static_cast<uintptr_t>(std::strtoull(argv[2], nullptr, 10)));
    // Input is enabled to exercise the foreground-scoped hook and public ABI.
    std::string diagnosticLog;
    l4d2_overlay::InputDiagnostics disabled(false, "test", [&](const char* line) { diagnosticLog += line; });
    disabled.message(WM_LBUTTONDOWN, 0); disabled.sample(parent, nullptr, false);
    require(diagnosticLog.empty(), "diagnostics are inert by default");
    l4d2_overlay::Presenter presenter(true, VK_HOME, false,
      [&](const char* line) { diagnosticLog += line; diagnosticLog += "\n"; }, true, true);
    char modulePath[MAX_PATH] {}; require(GetModuleFileNameA(nullptr, modulePath, MAX_PATH) != 0, "test module path");
    std::string fakePath(modulePath); fakePath = fakePath.substr(0, fakePath.find_last_of("\\/")) + (sizeof(void*) == 8 ? "\\fake-x64.dll" : "\\fake-x86.dll");
    HMODULE fake = LoadLibraryA(fakePath.c_str()); require(fake != nullptr, "load API test double");
    const std::string steamPath = fakePath.substr(0, fakePath.find_last_of("\\/")) + (sizeof(void*) == 8 ? "\\SteamOverlayVulkanLayer64.dll" : "\\SteamOverlayVulkanLayer.dll");
    require(CopyFileA(fakePath.c_str(), steamPath.c_str(), FALSE) != FALSE, "create named Steam module test double");
    const unsigned oldModules = l4d2_overlay::Presenter::steamModules();
    HMODULE steam = LoadLibraryA(steamPath.c_str()); require(steam != nullptr, "load named Steam Vulkan test double");
    const unsigned bit = sizeof(void*) == 8 ? 2u : 1u;
    require((l4d2_overlay::Presenter::steamModules() & bit) != 0, "detect correct Steam Vulkan module name");
    FreeLibrary(steam);
    require(l4d2_overlay::Presenter::steamModules() == oldModules, "detect delayed Steam module unload");
    require(DeleteFileA(steamPath.c_str()) != FALSE, "remove named Steam test double");
    std::string activityLog;
    require(!l4d2_overlay::SteamActivityDiagnostics::observe([&](const char* line) { activityLog += line; }),
      "observer waits for game's Steam API without loading it");
    const std::string apiPath = fakePath.substr(0, fakePath.find_last_of("\\/")) + "\\steam_api.dll";
    require(CopyFileA(fakePath.c_str(), apiPath.c_str(), FALSE) != FALSE, "create Steam API test double");
    HMODULE api = LoadLibraryA(apiPath.c_str()); require(api != nullptr, "load Steam API test double");
    require(l4d2_overlay::SteamActivityDiagnostics::observe([&](const char* line) { activityLog += line; activityLog += "\n"; }),
      "register legacy activation observer after delayed API load");
    auto rawActive = GetProcAddress(api, "TestSteamActive");
    bool (*setActive)(bool) = nullptr; std::memcpy(&setActive, &rawActive, sizeof(setActive));
    require(setActive && setActive(true) && setActive(false), "deliver legacy activation and deactivation callbacks");
    require(activityLog.find("registered=1 callback=331 payload_bytes=1") != std::string::npos
      && activityLog.find("active=1 callback=331") != std::string::npos
      && activityLog.find("active=0 callback=331") != std::string::npos, "observe both Steam transitions");
    require(activityLog.find("sdk_flags=1 sdk_callback=331") != std::string::npos,
      "report SDK-written registration fields on both architectures");
    require(!presenter.capturing(), "Steam diagnostics do not change capture policy");
    const HWND child = presenter.window(parent);
    require(child != nullptr, "cross-process child creation");
    DWORD pid = 0; GetWindowThreadProcessId(child, &pid);
    require(pid == GetCurrentProcessId(), "presenter must belong to host process");
    require(GetParent(child) == parent, "presenter must remain inside game window");
    require(presenter.route(parent) == child && presenter.route(nullptr) == nullptr, "present override routing");
    require(enabled(child, false), "input initially passes through disabled child");
    presenter.sampleInput();
    require(diagnosticLog.find("event=modules role=host") != std::string::npos, "both-process module observation available");
    require(diagnosticLog.find("presenter_pid=" + std::to_string(GetCurrentProcessId())) != std::string::npos,
      "diagnostic identifies actual presenter owner");
    require(diagnosticLog.find("enabled=0 capture=0") != std::string::npos, "disabled mouse target is observable");
    require(diagnosticLog.find("local_gui_ok=") != std::string::npos, "host and foreground thread focus observed separately");
    const std::string firstSample = diagnosticLog;
    presenter.sampleInput(); require(diagnosticLog == firstSample, "diagnostic polling is throttled");
    l4d2_overlay::InputDiagnostics counted(true, "test", [&](const char* line) { diagnosticLog += line; });
    counted.message(WM_MOUSEMOVE, 0); counted.message(WM_KEYDOWN, VK_HOME); counted.message(WM_INPUT, 0);
    counted.forwarded(); counted.sample(parent, child, false);
    require(diagnosticLog.find("mouse=1 keyboard=1 raw=1 forward=1") != std::string::npos,
      "count message classes without recording input contents");
    require(presenter.bindReShade(fake), "register documented API and overlay callback");
    auto rawToggle = GetProcAddress(fake, "TestToggleOverlay");
    bool (*toggle)(bool) = nullptr; std::memcpy(&toggle, &rawToggle, sizeof(toggle));
    require(toggle && toggle(true), "overlay event allows opening");
    require(presenter.capturing() && enabled(child, true), "overlay event captures mouse");
    require(toggle(false), "overlay event allows closing");
    require(!presenter.capturing() && enabled(child, false), "overlay event restores game input");
    const UINT steamMessage = RegisterWindowMessageW(L"L4D2BRIDGE_STEAM_ACTIVE");
    require(PostMessageW(child, steamMessage, 1, reinterpret_cast<LPARAM>(parent)) != FALSE, "post client Steam activation");
    require(enabled(child, true) && presenter.capturing(), "Steam activation enables mouse target");
    require(toggle(true) && toggle(false), "ReShade open and close during Steam capture");
    require(presenter.capturing() && enabled(child, true), "ReShade close does not release Steam input capture");
    require(toggle(true), "ReShade captures concurrently");
    presenter.steamCapture(false);
    require(presenter.capturing() && enabled(child, true), "Steam close does not release ReShade input capture");
    require(toggle(false), "close remaining ReShade capture");
    require(!presenter.capturing() && enabled(child, false), "both closed restores game input");
    require(SetWindowPos(parent, nullptr, 0, 0, 420, 240, SWP_NOMOVE | SWP_NOZORDER) != FALSE, "resize game window");
    bool resized = false;
    for (int i = 0; i < 100; ++i) {
      RECT a {}, b {}; GetClientRect(parent, &a); GetClientRect(child, &b);
      if (a.right == b.right && a.bottom == b.bottom) { resized = true; break; }
      Sleep(10);
    }
    require(resized, "presenter follows game client dimensions");
    presenter.stop(); require(!toggle(true), "callback unregistered on shutdown"); FreeLibrary(fake);
    presenter.stop(); require(!IsWindow(child), "presenter destruction and idempotent stop");
    std::printf("PASS: host-owned cross-process child, capture, reset routing, resizing and teardown (%zu-bit)\n", sizeof(void*) * 8);
    return 0;
  }
  require(argc == 2, "provide other architecture's test executable");
  WNDCLASSW wc {}; wc.lpfnWndProc = DefWindowProcW; wc.hInstance = GetModuleHandleW(nullptr); wc.lpszClassName = L"L4D2OverlayParentTest";
  require(RegisterClassW(&wc) != 0, "register simulated game window");
  HWND parent = CreateWindowW(wc.lpszClassName, L"L4D2 input compatibility test", WS_OVERLAPPEDWINDOW, 0, 0, 240, 120, nullptr, nullptr, wc.hInstance, nullptr);
  require(parent != nullptr, "create simulated game window");
  std::string command = std::string("\"") + argv[1] + "\" --child " + std::to_string(reinterpret_cast<uintptr_t>(parent));
  STARTUPINFOA startup {}; startup.cb = sizeof(startup); PROCESS_INFORMATION process {};
  require(CreateProcessA(nullptr, &command[0], nullptr, nullptr, FALSE, 0, nullptr, nullptr, &startup, &process) != FALSE, "launch cross-architecture host");
  const ULONGLONG deadline = GetTickCount64() + 15000;
  while (WaitForSingleObject(process.hProcess, 0) == WAIT_TIMEOUT && GetTickCount64() < deadline) {
    MSG message {}; while (PeekMessageW(&message, nullptr, 0, 0, PM_REMOVE)) { TranslateMessage(&message); DispatchMessageW(&message); }
    Sleep(5);
  }
  DWORD code = STILL_ACTIVE; GetExitCodeProcess(process.hProcess, &code);
  if (code == STILL_ACTIVE) { TerminateProcess(process.hProcess, 1); }
  CloseHandle(process.hThread); CloseHandle(process.hProcess); DestroyWindow(parent);
  require(code == 0, "cross-process host test exit");
  return 0;
}
