// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define NOMINMAX
#include "pageblock_residency.h"
#include "readback_backend.h"
#include "retention_policy.h"
#include <cassert>
#include <filesystem>
#include <cstdio>
#include <string>
#include <vector>
using namespace l4d2_residency;
using namespace l4d2_readback;

// Independent Host storage. This mock deliberately cannot access any client backing.
struct Backend {
  D3DSURFACE_DESC desc {};
  std::vector<uint8_t> pixels;
  uint32_t pitch;
  bool failed = false, locked = false;
  HRESULT descriptor(D3DSURFACE_DESC& result) { result = desc; return S_OK; }
  HRESULT synchronize(Response& response) { response.flushRequested = response.eventWait = 1; return S_OK; }
  HRESULT lock(D3DLOCKED_RECT& result) {
    if (failed) { return D3DERR_INVALIDCALL; }
    locked = true; result = { static_cast<INT>(pitch), pixels.data() }; return S_OK;
  }
  HRESULT unlock() { assert(locked); locked = false; return S_OK; }
};
D3DSURFACE_DESC descriptor(uint32_t format = kDxt5, uint32_t width = 256, uint32_t height = 256) {
  D3DSURFACE_DESC desc {}; desc.Width = width; desc.Height = height;
  desc.Format = static_cast<D3DFORMAT>(format); desc.Pool = D3DPOOL_MANAGED;
  desc.Type = D3DRTYPE_SURFACE; return desc;
}
void configure(Context& context, Backend& backend, std::string& log) {
  context.diagnostics = true;
  context.log = [&log](const char* line) { log += line; log += '\n'; };
  context.error = context.log;
  context.exchange = [&backend](const Request& request, Temporary& temporary, Response& response, uint64_t& elapsed) {
    const auto hr = temporary.create(request);
    if (FAILED(hr)) { return hr; }
    if (!runShared(backend, request, true, true) || temporary.wait(1000) != WAIT_OBJECT_0) { return E_FAIL; }
    response = temporary.response(); elapsed = 1; return static_cast<HRESULT>(response.hresult);
  };
}
Backend makeBackend(const D3DSURFACE_DESC& desc) {
  Layout layout; assert(residencyLayout(desc.Width, desc.Height, static_cast<uint32_t>(desc.Format), layout));
  Backend backend; backend.desc = desc; backend.pitch = layout.rowBytes + 32;
  backend.pixels.assign(static_cast<size_t>(backend.pitch) * layout.rows, 0xee);
  for (uint32_t row = 0; row < layout.rows; ++row) {
    for (uint32_t x = 0; x < layout.rowBytes; ++x) { backend.pixels[static_cast<size_t>(row) * backend.pitch + x] = static_cast<uint8_t>(row * 17 + x); }
  }
  return backend;
}
uint8_t* upload(Entry& entry, PagefileShadow& backing, uint32_t size, uint8_t value = 0xab) {
  auto* pointer = backing.acquire(size, SIZE_MAX); assert(pointer);
  std::memset(pointer, value, size); entry.uploaded(size); backing.release(SIZE_MAX); return pointer;
}
bool unmapped(const void* pointer) {
  MEMORY_BASIC_INFORMATION region {};
  return VirtualQuery(pointer, &region, sizeof(region)) && region.State == MEM_FREE;
}
int main() {
  const uint64_t baseline = l4d2_memory::surfaceBackingBytes.load();
  Policy policy;
  assert(parsePolicy("keep", policy) && policy == Policy::Keep);
  assert(parsePolicy("learned-aggressive", policy) && policy == Policy::LearnedAggressive);
  assert(parsePolicy("drop", policy) && policy == Policy::Drop);
  assert(!parsePolicy("unknown", policy));
  std::string log;
  const auto desc = descriptor(); Layout layout; assert(residencyLayout(256, 256, kDxt5, layout));
  const RECT full { 0, 0, 256, 256 };
  {
    Context c; auto backend = makeBackend(desc); configure(c, backend, log);
    PagefileShadow kept, eligible, exposed, transferring;
    Entry k(c, kept, 1, desc), e(c, eligible, 2, desc), l(c, exposed, 3, desc), t(c, transferring, 4, desc);
    k.learnedEligible = [] { return false; }; e.learnedEligible = [] { return true; };
    const auto keptPointer = upload(k, kept, layout.bytes);
    const auto eligiblePointer = upload(e, eligible, layout.bytes);
    upload(l, exposed, layout.bytes); assert(exposed.acquire(layout.bytes, SIZE_MAX));
    upload(t, transferring, layout.bytes); transferring.beginTransfer();
    assert(FAILED(exposed.evictBacking(layout.bytes)) && FAILED(transferring.evictBacking(layout.bytes)));
    const auto learned = RunPageBlockGc(c, PageBlockGcMode::Learned);
    assert(learned.pageBlocksScanned == 4 && learned.pageBlocksEvicted == 1 && learned.pageBlocksSkippedPolicy == 1);
    assert(learned.pageBlocksSkippedLocked == 1 && learned.pageBlocksSkippedTransferring == 1);
    assert(eligible.recoveryMissing() && unmapped(eligiblePointer) && kept.get() == keptPointer);
    const auto aggressive = RunPageBlockGc(c, PageBlockGcMode::Aggressive);
    assert(aggressive.pageBlocksEvicted == 1 && aggressive.bytesUnmapped >= layout.bytes);
    assert(kept.recoveryMissing() && unmapped(keptPointer));
    // Only Bridge-owned pins are drained; the exposed game pointer is never touched.
    t.drain = [&] { transferring.endTransfer(); return true; };
    const auto force = RunPageBlockGc(c, PageBlockGcMode::Force);
    assert(force.transfersDrained == 2 && force.drainWaitCount >= 1 && force.pageBlocksEvicted == 1);
    assert(force.pageBlocksSkippedLocked == 1 && exposed.get()); exposed.release(0);
  }
  {
    Context c; auto backend = makeBackend(desc); configure(c, backend, log);
    PagefileShadow backing; Entry entry(c, backing, 8, desc);
    auto* old = upload(entry, backing, layout.bytes);
    entry.becameIdle(); assert(backing.get() == old && !backing.recoveryMissing()); // KEEP is unchanged.
    c.policy = Policy::Drop;
    entry.becameIdle(); assert(backing.recoveryMissing() && unmapped(old) && c.dropEvictionCount == 1);
    // Repeated non-discard/read recovery returns current Host bytes, not the original upload/hash.
    for (uint32_t repeat = 0; repeat < 3; ++repeat) {
      backend.pixels[0] = static_cast<uint8_t>(0x30 + repeat);
      assert(entry.beforeLock(D3DLOCK_READONLY, full));
      auto* bytes = backing.acquire(layout.bytes, SIZE_MAX); assert(bytes && bytes[0] == backend.pixels[0]);
      entry.lockedSuccessfully();
      entry.becameIdle(); assert(backing.get() == bytes); // Active pointer is pinned.
      backing.release(SIZE_MAX); entry.becameIdle(); assert(backing.recoveryMissing());
    }
    assert(c.remapCountAfterDrop == 3 && c.reconstructionFailures == 0);
    backend.failed = true;
    assert(!entry.beforeLock(0, RECT { 4, 4, 8, 8 }) && backing.recoveryMissing());
    assert(c.reconstructionFailures == 1 && !backing.acquire(layout.bytes, 0));
    // Full discard skips readback even when the backend cannot lock for reading.
    assert(entry.beforeLock(D3DLOCK_DISCARD, full));
    assert(backing.acquire(layout.bytes, SIZE_MAX, true)); entry.lockedSuccessfully();
    backing.release(SIZE_MAX); entry.uploaded(layout.bytes); entry.becameIdle(); assert(backing.recoveryMissing());
  }
  {
    // SYSTEMMEM/cube-style surface identity; tight Host rows -> padded x86 client rows.
    auto smallDesc = descriptor(28, 1, 3); smallDesc.Pool = D3DPOOL_SYSTEMMEM;
    Context c; auto backend = makeBackend(smallDesc); configure(c, backend, log); c.policy = Policy::Drop;
    PagefileShadow backing; Entry entry(c, backing, 9, smallDesc);
    upload(entry, backing, 12); entry.becameIdle(); assert(backing.recoveryMissing());
    assert(entry.beforeLock(0, RECT { 0, 1, 1, 2 }));
    auto* bytes = backing.acquire(12, 0); assert(bytes);
    assert(bytes[0] == backend.pixels[0] && bytes[4] == backend.pixels[backend.pitch]
      && bytes[8] == backend.pixels[backend.pitch * 2]);
    bytes[4] = 0x66; assert(bytes[0] == backend.pixels[0] && bytes[8] == backend.pixels[backend.pitch * 2]);
    entry.lockedSuccessfully(); backing.release(0);
  }
  {
    Context c; auto backend = makeBackend(desc); configure(c, backend, log);
    PagefileShadow backing; Entry entry(c, backing, 10, desc);
    const auto pointer = upload(entry, backing, layout.bytes);
    c.referenceTest = true;
    assert(RunPageBlockGc(c, PageBlockGcMode::Force).pageBlocksSkippedPolicy == 1 && backing.get() == pointer);
    c.policy = Policy::Drop; entry.becameIdle(); assert(backing.get() == pointer);
    c.referenceTest = false; entry.uploadFailed();
    const auto result = RunPageBlockGc(c, PageBlockGcMode::Aggressive);
    assert(result.pageBlocksSkippedUnsynchronized == 1 && backing.get() == pointer);
  }
  assert(l4d2_memory::surfaceBackingBytes == baseline);
  assert(log.find("PB_GC mode=force") != std::string::npos && log.find("stage=reconstruction") != std::string::npos);
  puts("PASS: learned/aggressive/force GC; KEEP and transfer/Lock pins; real VA release; current Host readback, padded rows, repeated drop, discard and explicit recovery gaps (mock backend)");
}
