// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define NOMINMAX
#include "readback_backend.h"
#include "pagefile_shadow.h"
#include <cstdio>
#include <string>
#include <vector>

using namespace l4d2_readback;
static uint8_t pixel(size_t index) { return static_cast<uint8_t>((index * 17u + 11u) ^ (index >> 8)); }

// This test backend is explicitly not DXVK. Its source is created independently
// in the x64 child and it has no pointer/handle/name for the original PagefileShadow.
struct FakeBackend {
  Request request;
  Layout l;
  std::vector<uint8_t> source;
  uint32_t pitch = 0, mode = 0, state = 0;
  explicit FakeBackend(const Request& r, uint32_t failure = 0) : request(r), mode(failure) {
    layout(r.width, r.height, r.format, l);
    pitch = l.rowBytes + 32;
    source.assign(static_cast<size_t>(pitch) * l.rows, 0xee);
    for (uint32_t row = 0; row < l.rows; ++row) {
      for (uint32_t x = 0; x < l.rowBytes; ++x) {
        source[static_cast<size_t>(row) * pitch + x] = pixel(static_cast<size_t>(row) * l.rowBytes + x);
      }
    }
  }
  HRESULT descriptor(D3DSURFACE_DESC& desc) {
    if (state != 0) { return E_UNEXPECTED; }
    state = 1; desc = {};
    desc.Width = request.width + (mode == 5 ? 1u : 0u); desc.Height = request.height;
    desc.Format = static_cast<D3DFORMAT>(request.format); desc.Pool = D3DPOOL_MANAGED;
    return S_OK;
  }
  HRESULT synchronize(Response& response) {
    if (state != 1) { return E_UNEXPECTED; }
    state = 2; response.stage = Stage::QueryWait;
    response.flushRequested = response.eventWait = response.queryPolls = 1;
    return mode == 1 ? HRESULT_FROM_WIN32(ERROR_TIMEOUT) : S_OK;
  }
  HRESULT lock(D3DLOCKED_RECT& locked) {
    if (state != 2) { return E_UNEXPECTED; }
    state = 3;
    if (mode == 2) { return E_FAIL; }
    locked.Pitch = static_cast<INT>(mode == 3 ? l.rowBytes - 1 : pitch);
    locked.pBits = source.data(); return S_OK;
  }
  HRESULT unlock() {
    if (state != 3) { return E_UNEXPECTED; }
    state = 4; return mode == 4 ? E_FAIL : S_OK;
  }
};

static Request makeRequest(uint32_t format, uint32_t width, uint32_t height) {
  Request request;
  request.resourceId = 7; request.parentId = 6;
  request.width = width; request.height = height; request.format = format;
  Layout l; layout(width, height, format, l); request.bytes = l.bytes;
  LARGE_INTEGER nonce {}; QueryPerformanceCounter(&nonce);
  swprintf_s(request.name, L"Local\\L4D2Recovery-%lu-%llu", GetCurrentProcessId(), static_cast<unsigned long long>(nonce.QuadPart));
  return request;
}

static bool launch(const wchar_t* executable, const Request& request, uint32_t mode, PROCESS_INFORMATION& process) {
  wchar_t arguments[2048] {};
  swprintf_s(arguments, L"\"%ls\" --server \"%ls\" %u %u %u %u", executable,
    request.name, request.format, request.width, request.height, mode);
  STARTUPINFOW startup {}; startup.cb = sizeof(startup); process = {};
  return CreateProcessW(nullptr, arguments, nullptr, nullptr, FALSE, 0, nullptr, nullptr, &startup, &process) != FALSE;
}

int wmain(int argc, wchar_t** argv) {
  if (argc == 7 && std::wstring(argv[1]) == L"--server") {
    Request request;
    request.resourceId = 7; request.parentId = 6;
    wcscpy_s(request.name, argv[2]);
    request.format = static_cast<uint32_t>(wcstoul(argv[3], nullptr, 10));
    request.width = static_cast<uint32_t>(wcstoul(argv[4], nullptr, 10));
    request.height = static_cast<uint32_t>(wcstoul(argv[5], nullptr, 10));
    const uint32_t mode = static_cast<uint32_t>(wcstoul(argv[6], nullptr, 10));
    Layout l;
    if (!layout(request.width, request.height, request.format, l)) { return 10; }
    request.bytes = l.bytes;
    FakeBackend backend(request, mode);
    return runShared(backend, request, mode != 7, mode != 6) ? 0 : 11;
  }
  if (argc != 2) { return 1; }
  const auto baseline = l4d2_memory::surfaceBackingBytes.load();
  uint32_t checked = 0;
  for (const auto format : { kDxt1, kDxt3, kDxt5, 21u, 22u }) {
    for (const auto size : { 1u, 256u, 1024u, 2048u, 4096u }) {
      const Request request = makeRequest(format, size, size);
      Temporary recovered;
      if (FAILED(recovered.create(request))) { return 2; }
      PagefileShadow original;
      auto* bytes = original.acquire(request.bytes, 0);
      if (!bytes) { return 3; }
      for (size_t i = 0; i < request.bytes; ++i) { bytes[i] = pixel(i); }
      // Alter only the reference: recovery must still return the independent server bytes.
      const bool altered = size == 256;
      if (altered) { bytes[request.bytes - 1] ^= 0xff; }
      original.release(0);
      PROCESS_INFORMATION process {};
      if (!launch(argv[1], request, 0, process)) { return 4; }
      const auto wait = recovered.wait(10000);
      WaitForSingleObject(process.hProcess, 10000);
      DWORD exit = 1; GetExitCodeProcess(process.hProcess, &exit);
      CloseHandle(process.hProcess); CloseHandle(process.hThread);
      if (wait != WAIT_OBJECT_0 || exit != 0) { return 5; }
      const auto response = recovered.response();
      if (response.stage != Stage::Complete || response.hresult != S_OK || response.bytes != request.bytes
        || !response.eventWait || !response.flushRequested || response.deviceIdle) { return 6; }
      Comparison comparison;
      if (FAILED(original.compareRecovered(recovered.data(), request.bytes, comparison))) { return 7; }
      if (altered ? (comparison.mismatchBytes != 1 || comparison.firstOffset != static_cast<int64_t>(request.bytes - 1))
                  : (comparison.mismatchBytes || comparison.firstOffset != -1)) { return 8; }
      if (original.get() || l4d2_memory::surfaceBackingBytes != baseline + request.bytes) { return 9; }
      ++checked;
    }
  }
  for (uint32_t mode = 1; mode <= 7; ++mode) {
    Request request = makeRequest(kDxt5, 256, 256);
    Temporary recovered;
    if (FAILED(recovered.create(request))) { return 12; }
    PROCESS_INFORMATION process {};
    if (!launch(argv[1], request, mode, process)) { return 13; }
    const auto wait = recovered.wait(10000);
    WaitForSingleObject(process.hProcess, 10000);
    CloseHandle(process.hProcess); CloseHandle(process.hThread);
    if (wait != WAIT_OBJECT_0) { return 14; }
    const auto response = recovered.response();
    const Stage expected[] = { Stage::Pending, Stage::QueryWait, Stage::Lock, Stage::Pitch,
      Stage::Unlock, Stage::Descriptor, Stage::Resource, Stage::Disabled };
    if (response.stage != expected[mode] || SUCCEEDED(response.hresult) || response.bytes) { return 15; }
  }
  if (l4d2_memory::surfaceBackingBytes != baseline) { return 16; }
  printf("PASS: %u x86-to-x64 independent mock readbacks, reference-only corruption detection, failure stages and original backing retained\n", checked);
  return 0;
}
