// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <d3d9.h>
#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <functional>
#include <initializer_list>
#include <limits>
#include <map>
#include <memory>
#include <new>
#include <queue>
#include <sstream>
#include <stdexcept>
#include <type_traits>
#include <vector>
#include "memory_diagnostics.h"
#include "pagefile_shadow.h"
#include "texture_creation.h"

void require(bool condition, const char* message) {
  if (!condition) { throw std::runtime_error(message); }
}
#undef assert
#define assert(condition) require(!!(condition), "production assertion fired")
using UID = uint64_t;
enum class Result { Success, Timeout };
enum class Kind { VertexBuffer, IndexBuffer, RenderTarget, DepthStencilSurface,
  OffscreenPlainSurface, RenderTargetEx, OffscreenPlainSurfaceEx, DepthStencilSurfaceEx };
namespace Commands {
using Flags = unsigned;
enum FlagBits { DataInSharedHeap = 1, DataIsReserved = 2 };
enum D3D9Command { Bridge_Response, Bridge_UnlinkResource,
  IDirect3DDevice9Ex_CreateVertexBuffer, IDirect3DDevice9Ex_CreateIndexBuffer,
  IDirect3DDevice9Ex_CreateRenderTarget, IDirect3DDevice9Ex_CreateDepthStencilSurface,
  IDirect3DDevice9Ex_CreateOffscreenPlainSurface, IDirect3DDevice9Ex_CreateRenderTargetEx,
  IDirect3DDevice9Ex_CreateOffscreenPlainSurfaceEx, IDirect3DDevice9Ex_CreateDepthStencilSurfaceEx,
  IDirect3DVertexBuffer9_Destroy, IDirect3DIndexBuffer9_Destroy, IDirect3DSurface9_Destroy,
  IDirect3DVertexBuffer9_Lock, IDirect3DVertexBuffer9_Unlock,
  IDirect3DIndexBuffer9_Lock, IDirect3DIndexBuffer9_Unlock };
}
struct Message {
  Commands::D3D9Command command;
  UID resource, uid;
  Commands::Flags flags;
  std::vector<uint64_t> arguments;
  std::vector<uint8_t> bytes;
};
struct State {
  bool createResponses = true, allResponses = false, timedOut = false;
  bool shared = false, sharedDynamic = true, sharedStatic = true;
  bool optimized = false, sendWhole = false, requireNullOnRelease = false;
  HRESULT backendResult = D3D_OK, hostResponse = E_FAIL;
  unsigned waits = 0, pops = 0, live = 0, releases = 0, allocations = 0, deallocations = 0, responses = 0;
  UID lastUID = 0;
  std::function<bool()> outputIsNull;
  std::map<UID, void*> tracked;
  std::map<unsigned, std::vector<uint8_t>> sharedBuffers;
  std::vector<uint64_t> backendArguments;
  std::vector<Message> messages;
  std::vector<uint32_t> reserved;
} state;
void resetState() {
  require(!state.live && state.tracked.empty() && state.sharedBuffers.empty(), "resource or shared buffer leaked");
  for (unsigned i = 0; i < 3; ++i) {
    require(l4d2_memory::bytes[i] == 0 && l4d2_memory::objects[i] == 0, "shadow memory leaked");
  }
  state = {};
}
class GlobalOptions {
public:
  static bool getSendCreateFunctionServerResponses() { return state.createResponses; }
  static bool getSendAllServerResponses() { return state.allResponses; }
  static DWORD getAckTimeout() { return 100; }
  static bool getUseSharedHeap() { return state.shared; }
  static bool getUseSharedHeapForTextures() { return state.shared; }
  static bool getUseSharedHeapForDynamicBuffers() { return state.sharedDynamic; }
  static bool getUseSharedHeapForStaticBuffers() { return state.sharedStatic; }
  static bool getAlwaysCopyEntireStaticBuffer() { return state.sendWhole; }
};
class ClientOptions {
public:
  static bool getOptimizedDynamicLock() { return state.optimized; }
};
class SharedHeap {
public:
  using AllocId = unsigned;
  static constexpr AllocId kInvalidId = 0;
  static AllocId allocate(size_t size) {
    const auto id = ++state.allocations;
    state.sharedBuffers[id].resize(size);
    return id;
  }
  static uint8_t* getBuf(AllocId id) { return state.sharedBuffers.at(id).data(); }
  static void deallocate(AllocId id) {
    require(state.sharedBuffers.erase(id) == 1, "shared allocation released twice");
    ++state.deallocations;
  }
};
template<typename T> T align(T value, size_t alignment) {
  return (value + static_cast<T>(alignment) - 1) & ~(static_cast<T>(alignment) - 1);
}
class Logger {
public:
  template<typename T> static void err(const T&) {}
  template<typename T> static void trace(const T&) {}
};
template<typename... Args> const char* format_string(const char* message, Args...) { return message; }
class ClientMessage {
  Message m_message;
public:
  ClientMessage(Commands::D3D9Command command, UID resource, Commands::Flags flags = 0)
    : m_message{command, resource, ++state.lastUID, flags, {}, {}} {}
  ~ClientMessage() { state.messages.push_back(m_message); }
  UID get_uid() const { return m_message.uid; }
  template<typename... Args> void send_many(Args... values) {
    const std::initializer_list<uint64_t> arguments{static_cast<uint64_t>(values)...};
    m_message.arguments.insert(m_message.arguments.end(), arguments.begin(), arguments.end());
  }
  void send_data(unsigned id) { send_many(id); }
  void send_data(size_t size, const void* bytes) {
    if (size) {
      const auto* begin = static_cast<const uint8_t*>(bytes);
      m_message.bytes.assign(begin, begin + size);
    }
  }
  void* begin_data_blob(size_t size) {
    require(size <= 1024, "reserved upload exceeds bounded buffer storage");
    state.reserved.resize((size + 3) / 4);
    return state.reserved.data();
  }
  void end_data_blob() {}
};
void processHost(const Message& message);
class DeviceBridge {
public:
  static Result waitForCommand(Commands::D3D9Command command, uint32_t timeout, void*, bool matchUID, UID uid) {
    require(command == Commands::Bridge_Response && timeout == 100 && matchUID &&
      state.messages.size() == 1 && state.messages.front().uid == uid, "creation wait changed ordering or UID");
    ++state.waits;
    if (state.timedOut) { return Result::Timeout; }
    processHost(state.messages.front());
    return Result::Success;
  }
  static HRESULT get_data() { require(state.responses == 1, "response missing"); return state.hostResponse; }
  static void pop_front() { ++state.pops; }
  static DeviceBridge& getWriterChannel() { static DeviceBridge instance; return instance; }
  uint32_t* get_data_ptr() { return state.reserved.data(); }
};

// The surrounding COM/refcount storage and transport are test doubles. The
// generated Release body, wrappers, shadow allocation/destruction and methods
// are extracted verbatim from production code, apart from the Release signature.
struct TestUnknown {
  virtual ULONG AddRef() { return 1; }
  virtual ULONG Release() { return 0; }
  virtual ~TestUnknown() = default;
};
struct VertexInterface: TestUnknown {};
struct IndexInterface: TestUnknown {};
struct SurfaceInterface: TestUnknown {};
#define IUnknown TestUnknown
#define IDirect3DVertexBuffer9 VertexInterface
#define IDirect3DIndexBuffer9 IndexInterface
#define IDirect3DSurface9 SurfaceInterface
#define LPDIRECT3DVERTEXBUFFER9 VertexInterface*
#define LPDIRECT3DINDEXBUFFER9 IndexInterface*
#define LPDIRECT3DSURFACE9 SurfaceInterface*
struct D3DRefCounted { enum class Ref { Interface }; };
class BaseDirect3DDevice9Ex_LSS: public TestUnknown {
public:
  ULONG references = 1;
  ULONG AddRef() override { return ++references; }
  ULONG Release() override { return --references; }
  UID getId() const { return 77; }
};
template<typename T>
class Direct3DResource9_LSS: public T {
  ULONG m_references = 1;
protected:
  TestUnknown* m_pParent;
  virtual void onDestroy() = 0;
public:
  Direct3DResource9_LSS(T*, BaseDirect3DDevice9Ex_LSS* device): m_pParent(device) {
    ++state.live;
    m_pParent->AddRef();
  }
  ~Direct3DResource9_LSS() override {
    state.tracked.erase(getId());
    --state.live;
  }
  UID getId() const { return 0x1234; }
  bool isStandalone() const { return true; }
  template<D3DRefCounted::Ref> ULONG getRef() const { return m_references; }
  template<D3DRefCounted::Ref> ULONG decRef() {
    require(!state.requireNullOnRelease || state.outputIsNull(), "failed output was not cleared before Release");
    ++state.releases;
    const ULONG count = --m_references;
    if (!count) { onDestroy(); delete this; }
    return count;
  }
#include "resource_release.h"
};
template<typename T> T* trackWrapper(T* wrapper) {
  require(state.tracked.emplace(wrapper->getId(), wrapper).second, "wrapper tracked twice");
  return wrapper;
}
#include "resource_lockable.h"
#include "resource_wrappers.h"
template<bool EnableSync>
class Direct3DDevice9Ex_LSS: public BaseDirect3DDevice9Ex_LSS {
  bool m_ex = true;
public:
#include "resource_declarations.h"
};
#define ZoneScoped ((void)pSharedHandle)
#define LogFunctionCall() ((void)0)
#include "resource_methods.h"

class MockBackend {
public:
  template<typename T> HRESULT createBackend(std::initializer_list<uint64_t> arguments, T** output) {
    require(*output == nullptr, "Host backend output was not initialized");
    state.backendArguments = arguments;
    if (SUCCEEDED(state.backendResult)) { static T resource; *output = &resource; }
    return state.backendResult;
  }
#include "resource_backend.h"
} backend;
#define IDirect3DDevice9Ex MockBackend
std::map<uint32_t, TestUnknown*> gpD3DResources;
class ServerMessage {
public:
  ServerMessage(Commands::D3D9Command command, UID uid) {
    require(command == Commands::Bridge_Response && uid == state.messages.front().uid, "Host response UID changed");
    ++state.responses;
  }
  void send_data(HRESULT result) { state.hostResponse = result; }
};
#include "resource_server_macro.h"
#define GET_RES(name, unused) auto* name = &backend
#define PULL(type, name) const auto name = static_cast<type>(message.arguments.at(cursor++))
#define PULL_U(name) PULL(UINT, name)
#define PULL_D(name) PULL(DWORD, name)
#define PULL_HND(name) PULL(uint32_t, name)
void processHost(const Message& message) {
  using namespace Commands;
  size_t cursor = 0;
  const UID currentUID = message.uid;
  switch (message.command) {
#include "resource_host.h"
    default: throw std::runtime_error("unexpected Host command");
  }
  require(cursor == message.arguments.size(), "Host left command fields unread");
}

struct Outputs {
  VertexInterface* vertex = reinterpret_cast<VertexInterface*>(1);
  IndexInterface* index = reinterpret_cast<IndexInterface*>(1);
  SurfaceInterface* surface = reinterpret_cast<SurfaceInterface*>(1);
  TestUnknown* get(Kind kind) const {
    if (kind == Kind::VertexBuffer) { return vertex; }
    if (kind == Kind::IndexBuffer) { return index; }
    return surface;
  }
};
template<bool EnableSync>
HRESULT create(Kind kind, Direct3DDevice9Ex_LSS<EnableSync>& device, Outputs* output, UINT dimension, HANDLE* sharedHandle) {
  switch (kind) {
#include "resource_dispatch.h"
  }
  throw std::runtime_error("unknown resource kind");
}
constexpr std::array<Kind, 8> kinds{Kind::VertexBuffer, Kind::IndexBuffer, Kind::RenderTarget,
  Kind::DepthStencilSurface, Kind::OffscreenPlainSurface, Kind::RenderTargetEx,
  Kind::OffscreenPlainSurfaceEx, Kind::DepthStencilSurfaceEx};
template<bool EnableSync>
void testCreation(Kind kind, HRESULT backendResult, bool timeout, bool responses, bool allResponses, bool shared) {
  resetState();
  gpD3DResources.clear();
  state.backendResult = backendResult;
  state.timedOut = timeout;
  state.createResponses = responses;
  state.allResponses = allResponses;
  state.shared = shared;
  const bool wait = responses || allResponses;
  const HRESULT expected = wait ? (timeout ? D3DERR_INVALIDCALL : backendResult) : D3D_OK;
  Direct3DDevice9Ex_LSS<EnableSync> device;
  Outputs output;
  state.outputIsNull = [&] { return output.get(kind) == nullptr; };
  state.requireNullOnRelease = FAILED(expected);
  HANDLE sharedHandle = reinterpret_cast<HANDLE>(9);
  require(create(kind, device, &output, 64, &sharedHandle) == expected, "resource HRESULT changed");
  require(sharedHandle == reinterpret_cast<HANDLE>(9), "existing shared-handle behavior changed");
  require(state.waits == static_cast<unsigned>(wait) && state.pops == static_cast<unsigned>(wait && !timeout),
    "response consumption changed");
  require(!state.messages.empty(), "Create command missing");
  const auto message = state.messages.front();
  require(message.resource == device.getId() && message.arguments.back() == 0x1234,
    "Create command resource handles changed");
  if (wait && !timeout) {
    require(state.hostResponse == backendResult && state.responses == 1 &&
      gpD3DResources.size() == static_cast<size_t>(SUCCEEDED(backendResult)), "Host failure/success registration changed");
    auto expectedArguments = message.arguments;
    expectedArguments.pop_back();
    require(state.backendArguments == expectedArguments, "Host API arguments differ from transmitted fields");
  }
  if (FAILED(expected)) {
    require(!output.get(kind) && !state.live && state.tracked.empty() && state.releases == 1,
      "failed creation retained output, wrapper or tracked state");
  } else {
    require(output.get(kind) && state.live == 1 && state.tracked.size() == 1 && !state.releases && device.references == 2,
      "successful creation lost caller or parent ownership");
    const bool buffer = kind == Kind::VertexBuffer || kind == Kind::IndexBuffer;
    const auto shadowBytes = l4d2_memory::bytes[1].load() + l4d2_memory::bytes[2].load();
    require(shadowBytes == (buffer && !shared ? 64u : 0u), "buffer shadow allocation policy changed");
    output.get(kind)->Release();
  }
  require(device.references == 1, "resource release retained its parent device");
  const bool destroy = SUCCEEDED(expected) || timeout;
  require(state.messages.size() == (destroy ? 2u : 1u), "explicit failure or timeout Destroy handling changed");
  if (destroy) {
    const auto& last = state.messages.back();
    const auto command = kind == Kind::VertexBuffer ? Commands::IDirect3DVertexBuffer9_Destroy :
      kind == Kind::IndexBuffer ? Commands::IDirect3DIndexBuffer9_Destroy : Commands::IDirect3DSurface9_Destroy;
    require(last.command == command && last.resource == 0x1234 && last.uid > message.uid,
      "Destroy was not ordered after its Create");
  }
  resetState();
}
template<bool EnableSync> void testCreations() {
  for (const auto kind : kinds) {
    for (const bool shared : {false, true}) {
      for (const auto result : {D3D_OK, D3DERR_INVALIDCALL, D3DERR_OUTOFVIDEOMEMORY, E_OUTOFMEMORY}) {
        testCreation<EnableSync>(kind, result, false, true, false, shared);
        testCreation<EnableSync>(kind, result, false, false, true, shared);
      }
      testCreation<EnableSync>(kind, D3D_OK, true, true, false, shared);
      testCreation<EnableSync>(kind, D3DERR_OUTOFVIDEOMEMORY, false, false, false, shared);
    }
    for (unsigned i = 0; i < 50; ++i) {
      testCreation<EnableSync>(kind, D3DERR_OUTOFVIDEOMEMORY, false, true, false, false);
    }
    resetState();
    Direct3DDevice9Ex_LSS<EnableSync> device;
    require(create(kind, device, nullptr, 64, nullptr) == D3DERR_INVALIDCALL && state.messages.empty() && !state.live,
      "null output created or transmitted a resource");
    if (kind == Kind::VertexBuffer || kind == Kind::IndexBuffer || kind == Kind::RenderTarget || kind == Kind::DepthStencilSurface) {
      Outputs output;
      require(create(kind, device, &output, 0, nullptr) == D3DERR_INVALIDCALL && !output.get(kind) && state.messages.empty(),
        "zero-dimension validation did not clear its output");
    }
  }
}

template<typename Buffer, typename Desc>
void testLocks(const Desc& descriptor, bool shared, bool optimized, bool whole) {
  resetState();
  state.shared = shared;
  state.optimized = optimized;
  state.sendWhole = whole;
  BaseDirect3DDevice9Ex_LSS device;
  auto* buffer = trackWrapper(new Buffer(&device, descriptor));
  for (const UINT offset : {65u, (std::numeric_limits<UINT>::max)()}) {
    for (const UINT size : {0u, 1u, (std::numeric_limits<UINT>::max)()}) {
      void* pointer = reinterpret_cast<void*>(1);
      const auto allocations = state.allocations;
      require(buffer->lock(offset, size, &pointer, D3DLOCK_DISCARD) == D3DERR_INVALIDCALL && pointer == nullptr,
        "out-of-range offset was accepted");
      buffer->unlock();
      require(state.allocations == allocations && state.messages.empty(), "invalid lock allocated or queued a command");
    }
  }
  require(buffer->lock(0, 0, nullptr, 0) == D3DERR_INVALIDCALL, "null lock output was accepted");
  for (const UINT offset : {0u, 7u, 64u}) {
    for (const UINT requested : {0u, 5u, 128u, (std::numeric_limits<UINT>::max)()}) {
      state.messages.clear();
      void* pointer = nullptr;
      require(buffer->lock(offset, requested, &pointer, 0) == D3D_OK && pointer,
        "valid offset or tolerated oversized request was rejected");
      const size_t size = requested ? (std::min)(requested, 64u - offset) : 64u - offset;
      std::memset(pointer, 0x5a, size);
      buffer->unlock();
      require(!state.messages.empty(), "valid lock upload missing");
      const auto& upload = state.messages.back();
      const bool sendWhole = whole && (descriptor.Usage & D3DUSAGE_DYNAMIC) == 0;
      const size_t expectedSize = sendWhole ? 64 : size;
      require(upload.arguments[0] == (sendWhole ? 0u : offset) && upload.arguments[1] == expectedSize,
        "lock upload range changed");
      if (!shared && !optimized) {
        require(upload.bytes.size() == expectedSize, "shadow upload byte count changed");
        if (!sendWhole) {
          require(std::all_of(upload.bytes.begin(), upload.bytes.end(), [](uint8_t value) { return value == 0x5a; }),
            "shadow upload contents changed");
        }
      }
    }
  }
  state.messages.clear();
  void* pointer = nullptr;
  for (unsigned i = 0; i < 2; ++i) {
    require(buffer->lock(0, 8, &pointer, D3DLOCK_DISCARD) == D3D_OK, "discard lock failed");
    std::memset(pointer, 0x7b, 8);
    buffer->unlock();
  }
  state.messages.clear();
  require(buffer->lock(0, 8, &pointer, D3DLOCK_READONLY) == D3D_OK, "read-only lock failed");
  const size_t before = state.messages.size();
  buffer->unlock();
  require(state.messages.size() == before, "read-only unlock uploaded data");
  buffer->Release();
  require(device.references == 1 && state.allocations == state.deallocations, "buffer cleanup leaked references or shared storage");
  resetState();
}
template<typename Buffer, typename Desc> void testPolicy(const Desc& descriptor) {
  resetState();
  state.shared = true;
  state.sharedDynamic = false;
  state.sharedStatic = true;
  BaseDirect3DDevice9Ex_LSS device;
  // Poison the future m_desc storage so reading it before initialization chooses
  // the wrong policy deterministically, instead of relying on stack contents.
  alignas(Buffer) unsigned char storage[sizeof(Buffer)];
  std::memset(storage, 0xff, sizeof(storage));
  auto* buffer = new (static_cast<void*>(storage)) Buffer(&device, descriptor);
  require(l4d2_memory::bytes[1] == 0 && l4d2_memory::bytes[2] == 0,
    "shared policy read an uninitialized resource descriptor");
  void* pointer = nullptr;
  require(buffer->lock(65, 0, &pointer, 0) == D3DERR_INVALIDCALL && !state.allocations && state.messages.empty(),
    "shared policy invalid offset touched transport or allocations");
  buffer->~Buffer();
  device.Release();
  resetState();
}
int main() {
  try {
    testCreations<false>();
    testCreations<true>();
    for (const DWORD usage : {DWORD(0), DWORD(D3DUSAGE_DYNAMIC)}) {
      const D3DVERTEXBUFFER_DESC vertex{D3DFMT_VERTEXDATA, D3DRTYPE_VERTEXBUFFER, usage, D3DPOOL_DEFAULT, 64, 0};
      const D3DINDEXBUFFER_DESC index{D3DFMT_INDEX16, D3DRTYPE_INDEXBUFFER, usage, D3DPOOL_DEFAULT, 64};
      for (const bool shared : {false, true}) {
        testLocks<Direct3DVertexBuffer9_LSS>(vertex, shared, false, false);
        testLocks<Direct3DIndexBuffer9_LSS>(index, shared, false, false);
      }
      if (usage) {
        testLocks<Direct3DVertexBuffer9_LSS>(vertex, false, true, false);
        testLocks<Direct3DIndexBuffer9_LSS>(index, false, true, false);
      } else {
        testLocks<Direct3DVertexBuffer9_LSS>(vertex, false, false, true);
        testLocks<Direct3DIndexBuffer9_LSS>(index, false, false, true);
        testPolicy<Direct3DVertexBuffer9_LSS>(vertex);
        testPolicy<Direct3DIndexBuffer9_LSS>(index);
      }
    }
    std::puts("PASS: actual resource Create/Release/destruction, shadow ownership, Host responses and buffer locks; failure/timeout/async, shared policies and offset/oversized boundaries.");
    return 0;
  } catch (const std::exception& error) {
    std::fprintf(stderr, "%s\n", error.what());
    return 1;
  }
}
