// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Production upload/unlock, lock storage and format helpers are extracted at build time.
// Transport and shadow release are mocked; this does not measure game or GPU performance.
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3d9.h>
#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>
#include <queue>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>
#include "upload_observers.h"

void require(bool value, const char* message) { if (!value) throw std::runtime_error(message); }
struct Logger { static void err(const std::string&) {} };
#pragma warning(push)
#pragma warning(disable: 4505) // Other static format helpers are unused in this isolated harness.
#pragma warning(disable: 4063) // Legal FourCC extensions are outside the SDK D3DFORMAT enum.
#pragma warning(disable: 4702) // Upstream format helper retains a fallback return after throw.
#include "surface_format.h"
#pragma warning(pop)
#include "ati_texture_layout.h"

bool benchmarkEnabled = false;
LARGE_INTEGER copyStart {};
LONGLONG copyTicks = 0;
size_t copyCalls = 0;
namespace Commands {
constexpr uint32_t IDirect3DSurface9_UnlockRect = 23;
namespace FlagBits { constexpr uint32_t DataInSharedHeap = 4; }
}
namespace SharedHeap {
using AllocId = uint32_t;
constexpr AllocId kInvalidId = 0xffffffffu;
std::vector<AllocId> freed;
void deallocate(AllocId id) { freed.push_back(id); }
}
struct Capture {
  uint32_t commands = 0, dataFlag = 0, begins = 0, ends = 0;
  RECT rect {};
  bool rectSent = false, refuseBlob = false;
  size_t requestedBytes = 0;
  std::vector<uint64_t> fields;
  std::vector<uint8_t> storage;
  static constexpr size_t guard = 32;
} capture;
struct ClientMessage {
  uint32_t get_uid() const { return 123; }
  ClientMessage(uint32_t command, uint32_t id, uint32_t flag) {
    require(command == Commands::IDirect3DSurface9_UnlockRect && id == 7, "command or resource id changed");
    ++capture.commands; capture.dataFlag = flag;
  }
  void send_data(size_t bytes, const void* data) {
    require(!capture.rectSent && bytes == sizeof(RECT), "rectangle wire header changed");
    std::memcpy(&capture.rect, data, bytes); capture.rectSent = true;
  }
  template<class T> void send_data(T value) { capture.fields.push_back(static_cast<uint64_t>(value)); }
  uint8_t* begin_data_blob(size_t size) {
    ++capture.begins; capture.requestedBytes = size;
    if (capture.refuseBlob) { return nullptr; }
    require(size < 128u * 1024u * 1024u, "test tried to allocate an oversized payload");
    capture.storage.resize(size + 2 * Capture::guard, 0xcd);
    if (benchmarkEnabled) { QueryPerformanceCounter(&copyStart); }
    return capture.storage.data() + Capture::guard;
  }
  void end_data_blob() {
    if (benchmarkEnabled) {
      LARGE_INTEGER end {}; QueryPerformanceCounter(&end);
      copyTicks += end.QuadPart - copyStart.QuadPart;
    }
    ++capture.ends;
  }
};
size_t surfaceShadowBudget() { return 128u * 1024u * 1024u; }
struct PagefileShadow {
  unsigned releases = 0;
  unsigned transfers = 0;
  unsigned observations = 0;
  struct Transfer {
    PagefileShadow& shadow;
    explicit Transfer(PagefileShadow& value) : shadow(value) { ++shadow.transfers; }
    ~Transfer() { --shadow.transfers; }
  };
  void release(size_t budget) {
    require(budget == surfaceShadowBudget(), "shadow budget changed"); ++releases;
  }
  void observeUnlock(DWORD) { ++observations; }
};
namespace l4d2_readback {
using Digest = std::vector<uint8_t>;
struct Hasher {
  Digest bytes;
  void add(const void* data, size_t size) {
    const auto* first = static_cast<const uint8_t*>(data);
    bytes.insert(bytes.end(), first, first + size);
  }
  HRESULT finish(Digest& output) { output = bytes; return S_OK; }
};
bool enabled() { return false; }
void test(uint32_t, uint32_t, const D3DSURFACE_DESC&, PagefileShadow&) {}
}
namespace l4d2_residency {
struct Context { std::recursive_mutex mutex; };
Context& context() { static Context value; return value; }
struct Entry {
  unsigned idle = 0, attempts = 0, uploads = 0;
  void becameIdle() { ++idle; }
  void uploadFailed() { ++attempts; }
  void uploaded(size_t, bool) { ++uploads; }
};
}
namespace l4d2_retention {
struct Parent {
  l4d2_readback::Digest lastUpload;
  HRESULT result = E_FAIL;
  bool hashUpload(uint32_t, bool) { return true; }
  void uploaded(uint32_t, bool, const l4d2_readback::Digest& digest, HRESULT value) {
    lastUpload = digest; result = value;
  }
};
}
bool retentionEnabled = false;
class Direct3DSurface9_LSS {
#include "surface_lock_storage.h"
  D3DSURFACE_DESC m_desc {};
  bool m_bUseSharedHeap;
  uint32_t m_readbackParentId = 0, m_readbackMip = 0;
  bool m_readbackTexture2D = false, m_readbackAttempted = false;
  l4d2_readback::Digest m_uploadHash;
  HRESULT m_uploadHashResult = E_FAIL;
  void sendDataToServer(const LockInfo&);
  static std::tuple<size_t, size_t> getRectDimensions(const RECT&);
public:
  PagefileShadow m_shadow;
  std::unique_ptr<l4d2_residency::Entry> m_residency;
  std::shared_ptr<l4d2_retention::Parent> m_retention;
  Direct3DSurface9_LSS(D3DFORMAT format, UINT width, UINT height, bool shared = false)
    : m_bUseSharedHeap(shared), m_residency(std::make_unique<l4d2_residency::Entry>()) {
    m_desc.Format = format; m_desc.Width = width; m_desc.Height = height;
    if (retentionEnabled) { m_retention = std::make_shared<l4d2_retention::Parent>(); }
  }
  uint32_t getId() const { return 7; }
  void queue(const RECT& rect, INT pitch, void* data, DWORD flags = 0,
             SharedHeap::AllocId discard = SharedHeap::kInvalidId) {
    m_lockInfoQueue.push({{pitch, data}, rect, flags, 123, discard});
  }
  void unlock();
};
#ifndef SURFACE_COPY_BENCHMARK
void* countedCopy(void* target, const void* source, size_t bytes) {
  ++copyCalls; return std::memcpy(target, source, bytes);
}
#define memcpy countedCopy
#endif
#pragma warning(push)
#pragma warning(disable: 4244 4267) // Existing production size_t dimensions call uint32_t format helpers.
#include "surface_methods.h"
#pragma warning(pop)
#ifndef SURFACE_COPY_BENCHMARK
#undef memcpy
#endif

void checkPayload(const std::vector<uint8_t>& expected) {
  require(capture.requestedBytes == expected.size() && capture.ends == 1, "payload extent or completion changed");
  require(std::equal(expected.begin(), expected.end(), capture.storage.begin() + Capture::guard), "upload payload differs from row reference");
  require(std::all_of(capture.storage.begin(), capture.storage.begin() + Capture::guard,
    [](uint8_t byte) { return byte == 0xcd; }), "payload prefix guard overwritten");
  require(std::all_of(capture.storage.end() - Capture::guard, capture.storage.end(),
    [](uint8_t byte) { return byte == 0xcd; }), "payload suffix guard overwritten");
}
void runCase(D3DFORMAT format, UINT width, UINT height, RECT rect, uint32_t padding,
             DWORD flags = 0, bool shared = false, bool refuse = false) {
  const bool ati = l4d2_ati::isFormat(format);
  const bool compressed = ati || format == D3DFMT_DXT1 || format == D3DFMT_DXT5;
  const uint32_t block = compressed ? 4u : 1u;
  const uint32_t pixel = format == D3DFMT_DXT1 || format == static_cast<D3DFORMAT>(l4d2_ati::kAti1) ? 8u
    : compressed ? 16u : format == D3DFMT_A8 ? 1u : 4u;
  const auto regionWidth = static_cast<uint32_t>(rect.right - rect.left);
  const auto regionHeight = static_cast<uint32_t>(rect.bottom - rect.top);
  const uint32_t rows = (regionHeight + block - 1) / block;
  const auto rowBytes = (std::max)(ati ? 0u : static_cast<uint32_t>(sizeof(size_t)), ((regionWidth + block - 1) / block) * pixel);
  const auto pitch = (std::max)(ati ? 0u : static_cast<uint32_t>(sizeof(size_t)), ((width + block - 1) / block) * pixel) + padding;
  const uint32_t apiPitch = ati ? (width + 3u) & ~3u : pitch;
  const size_t offset = ati ? static_cast<size_t>(rect.top) * apiPitch + rect.left
    : static_cast<size_t>((rect.top + block - 1) / block) * pitch + ((rect.left + block - 1) / block) * pixel;
  const size_t backingBytes = static_cast<size_t>((height + block - 1) / block) * pitch;
  std::vector<uint8_t> source(backingBytes + 64, 0xa7), expected(static_cast<size_t>(rowBytes) * rows);
  for (uint32_t row = 0; row < rows; ++row) for (uint32_t byte = 0; byte < rowBytes; ++byte) {
    const auto value = static_cast<uint8_t>((row * 41u + byte * 13u + row / 7u) & 255u);
    source[32 + offset + static_cast<size_t>(row) * pitch + byte] = value;
    expected[static_cast<size_t>(row) * rowBytes + byte] = value;
  }
  const auto preserved = source;
  Direct3DSurface9_LSS surface(format, width, height, shared);
  capture = {}; capture.refuseBlob = refuse; SharedHeap::freed.clear(); copyCalls = 0;
  l4d2_color::lastUpload.clear();
  surface.queue(rect, static_cast<INT>(apiPitch), source.data() + 32 + offset, flags, 456);
  surface.unlock(); surface.unlock();
  require(source == preserved, "upload changed source, padding or guards");
  require(surface.m_shadow.releases == (shared ? 0u : 1u), "shadow release count changed");
  require(surface.m_shadow.transfers == 0 && surface.m_shadow.observations == (shared ? 0u : 1u),
    "upload transfer lifetime or unlock observation changed");
  if (flags & D3DLOCK_READONLY) {
    require(capture.commands == 0 && SharedHeap::freed.empty(), "readonly lock sent data or changed shared ownership"); return;
  }
  require(capture.commands == 1 && capture.rectSent && std::memcmp(&capture.rect, &rect, sizeof(rect)) == 0, "wire rectangle changed or duplicate unlock sent data");
  require(capture.dataFlag == (shared ? Commands::FlagBits::DataInSharedHeap : 0), "shared data flag changed");
  const std::vector<uint64_t> fields = shared
    ? std::vector<uint64_t>{flags, static_cast<uint64_t>(format), pitch, 123}
    : std::vector<uint64_t>{flags, static_cast<uint64_t>(format), rowBytes};
  require(capture.fields == fields, "wire flags, format, pitch or buffer id changed");
  if (shared) {
    require(capture.begins == 0 && SharedHeap::freed == std::vector<SharedHeap::AllocId>{456}, "shared upload copied data or lost discarded buffer"); return;
  }
  require(SharedHeap::freed.empty() && capture.begins == 1, "unexpected shared release or blob count");
  if (refuse) { require(capture.ends == 0 && copyCalls == 0, "failed reservation still copied or completed"); return; }
  checkPayload(expected);
  require(surface.m_residency->attempts == 1 && surface.m_residency->uploads == 1 && surface.m_residency->idle == 1,
    "surface upload skipped residency notifications");
  if (!ati && retentionEnabled) {
    require(surface.m_retention->result == S_OK && surface.m_retention->lastUpload == expected,
      "retention hash missed upload bytes");
  }
  if (!ati && l4d2_color::enabled.load() && (width <= 4 || height <= 4)) {
    require(l4d2_color::lastUpload == expected, "enabled surface diagnostics missed upload bytes");
  }
#ifndef SURFACE_COPY_BENCHMARK
  if (!ati) {
    const bool complete = rect.left == 0 && rect.top == 0 && regionWidth == width && regionHeight == height;
#ifdef SURFACE_ROW_REFERENCE
    (void)complete; const size_t expectedCopies = rows;
#else
    const bool colorSample = l4d2_color::enabled.load() && (width <= 4 || height <= 4);
    const size_t expectedCopies = complete && pitch == rowBytes && !retentionEnabled && !colorSample ? 1u : rows;
#endif
    require(copyCalls == expectedCopies, "copy path did not preserve the whole-surface eligibility rule");
  }
#endif
}

void testSizeBoundaries() {
  // Reserve failure preserves the existing wire-size behavior without allocating
  // multi-gigabyte storage. This optimization deliberately does not redefine it.
  for (const auto dimensions : {std::array<UINT, 2>{16384, 16384}, {32768, 32768}, {32768, 32769}}) {
    Direct3DSurface9_LSS surface(D3DFMT_A8R8G8B8, dimensions[0], dimensions[1]);
    RECT rect {0, 0, static_cast<LONG>(dimensions[0]), static_cast<LONG>(dimensions[1])};
    capture = {}; capture.refuseBlob = true; copyCalls = 0;
    surface.queue(rect, static_cast<INT>(dimensions[0] * 4u), nullptr);
    surface.unlock();
    const uint32_t originalSize = (dimensions[0] * 4u) * dimensions[1];
    require(capture.requestedBytes == originalSize && capture.ends == 0 && copyCalls == 0,
      "large reservation behavior changed or null blob was copied");
  }
}

void runBenchmark(const char* variant, const char* round) {
  struct Case { UINT width, height, iterations; D3DFORMAT format; };
  LARGE_INTEGER frequency {}; require(QueryPerformanceFrequency(&frequency) != FALSE, "clock unavailable");
  for (const auto item : {Case{64, 64, 2048, D3DFMT_A8R8G8B8}, Case{256, 256, 256, D3DFMT_A8R8G8B8},
                         Case{1024, 1024, 32, D3DFMT_A8R8G8B8}, Case{256, 256, 1024, D3DFMT_DXT1},
                         Case{1024, 1024, 128, D3DFMT_DXT5}}) {
    const size_t bytes = bridge_util::calcTotalSizeOfRect(item.width, item.height, item.format);
    std::vector<uint8_t> source(bytes);
    for (size_t i = 0; i < bytes; ++i) source[i] = static_cast<uint8_t>((i * 13u + i / 4096u) & 255u);
    Direct3DSurface9_LSS surface(item.format, item.width, item.height);
    const RECT rect {0, 0, static_cast<LONG>(item.width), static_cast<LONG>(item.height)};
    capture = {}; capture.storage.resize(bytes + 2 * Capture::guard, 0xcd); copyTicks = 0;
    for (UINT iteration = 0; iteration < item.iterations + 16; ++iteration) {
      source[(static_cast<size_t>(iteration) * 997u) % bytes] ^= static_cast<uint8_t>(iteration + 1);
      capture.fields.clear(); capture.rectSent = false; capture.ends = 0;
      surface.queue(rect, static_cast<INT>(bridge_util::calcRowSize(item.width, item.format)), source.data());
      benchmarkEnabled = iteration >= 16;
      surface.unlock();
      benchmarkEnabled = false;
      checkPayload(source);
    }
    const double microseconds = static_cast<double>(copyTicks) * 1000000.0 / static_cast<double>(frequency.QuadPart);
    std::printf("surface-copy variant=%s round=%s format=%u width=%u height=%u bytes=%zu iterations=%u copy_total_us=%.3f copy_us_per_iteration=%.3f\n",
      variant, round, static_cast<unsigned>(item.format), item.width, item.height, bytes, item.iterations,
      microseconds, microseconds / item.iterations);
  }
  std::puts("Copy-only CPU microbenchmark; allocation, IPC, GPU work and game FPS are not measured.");
}
int main(int argc, char** argv) {
  try {
    if (argc == 4 && std::strcmp(argv[1], "--benchmark") == 0) { runBenchmark(argv[2], argv[3]); return 0; }
    for (auto format : {D3DFMT_A8R8G8B8, D3DFMT_A8, D3DFMT_DXT1, D3DFMT_DXT5}) {
      runCase(format, 32, 16, {0, 0, 32, 16}, 0);
      runCase(format, 32, 16, {0, 0, 32, 16}, 13); // Full surface with padding must still copy rows.
      runCase(format, 32, 16, {4, 4, 20, 12}, 0); // Offset subrect within full backing pitch.
      runCase(format, 32, 16, {0, 4, 32, 12}, 0); // Contiguous but partial: preserve row fallback.
      runCase(format, 7, 5, {0, 0, 7, 5}, 0); // Odd dimensions and compressed block rounding.
      runCase(format, 1, 1, {0, 0, 1, 1}, 0); // Minimum architecture-dependent pitch.
      runCase(format, 32, 16, {0, 0, 32, 16}, 0, D3DLOCK_READONLY);
      runCase(format, 32, 16, {0, 0, 32, 16}, 0, D3DLOCK_DISCARD, true);
      runCase(format, 32, 16, {0, 0, 32, 16}, 0, 0, false, true);
    }
    for (auto format : {static_cast<D3DFORMAT>(l4d2_ati::kAti1), static_cast<D3DFORMAT>(l4d2_ati::kAti2)}) {
      runCase(format, 32, 16, {0, 0, 32, 16}, 0);
      runCase(format, 32, 16, {4, 0, 20, 8}, 0);
      runCase(format, 1, 1, {0, 0, 1, 1}, 0);
      runCase(format, 32, 16, {0, 0, 32, 16}, 0, D3DLOCK_READONLY);
      runCase(format, 32, 16, {0, 0, 32, 16}, 0, D3DLOCK_DISCARD, true);
    }
    // The fast path must preserve real retention hashing and diagnostic digests.
    for (bool diagnostics : {false, true}) for (bool retention : {false, true}) {
      l4d2_color::enabled.store(diagnostics); retentionEnabled = retention;
      runCase(D3DFMT_A8R8G8B8, 4, 4, {0, 0, 4, 4}, 0);
      runCase(D3DFMT_A8R8G8B8, 32, 16, {0, 0, 32, 16}, 0);
      runCase(D3DFMT_DXT5, 8, 8, {0, 0, 8, 8}, 0);
    }
    l4d2_color::enabled.store(false); retentionEnabled = false;
    testSizeBoundaries();
    std::puts("PASS: production surface upload/unlock; full, padded, offset, compressed and tiny layouts; ATI, readonly, shared heap, wire fields, payload guards and failed reservations");
    return 0;
  } catch (const std::exception& error) { std::fprintf(stderr, "%s\n", error.what()); return 1; }
}
