# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
import importlib.util
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location("color_analysis", Path(__file__).resolve().parents[1] / "scripts/analyze_color_diagnostics.py")
analysis = importlib.util.module_from_spec(spec)
spec.loader.exec_module(analysis)


class ColorAnalysis(unittest.TestCase):
    def test_matching_and_disagreeing_wire_requests(self):
        with tempfile.TemporaryDirectory() as directory:
            client, host = Path(directory) / "client.log", Path(directory) / "host.log"
            fields = "uid=10 resource_id=20 device_id=2 width=1 height=1 depth=1 levels=1 usage=0 format=0x35545844 pool=1"
            client.write_text("event=CONFIG build=same\nevent=CREATE_TEXTURE_SERIALIZED " + fields + "\nevent=END\n")
            host.write_text("event=CONFIG build=same\nevent=CREATE_TEXTURE_ORIGINAL " + fields + "\nevent=END\n")
            result = analysis.analyze(client, host)
            self.assertTrue(result["builds_match"])
            self.assertEqual(result["matched_texture_requests"], 1)
            self.assertEqual(result["texture_parameter_mismatch_examples"], [])
            host.write_text(host.read_text().replace("width=1", "width=4"))
            self.assertEqual(analysis.analyze(client, host)["texture_parameter_mismatch_examples"][0]["fields"], ["width"])

    def test_volume_pitch_and_payload_difference_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            client, host = Path(directory) / "client.log", Path(directory) / "host.log"
            client.write_text("event=CLIENT_VOLUME_LOCK reported_row_pitch=32 reported_slice_pitch=32 expected_row_bytes=128 expected_slice_bytes=4096\n"
                              "event=UPLOAD uid=17 resource_id=21 payload_bytes=16 hashed_bytes=16 content_hash=0xaaaa\n")
            host.write_text("event=UPLOAD uid=17 resource_id=21 payload_bytes=16 hashed_bytes=16 content_hash=0xbbbb\n")
            result = analysis.analyze(client, host)
            self.assertEqual(len(result["client_volume_pitch_error_examples"]), 1)
            self.assertEqual(result["sampled_upload_payload_difference_examples"][0]["fields"], ["content_hash"])
            self.assertFalse(result["normal_end_present"]["host"])


if __name__ == "__main__":
    unittest.main()
