# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
import importlib.util
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location("api_analysis", Path(__file__).resolve().parents[1] / "scripts/analyze_api_wait.py")
analysis = importlib.util.module_from_spec(spec)
spec.loader.exec_module(analysis)


def snapshot(sequence, tick, calls, total, maximum, complete=True):
    return (
        f"L4D2_API_WAIT_SUMMARY snapshot={sequence} role=client pid=7 tick_ms={tick} frequency=1000000 commands={calls} dropped_threads=0\n"
        f"L4D2_API_WAIT_THREAD snapshot={sequence} tid=11 inflight=0\n"
        f"L4D2_API_WAIT snapshot={sequence} tid=11 api=CreateTexture metric=api calls={calls} total_us={total} inclusive_us={total} max_us={maximum} ge_1ms=0 ge_5ms=0 ge_10ms=0 ge_50ms=0 ge_100ms=0\n"
        + (f"L4D2_API_WAIT_END snapshot={sequence}\n" if complete else "")
    )


class AnalysisTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.log = Path(self.directory.name) / "client.log"
        self.log.write_text(snapshot(1, 1000, 10, 200, 100) + snapshot(2, 2000, 12, 500, 250) + snapshot(3, 3000, 20, 1500, 500, False))

    def test_delta_ignores_truncated_snapshot_and_keeps_lifetime_max(self):
        result = analysis.report(self.log)
        self.assertEqual(result["end_snapshot"], 2)
        self.assertEqual(result["snapshot_wall_ms"], 1000)
        self.assertEqual(result["rows"][0]["calls"], 2)
        self.assertEqual(result["rows"][0]["total_us"], 300)
        self.assertEqual(result["rows"][0]["lifetime_max_us_at_end"], 250)
        self.assertEqual(result["direct_wait_path_total_us"], 0)

    def test_new_upload_phases_remain_separate_from_direct_waits(self):
        text = self.log.read_text().replace("metric=api", "metric=payload_copy_hash")
        self.log.write_text(text)
        result = analysis.report(self.log)
        self.assertEqual(result["metric_totals_us"]["payload_copy_hash"], 300)
        self.assertEqual(result["direct_wait_path_total_us"], 0)

    def test_outside_or_identical_boundaries_rejected(self):
        with self.assertRaises(ValueError):
            analysis.report(self.log, 0, 2000)
        with self.assertRaises(ValueError):
            analysis.report(self.log, 1001, 1200)

    def test_negative_counter_delta_rejected(self):
        self.log.write_text(snapshot(1, 1000, 10, 200, 100) + snapshot(2, 2000, 1, 20, 20))
        with self.assertRaises(ValueError):
            analysis.report(self.log)

    def test_missing_complete_interval_rejected(self):
        self.log.write_text(snapshot(1, 1000, 10, 200, 100) + snapshot(2, 2000, 12, 500, 250, False))
        with self.assertRaises(ValueError):
            analysis.report(self.log)

    def test_boundary_errors_are_explicit(self):
        result = analysis.report(self.log, 1100, 1900, thread=11)
        self.assertEqual(result["begin_boundary_error_ms"], -100)
        self.assertEqual(result["end_boundary_error_ms"], 100)
        self.assertEqual(result["per_thread_totals_us"]["11"]["api"], 300)


if __name__ == "__main__":
    unittest.main()
