// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <d3d9.h>
#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <initializer_list>
#include <stdexcept>
#include <vector>
#include "texture_creation.h"
#include "upload_observers.h"
#ifdef _MSC_VER
#include <intrin.h>
#else
#define _ReturnAddress() __builtin_return_address(0)
#endif

void require(bool condition, const char* message) {
  if (!condition) { throw std::runtime_error(message); }
}

using UID = uint64_t;
enum class Result { Success, Timeout };
namespace Commands {
enum Command {
  Bridge_Response,
  IDirect3DDevice9Ex_CreateVolumeTexture,
  IDirect3DDevice9Ex_CreateCubeTexture,
  IDirect3DVolumeTexture9_Destroy,
  IDirect3DCubeTexture9_Destroy
};
}
struct TEXTURE_DESC {
  UINT Width, Height, Depth, Levels;
  DWORD Usage;
  D3DFORMAT Format;
  D3DPOOL Pool;
};
struct Message {
  Commands::Command command;
  UID resource;
  UID uid;
  std::vector<uint64_t> arguments;
};
struct State {
  bool createResponses = true;
  bool allResponses = false;
  bool timedOut = false;
  HRESULT response = D3D_OK;
  unsigned waits = 0, pops = 0, live = 0, releases = 0, tracked = 0;
  UID lastUID = 0;
  std::function<bool()> outputIsNull;
  bool requireNullOnRelease = false;
  TEXTURE_DESC descriptor{};
  std::vector<Message> messages;
} state;

class GlobalOptions {
public:
  static bool getSendCreateFunctionServerResponses() { return state.createResponses; }
  static bool getSendAllServerResponses() { return state.allResponses; }
  static DWORD getAckTimeout() { return 100; }
};
class DeviceBridge {
public:
  static Result waitForCommand(Commands::Command command, uint32_t timeout, void*, bool matchUID, UID uid) {
    require(command == Commands::Bridge_Response && timeout == 100 && matchUID,
      "response wait options changed");
    require(state.messages.size() == 1 && state.messages.front().uid == uid,
      "creation was not sent before waiting for its matching response");
    ++state.waits;
    return state.timedOut ? Result::Timeout : Result::Success;
  }
  static HRESULT get_data() {
    require(state.waits == 1 && !state.timedOut, "response read without a successful wait");
    return state.response;
  }
  static void pop_front() { ++state.pops; }
};
class ClientMessage {
  Message m_message;
public:
  ClientMessage(Commands::Command command, UID resource)
    : m_message{command, resource, ++state.lastUID, {}} {}
  ~ClientMessage() { state.messages.push_back(m_message); }
  UID get_uid() const { return m_message.uid; }
  template<typename... Args>
  void send_many(Args... values) { m_message.arguments = {static_cast<uint64_t>(values)...}; }
};
class Logger {
public:
  static void err(const char*) {}
};
template<typename... Args>
const char* format_string(const char* message, Args...) { return message; }

// Replace only the COM object shell; the generated creation, cancellation,
// destruction and response-wait code comes from the actual patched sources.
struct VolumeInterface { virtual ULONG Release() = 0; virtual ~VolumeInterface() = default; };
struct CubeInterface { virtual ULONG Release() = 0; virtual ~CubeInterface() = default; };
#define IDirect3DVolumeTexture9 VolumeInterface
#define IDirect3DCubeTexture9 CubeInterface
template<typename Interface>
class MockTexture: public Interface {
protected:
  virtual void onDestroy() = 0;
public:
  template<typename Device>
  MockTexture(Device*, const TEXTURE_DESC& desc) {
    ++state.live;
    state.descriptor = desc;
  }
  ~MockTexture() override { --state.live; }
  UID getId() const { return 0x1234; }
  ULONG Release() override {
    require(!state.requireNullOnRelease || state.outputIsNull(),
      "failed output must be null before releasing its wrapper");
    ++state.releases;
    onDestroy();
    delete this;
    return 0;
  }
};
template<typename Texture>
Texture* trackWrapper(Texture* texture) { ++state.tracked; return texture; }
#include "texture_creation_wrappers.h"

template<typename... Args>
UINT CalculateNumMipLevels(Args... dimensions) {
  UINT maximum = (std::max)({static_cast<UINT>(dimensions)...});
  UINT levels = 0;
  do { ++levels; maximum >>= 1; } while (maximum);
  return levels;
}
template<bool EnableSync>
class Direct3DDevice9Ex_LSS {
public:
  UID getId() const { return 77; }
  HRESULT CreateVolumeTexture(UINT, UINT, UINT, UINT, DWORD, D3DFORMAT, D3DPOOL, IDirect3DVolumeTexture9**, HANDLE*);
  HRESULT CreateCubeTexture(UINT, UINT, DWORD, D3DFORMAT, D3DPOOL, IDirect3DCubeTexture9**, HANDLE*);
};
#define ZoneScoped ((void)pSharedHandle)
#define LogFunctionCall() ((void)0)
#include "texture_creation_methods.h"

template<bool Volume, bool EnableSync>
void exercise(HRESULT backendResult, bool timedOut, bool createResponses, bool allResponses, UINT levels) {
  require(!state.live, "previous wrapper leaked");
  state = {};
  state.response = backendResult;
  state.timedOut = timedOut;
  state.createResponses = createResponses;
  state.allResponses = allResponses;
  const bool wait = createResponses || allResponses;
  const HRESULT expected = wait ? (timedOut ? D3DERR_INVALIDCALL : backendResult) : D3D_OK;
  state.requireNullOnRelease = FAILED(expected);
  Direct3DDevice9Ex_LSS<EnableSync> device;
  VolumeInterface* volume = nullptr;
  CubeInterface* cube = nullptr;
  state.outputIsNull = [&] { return Volume ? volume == nullptr : cube == nullptr; };
  HRESULT actual;
  if constexpr (Volume) {
    actual = device.CreateVolumeTexture(16, 8, 4, levels, D3DUSAGE_DYNAMIC,
      D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, &volume, nullptr);
  } else {
    actual = device.CreateCubeTexture(16, levels, D3DUSAGE_DYNAMIC,
      D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, &cube, nullptr);
  }
  require(actual == expected, "creation HRESULT changed");
  require(state.waits == static_cast<unsigned>(wait) &&
    state.pops == static_cast<unsigned>(wait && !timedOut), "response consumption changed");
  require(state.tracked == 1 && !state.messages.empty(), "wrapper or create command missing");
  const auto create = state.messages.front();
  const UINT expectedLevels = levels ? levels : 5;
  const auto& descriptor = state.descriptor;
  require(descriptor.Width == 16 && descriptor.Height == (Volume ? 8u : 16u) &&
    descriptor.Depth == (Volume ? 4u : 6u) && descriptor.Levels == expectedLevels &&
    descriptor.Usage == D3DUSAGE_DYNAMIC && descriptor.Format == D3DFMT_A8R8G8B8 &&
    descriptor.Pool == D3DPOOL_DEFAULT, "texture descriptor changed");
  const std::vector<uint64_t> expectedArguments = Volume ?
    std::vector<uint64_t>{16, 8, 4, expectedLevels, D3DUSAGE_DYNAMIC, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, 0x1234} :
    std::vector<uint64_t>{16, expectedLevels, D3DUSAGE_DYNAMIC, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, 0x1234};
  require(create.command == (Volume ? Commands::IDirect3DDevice9Ex_CreateVolumeTexture :
    Commands::IDirect3DDevice9Ex_CreateCubeTexture) && create.resource == 77 &&
    create.arguments == expectedArguments, "creation command arguments changed");
  if (FAILED(expected)) {
    require(state.outputIsNull() && state.live == 0 && state.releases == 1,
      "failed creation retained its output or wrapper");
  } else {
    require(!state.outputIsNull() && state.live == 1 && state.releases == 0 && state.messages.size() == 1,
      "successful creation lost caller ownership");
    if constexpr (Volume) { volume->Release(); } else { cube->Release(); }
    require(state.live == 0 && state.releases == 1, "successful wrapper cleanup changed");
  }
  const bool destroy = SUCCEEDED(expected) || timedOut;
  require(state.messages.size() == (destroy ? 2u : 1u),
    "explicit failure sent Destroy, or unresolved/successful creation omitted it");
  if (destroy) {
    const auto& destruction = state.messages.back();
    require(destruction.command == (Volume ? Commands::IDirect3DVolumeTexture9_Destroy :
      Commands::IDirect3DCubeTexture9_Destroy) && destruction.resource == 0x1234 &&
      destruction.uid > create.uid, "Destroy was not ordered after Create for the same resource");
  }
}

template<bool Volume, bool EnableSync>
void runCases() {
  for (const UINT levels : {0u, 3u}) {
    for (const auto error : {D3DERR_INVALIDCALL, D3DERR_OUTOFVIDEOMEMORY, E_OUTOFMEMORY}) {
      exercise<Volume, EnableSync>(error, false, true, false, levels);
      exercise<Volume, EnableSync>(error, false, false, true, levels);
    }
    exercise<Volume, EnableSync>(D3D_OK, true, true, false, levels);
    exercise<Volume, EnableSync>(D3D_OK, true, false, true, levels);
    exercise<Volume, EnableSync>(D3D_OK, false, true, false, levels);
    exercise<Volume, EnableSync>(D3D_OK, false, false, true, levels);
    // Disabled responses preserve asynchronous ownership even if the fake backend fails.
    exercise<Volume, EnableSync>(D3DERR_OUTOFVIDEOMEMORY, false, false, false, levels);
  }
  for (unsigned i = 0; i < 1000; ++i) {
    exercise<Volume, EnableSync>(D3DERR_OUTOFVIDEOMEMORY, false, true, false, 1);
  }
  state = {};
  Direct3DDevice9Ex_LSS<EnableSync> device;
  const auto result = Volume ?
    device.CreateVolumeTexture(16, 8, 4, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, nullptr, nullptr) :
    device.CreateCubeTexture(16, 1, 0, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, nullptr, nullptr);
  require(result == D3DERR_INVALIDCALL && !state.tracked && state.messages.empty(),
    "null output changed validation or created a resource");
}

int main() {
  try {
    runCases<true, false>();
    runCases<false, false>();
    runCases<true, true>();
    runCases<false, true>();
    std::puts("PASS: actual volume/cube creation, cancellation and destruction; HRESULT/output/ownership, explicit failure versus timeout, sync/async responses, wire fields and mip levels.");
    return 0;
  } catch (const std::exception& error) {
    std::fprintf(stderr, "%s\n", error.what());
    return 1;
  }
}
