// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d9.h>
#include <cstdio>
#include <cstring>
#include <limits>
#include <stdexcept>
#include <vector>
#include "volume_layout.h"

namespace {
void require(bool value, const char* message) {
  if (!value) { throw std::runtime_error(message); }
}
struct Wire {
  std::vector<uint32_t> fields;
  template<typename... Values> void send_many(Values... values) { fields = { values... }; }
};
uint8_t pattern(uint32_t x, uint32_t y, uint32_t z, uint32_t byte) {
  return static_cast<uint8_t>((x * 7 + y * 19 + z * 43 + byte * 61) & 255u);
}
unsigned cases = 0;

void transfer(uint32_t parentWidth, uint32_t parentHeight, uint32_t parentDepth,
              D3DBOX box, uint32_t block, uint32_t element) {
  D3DVOLUME_DESC desc {};
  desc.Width = parentWidth; desc.Height = parentHeight; desc.Depth = parentDepth;
  l4d2_volume::Layout storage;
  require(l4d2_volume::layout(box, desc, block, element, storage), "valid lock rejected");
  std::vector<uint8_t> allocation(static_cast<size_t>(storage.bytes) + 32, 0xcd);
  const auto locked = l4d2_volume::lockedBox(allocation.data() + 16, storage);
  const uint32_t columns = (box.Right - box.Left + block - 1) / block;
  const uint32_t rows = (box.Bottom - box.Top + block - 1) / block;
  require(locked.RowPitch == static_cast<int32_t>(columns * element)
    && locked.SlicePitch == static_cast<int32_t>(columns * rows * element), "API pitches are not byte strides");

  // The game writes through the returned API pitches, including a nonzero parent slice.
  std::vector<uint8_t> expected;
  for (uint32_t z = box.Front; z < box.Back; ++z) {
    for (uint32_t y = 0; y < rows; ++y) {
      auto* row = static_cast<uint8_t*>(locked.pBits)
        + static_cast<size_t>(z - box.Front) * locked.SlicePitch + static_cast<size_t>(y) * locked.RowPitch;
      for (uint32_t x = 0; x < columns; ++x) {
        for (uint32_t b = 0; b < element; ++b) {
          const auto value = pattern(box.Left / block + x, box.Top / block + y, z, b);
          row[x * element + b] = value;
          expected.push_back(value);
        }
      }
    }
  }
  std::vector<uint8_t> payload;
  require(l4d2_volume::visitRows(locked.pBits, locked.RowPitch, locked.SlicePitch, storage,
    [&](const uint8_t* row, uint32_t bytes) { payload.insert(payload.end(), row, row + bytes); }), "packing rejected");
  require(payload == expected && payload.size() == storage.bytes, "serialized volume differs from game writes");
  for (size_t i = 0; i < 16; ++i) {
    require(allocation[i] == 0xcd && allocation[allocation.size() - 1 - i] == 0xcd, "lock buffer overrun");
  }
  Wire wire; storage.send(wire);
  require(wire.fields == std::vector<uint32_t>({ element, columns, rows, box.Back - box.Front }),
    "existing four-field block-count wire changed");

  // Emulate the unchanged Host decoder into a padded backend allocation, then check every byte.
  const uint32_t backendColumns = (parentWidth + block - 1) / block;
  const uint32_t backendRows = (parentHeight + block - 1) / block;
  const size_t backendPitch = backendColumns * element + 17;
  const size_t backendSlice = backendPitch * backendRows + 23;
  std::vector<uint8_t> backend(backendSlice * parentDepth, 0xea), expectedBackend(backend.size(), 0xea);
  const size_t start = box.Front * backendSlice + (box.Top / block) * backendPitch + (box.Left / block) * element;
  const size_t wireRow = static_cast<size_t>(wire.fields.at(0)) * wire.fields.at(1);
  const size_t wireSlice = wireRow * wire.fields.at(2);
  for (uint32_t z = 0; z < wire.fields.at(3); ++z) {
    for (uint32_t y = 0; y < wire.fields.at(2); ++y) {
      std::memcpy(backend.data() + start + z * backendSlice + y * backendPitch,
        payload.data() + z * wireSlice + y * wireRow, wireRow);
    }
  }
  for (uint32_t z = box.Front; z < box.Back; ++z) {
    for (uint32_t y = box.Top / block; y < box.Top / block + rows; ++y) {
      for (uint32_t x = box.Left / block; x < box.Left / block + columns; ++x) {
        for (uint32_t b = 0; b < element; ++b) {
          expectedBackend[z * backendSlice + y * backendPitch + x * element + b] = pattern(x, y, z, b);
        }
      }
    }
  }
  require(backend == expectedBackend, "backend content, partial-box boundaries or padding corrupted");
  ++cases;
}
void reject(D3DBOX box, D3DVOLUME_DESC desc, uint32_t block, uint32_t element) {
  l4d2_volume::Layout result { 1, 1, 1, 1, 1, 1, 1, 1, 1 };
  require(!l4d2_volume::layout(box, desc, block, element, result) && !result.bytes, "invalid/overflow layout accepted");
  ++cases;
}
}
int main() {
  try {
    transfer(32, 32, 32, { 0, 0, 32, 32, 0, 32 }, 1, 4);
    for (uint32_t z = 0; z < 32; ++z) {
      transfer(32, 32, 32, { 0, 0, 32, 32, z, z + 1 }, 1, 4);
    }
    for (const auto bytes : { 1u, 2u, 3u, 4u, 8u, 16u }) {
      transfer(16, 13, 9, { 3, 2, 12, 11, 4, 7 }, 1, bytes);
    }
    // DXT1, DXT2/3/4/5 block geometry: full, nonzero box, edge, minimum mip.
    for (const auto bytes : { 8u, 16u }) {
      transfer(32, 32, 8, { 0, 0, 32, 32, 0, 8 }, 4, bytes);
      transfer(32, 32, 8, { 4, 8, 20, 24, 3, 5 }, 4, bytes);
      transfer(9, 7, 3, { 4, 4, 9, 7, 1, 2 }, 4, bytes);
      transfer(1, 1, 1, { 0, 0, 1, 1, 0, 1 }, 4, bytes);
    }
    D3DVOLUME_DESC desc {}; desc.Width = desc.Height = desc.Depth = 32;
    for (const auto box : { D3DBOX { 0, 0, 0, 32, 0, 32 }, D3DBOX { 9, 0, 8, 32, 0, 32 },
      D3DBOX { 0, 9, 32, 8, 0, 32 }, D3DBOX { 0, 0, 32, 32, 9, 8 },
      D3DBOX { 0, 0, 33, 32, 0, 32 }, D3DBOX { 0, 0, 32, 33, 0, 32 },
      D3DBOX { 0, 0, 32, 32, 0, 33 } }) { reject(box, desc, 1, 4); }
    reject({ 0, 0, 32, 32, 0, 32 }, desc, 0, 4);
    reject({ 0, 0, 32, 32, 0, 32 }, desc, 1, 0);
    desc.Width = desc.Height = desc.Depth = (std::numeric_limits<uint32_t>::max)();
    reject({ 0, 0, desc.Width, 1, 0, 1 }, desc, 1, 4);
    reject({ 0, 0, 65536, 65536, 0, 1 }, desc, 1, 4);
    reject({ 0, 0, 32768, 8192, 0, 4 }, desc, 1, 4);

    desc.Width = desc.Height = 2; desc.Depth = 2;
    l4d2_volume::Layout compact;
    require(l4d2_volume::layout({ 0, 0, 2, 2, 0, 2 }, desc, 1, 4, compact), "small layout failed");
    std::vector<uint8_t> padded(80, 0xa5);
    const uint8_t expected[] = { 1, 2, 3, 4, 5, 6, 7, 8 };
    for (const auto offset : { 0u, 12u, 40u, 52u }) { std::memcpy(padded.data() + offset, expected, 8); }
    std::vector<uint8_t> packed;
    require(l4d2_volume::visitRows(padded.data(), 12, 40, compact, [&](const uint8_t* row, uint32_t n) {
      packed.insert(packed.end(), row, row + n);
    }) && packed.size() == 32, "padded source failed");
    for (size_t i = 0; i < packed.size(); ++i) { require(packed[i] == expected[i % 8], "padding included in wire"); }
    unsigned writes = 0;
    const auto sink = [&](const uint8_t*, uint32_t) { ++writes; };
    require(!l4d2_volume::visitRows(nullptr, 8, 16, compact, sink)
      && !l4d2_volume::visitRows(padded.data(), -1, 16, compact, sink)
      && !l4d2_volume::visitRows(padded.data(), 2, 2, compact, sink)
      && !l4d2_volume::visitRows(padded.data(), 8, 8, compact, sink) && writes == 0,
      "bad byte pitches were read (includes the previous count-pitch defect)");
    std::printf("PASS: %u Volume layout/transfer cases, game writes through API pitches, unchanged wire, padded backend and partial-box guards; padded source and invalid stride rejection.\n", cases);
    return 0;
  } catch (const std::exception& error) { std::fprintf(stderr, "%s\n", error.what()); return 1; }
}
