// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once
#include <cstdio>
#include <stdexcept>
#include <string>

namespace bridge_util {
enum class LogLevel { Trace, Debug, Info, Warn, Error };
class Logger {
public:
  static bool isEnabled(LogLevel) { return false; }
  static void info(const std::string&) {}
  static void warn(const std::string&) {}
  // Throw instead of opening a fatal-error dialog. This also lets the harness
  // verify the actual Host Command constructor rejects overlapping lifetimes.
  static void err(const std::string& value) { throw std::runtime_error(value); }
  [[noreturn]] static void errLogMessageBoxAndExit(const std::string& value) {
    throw std::runtime_error(value);
  }
  template<class F> static void debugLazy(F&&) {}
  template<class F> static void traceLazy(F&&) {}
};

template<class... Args>
std::string format_string(const char* format, Args... args) {
  const int size = std::snprintf(nullptr, 0, format, args...);
  if (size < 0) { throw std::runtime_error("test log formatting failed"); }
  std::string result(static_cast<size_t>(size) + 1, '\0');
  std::snprintf(result.data(), result.size(), format, args...);
  result.resize(static_cast<size_t>(size));
  return result;
}
}
