// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include <windows.h>
#include <tlhelp32.h>
#include <cstdio>
#include <string>
#include "sdk/l4n_plugin.h"
#include "pageblock_control.h"

namespace {
class BridgePlugin final : public IL4NPlugin {
  std::string m_menu;
  std::string m_status;
  static const char* callback(void* userData);
  static const char* policyName(l4d2_control::Policy policy) {
    switch (policy) {
    case l4d2_control::Policy::Keep: return "keep";
    case l4d2_control::Policy::LearnedAggressive: return "learned-aggressive";
    case l4d2_control::Policy::Drop: return "drop [experimental]";
    }
    return "unknown";
  }
  static l4d2_control::Invoke findControl() {
    // Use already loaded modules. Never load another D3D9 runtime into the game.
    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE, GetCurrentProcessId());
    if (snapshot == INVALID_HANDLE_VALUE) { return nullptr; }
    MODULEENTRY32W module {}; module.dwSize = sizeof(module);
    l4d2_control::Invoke invoke = nullptr;
    if (Module32FirstW(snapshot, &module)) {
      do {
        invoke = reinterpret_cast<l4d2_control::Invoke>(GetProcAddress(module.hModule, l4d2_control::kExport));
        if (invoke) { break; }
      } while (Module32NextW(snapshot, &module));
    }
    CloseHandle(snapshot);
    return invoke;
  }
  static std::string item(const char* title, uintptr_t action) {
    char text[320] {};
    sprintf_s(text, "\"%s\" { \"callback\" \"0x%llx\" \"user_data\" \"0x%llx\" }\n", title,
      static_cast<unsigned long long>(reinterpret_cast<uintptr_t>(&callback)), static_cast<unsigned long long>(action));
    return text;
  }
  static std::string info(const std::string& title) { return item(title.c_str(), 0); }
  const char* statusMenu(const char* title) {
    m_menu = std::string("\"") + title + "\" {\n" + info(m_status) + "}\n";
    return m_menu.c_str();
  }
  const char* menu() {
    m_menu = "\"L4D2 Bridge\" {\n";
    if (!m_status.empty()) { m_menu += info("Last action result: " + m_status); }
    m_menu += item("PageBlock Stats", 1) + item("Retention Policy", 2)
      + item("GC Learned", 20) + item("GC Aggressive", 21) + item("GC Force", 22);
    m_menu += "}\n"; return m_menu.c_str();
  }
public:
  unsigned int GetInterfaceVersion() override { return 2; }
  const char* GetName() override { return "L4D2 Bridge Controls"; }
  const char* GetVersion() override { return "experimental-3"; }
  const char* RequestHudMenu(bool requestTitle) override { return requestTitle ? "L4D2 Bridge" : menu(); }
  const char* action(uintptr_t action) {
    // SDK non-null callback results open children; navigation belongs to L4N.
    if (!action) { return nullptr; }
    const auto invoke = findControl();
    if (!invoke) {
      m_status = "Bridge control API unavailable: install matching experimental client";
      return statusMenu("Bridge Request Failed");
    }
    l4d2_control::Request request;
    if (action >= 10 && action <= 12) { request.operation = l4d2_control::Operation::SetPolicy; request.value = static_cast<uint32_t>(action - 10); }
    else if (action >= 20 && action <= 22) { request.operation = l4d2_control::Operation::Gc; request.value = static_cast<uint32_t>(action - 20); }
    else if (action != 1 && action != 2) {
      m_status = "Invalid control action"; return statusMenu("Bridge Request Failed");
    }
    l4d2_control::DetailedResponse extended;
    auto& response = extended.base;
    request.version = l4d2_control::kDetailedVersion;
    HRESULT hr = invoke(&request, &response);
    if (hr == E_INVALIDARG) {
      // Older Bridge clients reject v2 before executing the operation.
      request.version = l4d2_control::kVersion; response = l4d2_control::Response {};
      hr = invoke(&request, &response);
    }
    const bool detailed = SUCCEEDED(hr) && response.version == l4d2_control::kDetailedVersion
      && response.bytes == sizeof(extended);
    if (FAILED(hr)) {
      char text[160] {}; sprintf_s(text, "Bridge request failed: 0x%08lx", static_cast<unsigned long>(hr));
      m_status = text; return statusMenu("Bridge Request Failed");
    }
    if (action == 2) {
      m_menu = "\"Retention Policy\" {\n" + info("Session only; bridge.conf is unchanged")
        + item("keep", 10) + item("learned-aggressive", 11) + item("drop [experimental]", 12) + "}\n";
      return m_menu.c_str();
    }
    if (action == 1) {
      m_menu = "\"PageBlock Stats\" {\n" + info(std::string("Policy: ") + policyName(response.policy));
      char text[200] {};
      sprintf_s(text, "Blocks: %llu; locked: %llu; transferring: %llu", response.pageBlocks, response.locked, response.transferring); m_menu += info(text);
      sprintf_s(text, "Client mapped VA: %.2f MiB; backing: %.2f MiB", response.mappedBytes / 1048576.0, response.backingBytes / 1048576.0); m_menu += info(text);
      sprintf_s(text, "Drop evictions: %llu; cumulative released: %.2f MiB", response.dropEvictionCount, response.dropEvictedBytes / 1048576.0); m_menu += info(text);
      sprintf_s(text, "Remaps after drop: %llu; reconstruction failures: %llu", response.remapCountAfterDrop, response.reconstructionFailures); m_menu += info(text);
      if (detailed) {
        const auto& c = extended.coverage;
        sprintf_s(text, "Tracked: %llu; capable: %llu; non-reclaimable: %llu", c.tracked, c.capable, c.nonReclaimable); m_menu += info(text);
        sprintf_s(text, "Safe now: %llu; KEEP: %llu; evictable: %llu", c.safeNow, c.learnedKeep, c.learnedEvictable); m_menu += info(text);
        sprintf_s(text, "Unsupported: %llu; recovery gap: %llu; unclassified: %llu", c.unsupportedCapability, c.recoveryUnavailable, c.learnedUnclassified); m_menu += info(text);
      }
      if (response.flags & 1) { m_menu += info("Reference readback test active: eviction controls disabled"); }
      if (!(response.flags & 2)) { m_menu += info("Unsupported shared heap/backend: eviction controls disabled"); }
      m_menu += "}\n"; return m_menu.c_str();
    }
    if (request.operation == l4d2_control::Operation::Gc) {
      char text[220] {};
      sprintf_s(text, "GC evicted %llu; VA freed %.2f MiB; backing freed %.2f MiB", response.pageBlocksEvicted, response.bytesUnmapped / 1048576.0, response.backingBytesReleased / 1048576.0);
      m_status = text;
      m_menu = "\"PageBlock GC Result\" {\n" + info(m_status);
      sprintf_s(text, "Skipped locked: %llu; transfers: %llu; policy: %llu", response.pageBlocksSkippedLocked, response.pageBlocksSkippedTransferring, response.pageBlocksSkippedPolicy); m_menu += info(text);
      sprintf_s(text, "Unsynchronized: %llu; failures: %llu", response.pageBlocksSkippedUnsynchronized, response.failures); m_menu += info(text);
      if (detailed) {
        sprintf_s(text, "Unsupported: %llu; recovery gap: %llu; unclassified: %llu", extended.skippedUnsupportedCapability, extended.skippedRecoveryUnavailable, extended.skippedUnclassified); m_menu += info(text);
        sprintf_s(text, "No backing: %llu; reference test: %llu", extended.skippedNoBacking, extended.skippedReferenceTest); m_menu += info(text);
        sprintf_s(text, "Host ACK waits: %llu; time: %.3f ms", extended.hostAckWaitCount, extended.hostAckWaitTimeMs); m_menu += info(text);
      }
      sprintf_s(text, "Drained: %llu; waits: %llu; wait time: %.3f ms", response.transfersDrained, response.drainWaitCount, response.drainWaitTimeMs); m_menu += info(text);
      m_menu += "}\n"; return m_menu.c_str();
    }
    m_status = std::string("Policy selected: ") + policyName(response.policy);
    return statusMenu("Policy Change Result");
  }
};
BridgePlugin& instance() { static BridgePlugin plugin; return plugin; }
const char* BridgePlugin::callback(void* userData) { return instance().action(reinterpret_cast<uintptr_t>(userData)); }
}
extern "C" __declspec(dllexport) IL4NPlugin* GetL4NPluginInstance() { return &instance(); }
