// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include <windows.h>
#include <tlhelp32.h>
#include <cstdio>
#include <string>
#include "sdk/l4n_plugin.h"
#include "bridge_control.h"

namespace {
namespace general = l4d2_bridge_control;
class BridgePlugin final : public IL4NPlugin {
  std::string m_menu, m_status;
  general::Host m_selectedHost = general::Host::Unknown;
  struct Controls { general::Invoke settings = nullptr; l4d2_control::Invoke pageBlocks = nullptr; };
  static const char* callback(void* userData);
  static const char* policyName(l4d2_control::Policy policy) {
    switch (policy) {
    case l4d2_control::Policy::Keep: return "keep";
    case l4d2_control::Policy::LearnedAggressive: return "learned-aggressive";
    case l4d2_control::Policy::Drop: return "drop [experimental]";
    }
    return "unknown";
  }
  static const char* hostName(general::Host host) {
    return host == general::Host::X86 ? "x86" : host == general::Host::X64 ? "x64" : "unavailable";
  }
  static const char* policyLabel(l4d2_control::Policy policy) {
    return policy == l4d2_control::Policy::LearnedAggressive ? "lg"
      : policy == l4d2_control::Policy::Keep ? "keep"
      : policy == l4d2_control::Policy::Drop ? "drop" : "unknown";
  }
  static Controls findControls() {
    // Use already loaded modules. Never load another D3D9 runtime into the game.
    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE, GetCurrentProcessId());
    if (snapshot == INVALID_HANDLE_VALUE) { return {}; }
    MODULEENTRY32W module {}; module.dwSize = sizeof(module);
    Controls result;
    if (Module32FirstW(snapshot, &module)) {
      do {
        auto pageBlocks = reinterpret_cast<l4d2_control::Invoke>(GetProcAddress(module.hModule, l4d2_control::kExport));
        if (!pageBlocks) { continue; }
        result.pageBlocks = pageBlocks;
        result.settings = reinterpret_cast<general::Invoke>(GetProcAddress(module.hModule, general::kExport));
        break;
      } while (Module32NextW(snapshot, &module));
    }
    CloseHandle(snapshot);
    return result;
  }
  static std::string escape(const std::string& title) {
    std::string result;
    for (char c : title) {
      if (c == '"' || c == '\\') { result += '\\'; }
      result += c == '\n' || c == '\r' ? ' ' : c;
    }
    return result;
  }
  static std::string item(const std::string& title, uintptr_t action) {
    char text[160] {};
    sprintf_s(text, " { \"callback\" \"0x%llx\" \"user_data\" \"0x%llx\" }\n",
      static_cast<unsigned long long>(reinterpret_cast<uintptr_t>(&callback)), static_cast<unsigned long long>(action));
    return "\"" + escape(title) + "\"" + text;
  }
  static std::string info(const std::string& title) { return item(title, 0); }
  static std::string error(HRESULT hr) {
    char code[40] {}, description[256] {};
    sprintf_s(code, "0x%08lx", static_cast<unsigned long>(hr));
    const DWORD message = HRESULT_FACILITY(hr) == FACILITY_WIN32 ? HRESULT_CODE(hr) : static_cast<DWORD>(hr);
    FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, nullptr,
      message, MAKELANGID(LANG_ENGLISH, SUBLANG_ENGLISH_US), description, sizeof(description), nullptr);
    return std::string(code) + (description[0] ? std::string(" ") + description : "");
  }
  const char* page(const char* title, const std::string& rows) {
    m_menu = std::string("\"") + title + "\" {\n" + rows + "}\n";
    return m_menu.c_str();
  }
  const char* failed(const std::string& message) {
    m_status = message; return page("Bridge Request Failed", info(message));
  }
  static HRESULT query(general::Invoke invoke, general::Operation operation, uint32_t value, general::Response& response) {
    if (!invoke) { return E_NOINTERFACE; }
    general::Request request; request.operation = operation; request.value = value;
    const auto hr = invoke(&request, &response);
    return SUCCEEDED(hr) && !general::compatible(request, response) ? E_UNEXPECTED : hr;
  }
  static HRESULT pageBlocks(l4d2_control::Invoke invoke, l4d2_control::Operation operation, uint32_t value,
      l4d2_control::DetailedResponse& extended, bool& detailed) {
    if (!invoke) { return E_NOINTERFACE; }
    l4d2_control::Request request; request.operation = operation; request.value = value; request.version = l4d2_control::kDetailedVersion;
    auto& response = extended.base;
    auto hr = invoke(&request, &response);
    if (hr == E_INVALIDARG) {
      request.version = l4d2_control::kVersion; response = l4d2_control::Response {};
      hr = invoke(&request, &response);
    }
    if (SUCCEEDED(hr) && !l4d2_control::compatible(request, response)) { return E_UNEXPECTED; }
    detailed = SUCCEEDED(hr) && response.version == l4d2_control::kDetailedVersion;
    return hr;
  }
  const char* status(const Controls& controls) {
    std::string rows;
    l4d2_control::DetailedResponse extended; bool detailed = false;
    const auto hr = pageBlocks(controls.pageBlocks, l4d2_control::Operation::Stats, 0, extended, detailed);
    if (FAILED(hr)) { return page("Status", rows + info("PageBlock status failed: " + error(hr))); }
    const auto& response = extended.base;
    rows += info(std::string("Memory Policy: ") + policyName(response.policy));
    char text[220] {};
    sprintf_s(text, "Blocks: %llu; locked: %llu; transferring: %llu", response.pageBlocks, response.locked, response.transferring); rows += info(text);
    sprintf_s(text, "Client mapped VA: %.2f MiB; backing: %.2f MiB", response.mappedBytes / 1048576.0, response.backingBytes / 1048576.0); rows += info(text);
    sprintf_s(text, "Drop evictions: %llu; cumulative released: %.2f MiB", response.dropEvictionCount, response.dropEvictedBytes / 1048576.0); rows += info(text);
    sprintf_s(text, "Remaps after drop: %llu; reconstruction failures: %llu", response.remapCountAfterDrop, response.reconstructionFailures); rows += info(text);
    if (detailed) {
      const auto& c = extended.coverage;
      sprintf_s(text, "Tracked: %llu; capable: %llu; non-reclaimable: %llu", c.tracked, c.capable, c.nonReclaimable); rows += info(text);
      sprintf_s(text, "Safe now: %llu; KEEP: %llu; evictable: %llu", c.safeNow, c.learnedKeep, c.learnedEvictable); rows += info(text);
      sprintf_s(text, "Unsupported: %llu; recovery gap: %llu; unclassified: %llu", c.unsupportedCapability, c.recoveryUnavailable, c.learnedUnclassified); rows += info(text);
    }
    if (!(response.flags & 2)) { rows += info("Unsupported backing/backend: GC unavailable"); }
    return page("Status", rows);
  }
  const char* gc(const Controls& controls, uint32_t mode) {
    l4d2_control::DetailedResponse extended; bool detailed = false;
    const auto hr = pageBlocks(controls.pageBlocks, l4d2_control::Operation::Gc, mode, extended, detailed);
    if (FAILED(hr)) { return failed("Bridge request failed: " + error(hr)); }
    const auto& response = extended.base;
    char text[220] {};
    sprintf_s(text, "GC evicted %llu; VA freed %.2f MiB; backing freed %.2f MiB", response.pageBlocksEvicted, response.bytesUnmapped / 1048576.0, response.backingBytesReleased / 1048576.0);
    m_status = text;
    std::string rows = info(m_status);
    sprintf_s(text, "Skipped locked: %llu; transfers: %llu; policy: %llu", response.pageBlocksSkippedLocked, response.pageBlocksSkippedTransferring, response.pageBlocksSkippedPolicy); rows += info(text);
    sprintf_s(text, "Unsynchronized: %llu; failures: %llu", response.pageBlocksSkippedUnsynchronized, response.failures); rows += info(text);
    if (detailed) {
      sprintf_s(text, "Unsupported: %llu; recovery gap: %llu; unclassified: %llu", extended.skippedUnsupportedCapability, extended.skippedRecoveryUnavailable, extended.skippedUnclassified); rows += info(text);
      sprintf_s(text, "No backing: %llu", extended.skippedNoBacking); rows += info(text);
      sprintf_s(text, "Host ACK waits: %llu; time: %.3f ms", extended.hostAckWaitCount, extended.hostAckWaitTimeMs); rows += info(text);
    }
    sprintf_s(text, "Drained: %llu; waits: %llu; wait time: %.3f ms", response.transfersDrained, response.drainWaitCount, response.drainWaitTimeMs); rows += info(text);
    return page("PageBlock GC Result", rows);
  }
  std::string policyRows(const Controls& controls) {
    general::Response settings;
    if (controls.settings) {
      const auto hr = query(controls.settings, general::Operation::GetMemoryPolicy, 0, settings);
      if (SUCCEEDED(hr) && SUCCEEDED(settings.runtimeResult)) {
        const bool configured = SUCCEEDED(settings.queryResult) && settings.runtimePolicy == settings.configuredPolicy;
        auto rows = info(std::string(u8"当前策略: ") + policyLabel(settings.runtimePolicy) + (configured ? " (configure)" : " (runtime)"));
        if (FAILED(settings.queryResult)) { rows += info("Configuration unavailable: " + error(settings.queryResult)); }
        return rows;
      }
    }
    l4d2_control::DetailedResponse response; bool detailed = false;
    const auto hr = pageBlocks(controls.pageBlocks, l4d2_control::Operation::Stats, 0, response, detailed);
    auto rows = SUCCEEDED(hr) ? info(std::string(u8"当前策略: ") + policyLabel(response.base.policy) + " (runtime)")
      : info("Current policy unavailable: " + error(hr));
    rows += info(controls.settings ? "Configuration status unavailable" : "Older Bridge: configuration save unavailable");
    return rows;
  }
  static std::string policySave(const Controls& controls) {
    return controls.settings ? item("save to configure", 13) : info("save to configure [unavailable]");
  }
  const char* setPolicy(const Controls& controls, uint32_t value) {
    l4d2_control::DetailedResponse response; bool detailed = false;
    const auto hr = pageBlocks(controls.pageBlocks, l4d2_control::Operation::SetPolicy, value, response, detailed);
    if (FAILED(hr)) { return failed("Runtime policy failed: " + error(hr)); }
    m_status = std::string("Runtime policy changed to ") + policyLabel(response.base.policy) + "; configuration unchanged";
    return page("Memory Policy Result", policyRows(controls) + info(m_status) + policySave(controls));
  }
  const char* savePolicy(const Controls& controls) {
    if (!controls.settings) { return failed("Configuration save unavailable on this Bridge"); }
    l4d2_control::DetailedResponse runtime; bool detailed = false;
    const auto statsResult = pageBlocks(controls.pageBlocks, l4d2_control::Operation::Stats, 0, runtime, detailed);
    if (FAILED(statsResult)) { return failed("Cannot save current runtime policy: " + error(statsResult)); }
    general::Response response;
    // The existing ABI reasserts this same runtime value before saving it.
    const auto hr = query(controls.settings, general::Operation::SetMemoryPolicy, static_cast<uint32_t>(runtime.base.policy), response);
    if (FAILED(hr)) { return failed("Memory policy request failed: " + error(hr)); }
    const auto checked = SUCCEEDED(response.runtimeResult) ? std::string("Runtime policy: ") + policyLabel(response.runtimePolicy)
      : "Runtime policy confirmation failed: " + error(response.runtimeResult);
    const auto saved = response.configWriteSucceeded ? std::string("Config saved successfully") : "Warning: failed to persist configuration: " + error(response.configResult);
    m_status = checked + "; " + saved;
    return page("Memory Policy Save Result", policyRows(controls) + info(checked) + info(saved));
  }
  std::string hostRows(const Controls& controls, bool resetSelection = false) {
    general::Response response;
    const auto hr = query(controls.settings, general::Operation::GetHostMode, 0, response);
    const bool available = SUCCEEDED(hr) && SUCCEEDED(response.queryResult);
    if (resetSelection) { m_selectedHost = available ? response.configuredHost : general::Host::Unknown; }
    return available ? info(std::string("Configured Host: ") + hostName(response.configuredHost))
      : info("Configured Host unavailable: " + error(FAILED(hr) ? hr : response.queryResult));
  }
  const char* selectHost(const Controls& controls, general::Host host) {
    if (!controls.settings) { return failed("Host configuration unavailable on this Bridge"); }
    m_selectedHost = host;
    m_status = std::string("Selected Host: ") + hostName(host) + "; configuration unchanged";
    return page("Host Selection", hostRows(controls) + info(m_status)
      + info("Save configuration; restart L4D2 to apply") + item("Save", 42));
  }
  const char* saveHost(const Controls& controls) {
    if (m_selectedHost != general::Host::X86 && m_selectedHost != general::Host::X64) { return failed("Select a Host before saving"); }
    return setPersistent(controls, general::Operation::SetHostMode, static_cast<uint32_t>(m_selectedHost));
  }
  const char* setPersistent(const Controls& controls, general::Operation operation, uint32_t value) {
    if (!controls.settings) { return failed("Persistent Host / ReShade settings unavailable on this Bridge"); }
    general::Response response;
    const auto hr = query(controls.settings, operation, value, response);
    if (FAILED(hr)) { return failed("Settings request failed: " + error(hr)); }
    if (!response.configWriteSucceeded) { return failed("Failed to persist configuration: " + error(response.configResult)); }
    const auto title = operation == general::Operation::SetHostMode ? "Host Result" : "ReShade Presenter Result";
    m_status = operation == general::Operation::SetHostMode
      ? std::string("Host set to ") + hostName(static_cast<general::Host>(value)) + "."
      : std::string("ReShade Presenter ") + (value ? "enabled." : "disabled.");
    m_status += " Restart L4D2 to apply.";
    std::string rows = info(m_status);
    if (operation == general::Operation::SetHostMode) { rows += hostRows(controls); }
    if (operation == general::Operation::SetReShadePresenter && value && response.configuredHost == general::Host::X86) {
      rows += info("Note: validated ReShade combination is x64 Host + Vulkan ReShade 6.0.1.");
    }
    if (FAILED(response.queryResult)) { rows += info("Saved; status read failed: " + error(response.queryResult)); }
    return page(title, rows);
  }
public:
  unsigned int GetInterfaceVersion() override { return 2; }
  const char* GetName() override { return "L4D2 Bridge Controls"; }
  const char* GetVersion() override { return "common-settings-2"; }
  const char* RequestHudMenu(bool requestTitle) override {
    if (requestTitle) { return "L4D2 Bridge"; }
    auto rows = item("Status", 1) + item("GC", 2) + item("Memory Policy", 3) + item("ReShade Presenter", 4) + item("Host", 5);
    if (!m_status.empty()) { rows += info("Last action result: " + m_status); }
    return page("L4D2 Bridge", rows);
  }
  const char* action(uintptr_t action) {
    // SDK non-null callback results open children; navigation belongs to L4N.
    if (!action) { return nullptr; }
    const auto controls = findControls();
    if (action == 1) { return status(controls); }
    if (action == 2) { return page("GC", item("Learned", 20) + item("Aggressive", 21) + item("Force", 22)); }
    if (action == 3) {
      return page("Memory Policy", policyRows(controls) + item("keep", 10) + item("lg", 11)
        + item("drop [experimental]", 12) + policySave(controls));
    }
    if (action == 4 || action == 5) {
      if (!controls.settings) { return page(action == 4 ? "ReShade Presenter" : "Host", info("Unavailable: this Bridge has no persistent settings API")); }
      if (action == 5) {
        return page("Host", hostRows(controls, true) + item("x86 Host", 40) + item("x64 Host", 41) + item("Save", 42));
      }
      general::Response response;
      const auto hr = query(controls.settings, general::Operation::GetReShadePresenter, 0, response);
      std::string rows = info("Save configuration; restart L4D2 to apply");
      if (FAILED(hr) || FAILED(response.queryResult)) { rows += info("Current configuration unavailable: " + error(FAILED(hr) ? hr : response.queryResult)); }
      else {
        rows += info(std::string("Configured: ") + (response.presenterConfigured ? "Enabled" : "Disabled"));
      }
      return page("ReShade Presenter", rows + info("Controls Bridge Presenter/input support; does not install ReShade") + item("Enable", 30) + item("Disable", 31));
    }
    if (action >= 10 && action <= 12) { return setPolicy(controls, static_cast<uint32_t>(action - 10)); }
    if (action == 13) { return savePolicy(controls); }
    if (action >= 20 && action <= 22) { return gc(controls, static_cast<uint32_t>(action - 20)); }
    if (action == 30 || action == 31) { return setPersistent(controls, general::Operation::SetReShadePresenter, action == 30 ? 1u : 0u); }
    if (action == 40 || action == 41) { return selectHost(controls, action == 40 ? general::Host::X86 : general::Host::X64); }
    if (action == 42) { return saveHost(controls); }
    return failed("Invalid control action");
  }
};
BridgePlugin& instance() { static BridgePlugin plugin; return plugin; }
const char* BridgePlugin::callback(void* userData) { return instance().action(reinterpret_cast<uintptr_t>(userData)); }
}
extern "C" __declspec(dllexport) IL4NPlugin* GetL4NPluginInstance() { return &instance(); }
