// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once

// The real transport uses ANSI Win32 mapping/semaphore APIs. The test launcher
// separately uses explicit wide APIs so executable paths may contain Unicode.
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0601
#endif
#undef UNICODE
#undef _UNICODE
#include <windows.h>
#include <array>
#include <atomic>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <stdexcept>
#include <string>
#include <vector>
#undef FORCEINLINE
#include "util_common.h"
using namespace bridge_util;

#ifdef USE_BLOCKING_QUEUE
#error "The command guard regression requires the production atomic queue."
#endif
#ifndef NDEBUG
#error "Use NDEBUG: Host nesting must reach the production runtime error check."
#endif
