#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Compare complete cumulative snapshots; never infer Source loading or GPU time."""
import argparse
import json
from pathlib import Path

COUNTERS = ("calls", "total_us", "inclusive_us", "ge_1ms", "ge_5ms", "ge_10ms", "ge_50ms", "ge_100ms")
DIRECT_WAITS = {"server_response_wait", "data_queue_full_wait", "command_queue_full_wait", "present_semaphore_wait", "resource_completion_wait"}


def fields(line):
    return dict(item.split("=", 1) for item in line.split()[1:] if "=" in item)


def snapshots(path):
    complete, current = [], None
    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("L4D2_API_WAIT_SUMMARY "):
            current = {"header": fields(line), "rows": {}, "threads": {}, "active_spans": {}}
        elif current and line.startswith("L4D2_API_WAIT_THREAD "):
            f = fields(line)
            if f["snapshot"] == current["header"]["snapshot"]:
                current["threads"][f["tid"]] = int(f["inflight"])
                current["active_spans"][f["tid"]] = {name: f.get(name) for name in ("active_api", "active_metric", "active_span_elapsed_us")}
        elif current and line.startswith("L4D2_API_WAIT "):
            f = fields(line)
            if f["snapshot"] == current["header"]["snapshot"]:
                current["rows"][(f["tid"], f["api"], f["metric"])] = f
        elif current and line.startswith("L4D2_API_WAIT_END "):
            if fields(line)["snapshot"] == current["header"]["snapshot"]:
                complete.append(current)
            current = None
    if len(complete) < 2:
        raise ValueError(f"Need at least two complete snapshots: {path}")
    identities = {(s["header"]["pid"], s["header"]["role"], s["header"]["frequency"]) for s in complete}
    if len(identities) != 1:
        raise ValueError(f"Mixed process sessions in {path}")
    return complete


def boundary(data, tick, fallback):
    if tick is None:
        return data[fallback]
    if tick < int(data[0]["header"]["tick_ms"]) or tick > int(data[-1]["header"]["tick_ms"]):
        raise ValueError("Requested boundary is outside the complete snapshot range")
    return min(data, key=lambda s: abs(int(s["header"]["tick_ms"]) - tick))


def report(path, begin_tick=None, end_tick=None, thread=None):
    data = snapshots(path)
    begin, end = boundary(data, begin_tick, 0), boundary(data, end_tick, -1)
    start, finish = int(begin["header"]["tick_ms"]), int(end["header"]["tick_ms"])
    if finish <= start:
        raise ValueError("Begin/end resolve to the same or reversed snapshot")
    rows, totals, per_thread = [], {}, {}
    for key, final in end["rows"].items():
        tid, api, metric = key
        if thread is not None and int(tid) != thread:
            continue
        initial = begin["rows"].get(key, {})
        delta = {name: float(final[name]) - float(initial.get(name, 0)) for name in COUNTERS}
        if any(value < 0 for value in delta.values()):
            raise ValueError(f"Counter regression: {key}")
        if not delta["calls"] and not delta["total_us"]:
            continue
        delta["calls"] = int(delta["calls"])
        delta["avg_inclusive_us"] = delta["inclusive_us"] / delta["calls"] if delta["calls"] else None
        # A cumulative maximum cannot be subtracted into an interval maximum.
        rows.append({"tid": int(tid), "api": api, "metric": metric, **delta,
                     "lifetime_max_us_at_end": float(final["max_us"])})
        totals[metric] = totals.get(metric, 0) + delta["total_us"]
        thread_totals = per_thread.setdefault(tid, {})
        thread_totals[metric] = thread_totals.get(metric, 0) + delta["total_us"]
    return {
        "path": str(path), "role": end["header"]["role"], "pid": int(end["header"]["pid"]),
        "begin_snapshot": int(begin["header"]["snapshot"]), "end_snapshot": int(end["header"]["snapshot"]),
        "begin_tick_ms": start, "end_tick_ms": finish, "snapshot_wall_ms": finish - start,
        "begin_boundary_error_ms": start - begin_tick if begin_tick is not None else None,
        "end_boundary_error_ms": finish - end_tick if end_tick is not None else None,
        "queued_commands_delta": int(end["header"]["commands"]) - int(begin["header"]["commands"]),
        "dropped_threads": int(end["header"]["dropped_threads"]),
        "inflight_at_begin": begin["threads"], "inflight_at_end": end["threads"],
        "active_spans_at_begin": begin["active_spans"], "active_spans_at_end": end["active_spans"],
        "metric_totals_us": totals, "per_thread_totals_us": per_thread,
        "direct_wait_path_total_us": sum(totals.get(name, 0) for name in DIRECT_WAITS),
        "rows": sorted(rows, key=lambda row: row["total_us"], reverse=True),
        "limits": ["summed durations are cumulative thread time and may overlap",
                   "snapshots are approximate; phases may complete before their enclosing API",
                   "unattributed includes scheduling, unmeasured locks and local work, not measured CPU time",
                   "queue delay and GPU execution time are unknown",
                   "lifetime maxima are not interval maxima; no percentile estimates"],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--client", required=True)
    parser.add_argument("--host")
    parser.add_argument("--begin-tick-ms", type=int)
    parser.add_argument("--end-tick-ms", type=int)
    parser.add_argument("--client-thread", type=int, help="Actual observed API thread ID; no inferred Source main thread")
    parser.add_argument("--observed-loading-ms", type=float, help="Independently measured loading wall time, not inferred by Bridge")
    args = parser.parse_args()
    result = {"observed_loading_wall_ms": args.observed_loading_ms,
              "client": report(args.client, args.begin_tick_ms, args.end_tick_ms, args.client_thread)}
    if args.host:
        result["host"] = report(args.host, args.begin_tick_ms, args.end_tick_ms)
        if result["client"]["role"] != "client" or result["host"]["role"] != "host":
            parser.error("Client and Host log roles must match their arguments")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
