# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Summarize cumulative Bridge data/resource snapshots without double counting."""
import argparse
import json
from pathlib import Path


def analyze(text):
    sessions = []
    session = None
    for number, line in enumerate(text.splitlines(), 1):
        if not line.strip():
            continue
        try:
            fields = dict(token.split("=", 1) for token in line.split())
            if fields.get("schema") != "1":
                raise ValueError("unsupported schema")
            event = fields["event"]
            if event == "CONFIG":
                session = {"role": fields["role"], "pid": int(fields["pid"]),
                           "build": fields["build"], "bits": int(fields["bits"]),
                           "start_ms": int(fields["tick_ms"]), "ended": False,
                           "kinds": {}, "commands": {}, "buffers": {}, "dynamic_locks": {}, "states": {},
                           "limits": {}, "warnings": [],
                           "observed_live": {}, "largest_released": []}
                sessions.append(session)
            if session is None:
                raise ValueError("record before CONFIG")
            if fields.get("role", session["role"]) != session["role"] or int(fields.get("pid", session["pid"])) != session["pid"]:
                raise ValueError("mixed process/role inside a session")
            values = {key: int(value) for key, value in fields.items() if value.isdecimal()}
            if event == "KIND":
                # Records are cumulative. Replace the previous snapshot; never sum it.
                session["kinds"][fields["kind"]] = values
            elif event == "BUFFER":
                session["buffers"][fields["kind"]] = values
            elif event == "DYNAMIC_LOCK":
                session["dynamic_locks"][fields["kind"]] = values
            elif event == "STATE":
                key = fields["command"] + ":" + fields["recording"]
                session["states"][key] = {**values, "name": fields["name"]}
            elif event == "COMMAND":
                key = fields["queue"] + ":" + fields["command"]
                session["commands"][key] = {**values, "name": fields["name"], "queue": fields["queue"]}
                if fields["name"] == "UnknownOverflow":
                    session["warnings"].append("unknown command IDs were coalesced")
            elif event in ("RESOURCE_LIVE", "RESOURCE_RELEASE"):
                key = fields["kind"] + ":" + fields["id"]
                resource = {**values, "kind": fields["kind"]}
                if event == "RESOURCE_LIVE":
                    session["observed_live"][key] = resource
                else:
                    session["observed_live"].pop(key, None)
                    session["largest_released"].append(resource)
                    session["largest_released"].sort(key=lambda row: row.get("shadow_bytes", 0), reverse=True)
                    del session["largest_released"][20:]
            elif event in ("SNAPSHOT", "END"):
                session["limits"].update(values)
                if event == "END":
                    session["ended"] = True
        except (ValueError, KeyError) as error:
            if session is None:
                raise ValueError(f"line {number}: {error}") from error
            session["warnings"].append(f"line {number}: {error}")
    if not sessions:
        raise ValueError("no data diagnostics session found")
    for session in sessions:
        if not session["ended"]:
            session["warnings"].append("missing END: log may be incomplete")
        for key in ("resource_overflow", "retired_dropped", "file_discarded", "write_failures"):
            if session["limits"].get(key, 0):
                session["warnings"].append(f"{key}={session['limits'][key]}: detailed evidence is incomplete")
        session["warnings"] = sorted(set(session["warnings"]))
        for kind, values in session["dynamic_locks"].items():
            count = values.get("lock_count", 0)
            values["average_lock_bytes"] = values.get("total_lock_bytes", 0) / count if count else None
            buckets = [value for key, value in values.items() if key.startswith("bucket_")]
            if buckets and sum(buckets) != count:
                session["warnings"].append(f"{kind}: dynamic histogram count mismatch")
        for values in session["states"].values():
            total, compared, same = (values.get(key, 0) for key in ("total_calls", "compared_calls", "same_value_calls"))
            values["same_value_ratio"] = same / total if total else None
            values["compared_same_value_ratio"] = same / compared if compared else None
            if same > compared or compared > total:
                session["warnings"].append(f"{values['name']}: inconsistent state equality counts")
        session["largest_observed_live"] = sorted(session["observed_live"].values(), key=lambda row: row.get("shadow_bytes", 0), reverse=True)[:20]
        # Live records rotate; this list is observed metadata, not a complete live inventory.
        del session["observed_live"]
        session["largest_transfer_commands"] = sorted(session["commands"].values(), key=lambda row: row.get("data_bytes", 0), reverse=True)[:10]
        session["slowest_handler_commands"] = sorted(session["commands"].values(), key=lambda row: row.get("handler_us", 0), reverse=True)[:10]
    return sessions


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("logs", nargs="+", type=Path)
    parser.add_argument("--json", type=Path, help="write a machine-readable report")
    args = parser.parse_args()
    reports = []
    for path in args.logs:
        for session in analyze(path.read_text(encoding="utf-8-sig", errors="replace")):
            session["source"] = str(path)
            reports.append(session)
    if args.json:
        args.json.write_text(json.dumps(reports, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    for session in reports:
        print(f"{session['source']}: {session['role']} pid={session['pid']} bits={session['bits']} build={session['build']}")
        for kind, values in session["kinds"].items():
            print(f"  {kind}: live={values.get('live', 0)} shadow={values.get('shadow_bytes', 0) / 1048576:.2f} MiB "
                  f"locks={values.get('locks', 0)} uploads={values.get('upload_bytes', 0) / 1048576:.2f} MiB "
                  f"readonly={values.get('readonly', 0)} invalid={values.get('invalid', 0)}")
        for kind, values in session["buffers"].items():
            print(f"  Storage {kind}: static WRITEONLY candidates={values.get('candidate_writeonly_static_bytes', 0) / 1048576:.2f} MiB "
                  f"dynamic shadow={values.get('dynamic_shadow_live_bytes', 0) / 1048576:.2f} MiB "
                  f"avoided={values.get('avoided_persistent_shadow_bytes_current', 0) / 1048576:.2f} MiB "
                  f"staging enabled={values.get('range_staging_enabled', 0)}")
        for kind, values in session["dynamic_locks"].items():
            print(f"  Dynamic {kind}: locks={values.get('lock_count', 0)} average={values['average_lock_bytes']} B "
                  f"min/max={values.get('min_lock_bytes', 0)}/{values.get('max_lock_bytes', 0)} B")
        for values in session["states"].values():
            print(f"  Local state {values['name']}: recording={values.get('recording', 0)} "
                  f"same/total={values.get('same_value_calls', 0)}/{values.get('total_calls', 0)} "
                  f"compared={values.get('compared_calls', 0)}")
        for row in session["largest_observed_live"][:5]:
            print(f"  Observed {row['kind']} id={row.get('id')}: shadow={row.get('shadow_bytes', 0) / 1048576:.2f} MiB "
                  f"locks={row.get('locks', 0)} lock_idle={row.get('lock_idle_ms', 0)} ms")
        for row in session["largest_transfer_commands"][:5]:
            print(f"  TX {row['queue']}/{row['name']}: {row.get('data_bytes', 0) / 1048576:.2f} MiB")
        for row in session["slowest_handler_commands"][:5]:
            print(f"  Handler {row['queue']}/{row['name']}: {row.get('handler_us', 0) / 1000:.3f} ms total, "
                  f"{row.get('max_handler_us', 0) / 1000:.3f} ms max")
        for warning in session["warnings"]:
            print("  Warning: " + warning)
    print("Shadow/temporary storage, cumulative serialized bytes and handler time are separate measures; none proves safe reclamation.")


if __name__ == "__main__":
    main()
