# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Match the opt-in Client/Host colour logs without requiring manual time markers."""
import argparse
from collections import Counter
import json
from pathlib import Path
import re


def rows(path):
    with Path(path).open(encoding="utf-8", errors="replace") as stream:
        for line in stream:
            row = dict(re.findall(r"([a-zA-Z_][a-zA-Z_0-9]*)=([^\s]+)", line))
            if "event" in row:
                yield row


def number(row, name, default=0):
    try:
        value = row.get(name, str(default))
        return int(value, 16 if value.lower().startswith("0x") else 10)
    except ValueError:
        return default


def analyze(client_path, host_path):
    creations = {"client": {}, "host": {}}
    uploads = {"client": {}, "host": {}}
    counts = {"client": Counter(), "host": Counter()}
    configs, limits, mismatches, volume_errors, failures, bindings, states = {}, {}, [], [], [], [], []
    for role, path in (("client", client_path), ("host", host_path)):
        for row in rows(path):
            event = row["event"]
            counts[role][event] += 1
            if event == "CONFIG":
                configs[role] = row
            elif event == "LIMITS":
                limits[role] = row
            key = (number(row, "uid"), number(row, "resource_id"))
            if event == "CREATE_TEXTURE_SERIALIZED" and role == "client":
                creations[role][key] = row
            elif event == "CREATE_TEXTURE_ORIGINAL" and role == "host":
                creations[role][key] = row
            elif event in ("CREATE_TEXTURE_RESULT", "CREATE_VOLUME_RESULT"):
                if number(row, "hresult") & 0x80000000 and len(failures) < 64:
                    failures.append(row)
            elif event == "UPLOAD":
                uploads[role][key] = row
            elif event == "CLIENT_VOLUME_LOCK":
                if number(row, "reported_row_pitch") < number(row, "expected_row_bytes") or number(row, "reported_slice_pitch") < number(row, "expected_slice_bytes"):
                    if len(volume_errors) < 64:
                        volume_errors.append(row)
            elif event == "CRITICAL_TEXTURE_BIND" and len(bindings) < 64:
                bindings.append(row)
            elif event == "BACKEND_STATE" and len(states) < 128:
                states.append(row)
    matched = 0
    fields = ("device_id", "width", "height", "depth", "levels", "usage", "format", "pool")
    for key, client in creations["client"].items():
        host = creations["host"].get(key)
        if host is None:
            continue
        matched += 1
        different = [name for name in fields if number(client, name) != number(host, name)]
        if different and len(mismatches) < 64:
            mismatches.append({"uid": key[0], "resource_id": key[1], "fields": different, "client": client, "host": host})
    payload_differences = []
    matched_uploads = 0
    for key, client in uploads["client"].items():
        host = uploads["host"].get(key)
        if host is None or number(client, "shared") or number(host, "shared"):
            continue
        matched_uploads += 1
        different = [name for name in ("payload_bytes", "hashed_bytes", "content_hash") if number(client, name) != number(host, name)]
        if different and len(payload_differences) < 64:
            payload_differences.append({"uid": key[0], "resource_id": key[1], "fields": different, "client": client, "host": host})
    return {
        "configs": configs,
        "builds_match": len(configs) == 2 and configs["client"].get("build") == configs["host"].get("build"),
        "event_counts": {role: dict(value) for role, value in counts.items()},
        "matched_texture_requests": matched,
        "unmatched_client_texture_requests": len(creations["client"]) - matched,
        "texture_parameter_mismatch_examples": mismatches,
        "failed_creation_examples": failures,
        "matched_uploads": matched_uploads,
        "sampled_upload_payload_difference_examples": payload_differences,
        "client_volume_pitch_error_examples": volume_errors,
        "critical_binding_examples": bindings,
        "backend_state_examples": states,
        "limits": limits,
        "normal_end_present": {role: counts[role]["END"] > 0 for role in counts},
        "evidence_limits": [
            "Snapshots are sampled; brief intermediate render states may be missed.",
            "Upload hashes cover at most the first 65536 bytes, not the entire large resource.",
            "Upload rate limits are independent; unmatched uploads do not prove transport loss.",
            "Volume pitch errors prove an API layout issue, not the user's visual root cause.",
            "No compatibility fallback or state replay is enabled.",
        ],
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("client", type=Path)
    parser.add_argument("host", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    result = json.dumps(analyze(args.client, args.host), ensure_ascii=False, indent=2) + "\n"
    if args.output:
        args.output.write_text(result, encoding="utf-8")
    else:
        print(result, end="")
