# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

param(
  [Parameter(Mandatory = $true)][string]$DxvkDll,
  [Parameter(Mandatory = $true)][string]$Dxvk32Dll,
  [string]$VcVarsVer = '14.29',
  [switch]$PatchOnly
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$projectVersion = (Get-Content (Join-Path $repoRoot 'VERSION') -Raw).Trim()
$patchHash = (Get-FileHash (Join-Path $repoRoot 'patches/l4d2-bridge.patch') -Algorithm SHA256).Hash.ToLower().Substring(0, 16)
$env:L4D2_BRIDGE_BUILD_ID = "l4d2-$projectVersion+$patchHash"
$dxvkPath = (Resolve-Path $DxvkDll).Path
function Invoke-Checked {
  param([string]$Program, [string[]]$Arguments)
  & $Program @Arguments
  if ($LASTEXITCODE -ne 0) { throw "$Program failed: $LASTEXITCODE" }
}
Invoke-Checked 'python' @("$PSScriptRoot/prepare_bridge.py")
$source = Join-Path $repoRoot '.deps/dxvk-remix'
Push-Location (Join-Path $source 'bridge')
try {
  # Each architecture gets a fresh PowerShell process and its own MSVC environment.
  foreach ($arch in @('x64', 'x86')) {
    $buildCommand = ". .\build_bridge.ps1; Build -Platform $arch -BuildFlavour debugoptimized -BuildSubDir _compDebugOptimized_$arch -VcVarsVer $VcVarsVer; exit `$LASTEXITCODE"
    Invoke-Checked 'powershell.exe' @('-NoProfile', '-Command', $buildCommand)
  }
  if ($Dxvk32Dll) {
    # A separate directory gives all utility code SERVER definitions instead of CLIENT.
    $buildCommand = ". .\build_common.ps1; SetupVS -Platform x86 -VcVarsVer $VcVarsVer; & meson setup _compDebugOptimized_x86_server --buildtype debugoptimized --backend ninja --debug -Dexperimental_x86_server=true; if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }; & meson compile -C _compDebugOptimized_x86_server; exit `$LASTEXITCODE"
    Invoke-Checked 'powershell.exe' @('-NoProfile', '-Command', $buildCommand)
  }
} finally { Pop-Location }
$packager = if ($projectVersion.Contains('-dev')) { 'package_development.py' } else { 'package_release.py' }
$packageArgs = @("$PSScriptRoot/$packager", '--source', $source, '--dxvk', $dxvkPath)
if ($Dxvk32Dll) { $packageArgs += @('--dxvk-x86', (Resolve-Path $Dxvk32Dll).Path) }
if ($PatchOnly) {
  if (!$projectVersion.Contains('-dev')) { throw 'PatchOnly requires a development version' }
  $packageArgs += '--patch-only'
}
if ($projectVersion.Contains('-dev')) {
  $plugin = Join-Path $repoRoot '.deps/l4n-plugin/L4D2BridgePlugin.dll'
  if (Test-Path $plugin) { $packageArgs += @('--plugin', $plugin) }
}
Invoke-Checked 'python' $packageArgs
