# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param(
    [string]$OutputDirectory = "",
    [string]$TestFixtureHeader = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
if (-not $OutputDirectory) { $OutputDirectory = Join-Path $repoRoot "dist/thinflex-tool" }
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$fixtureBuild = -not [string]::IsNullOrEmpty($TestFixtureHeader)
if ($fixtureBuild) {
    # Windows aliases trailing dots/spaces, and junctions can redirect an
    # apparently safe output into dist. Keep fixture destinations unambiguous.
    foreach ($segment in ($OutputDirectory -split '[\\/]')) {
        if ($segment -match '[. ]$') { throw "Test fixture output cannot use Windows path aliases." }
    }
    $ancestor = $OutputDirectory
    while ($ancestor) {
        if (Test-Path -LiteralPath $ancestor) {
            $item = Get-Item -LiteralPath $ancestor -Force
            if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                throw "Test fixture output cannot pass through a filesystem junction or symbolic link."
            }
        }
        $ancestor = [IO.Path]::GetDirectoryName($ancestor)
    }
    $distRoot = [IO.Path]::GetFullPath((Join-Path $repoRoot "dist"))
    if ($OutputDirectory.Equals($distRoot, [StringComparison]::OrdinalIgnoreCase) -or
        $OutputDirectory.StartsWith($distRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Test fixture output must not be placed under release dist."
    }
    $TestFixtureHeader = (Resolve-Path -LiteralPath $TestFixtureHeader).Path
}

# vcvarsall sets the x64 compiler, library and SDK paths for this process only.
if (-not (Get-Command cl.exe -ErrorAction SilentlyContinue)) {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio/Installer/vswhere.exe"
    if (-not (Test-Path -LiteralPath $vswhere)) { throw "MSVC x64 build tools are required (vswhere.exe was not found)." }
    $installation = & $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if ($LASTEXITCODE -ne 0 -or -not $installation) { throw "MSVC x64 build tools were not found." }
    $vcvars = Join-Path $installation "VC/Auxiliary/Build/vcvarsall.bat"
    # Supply cmd's raw command line directly. PowerShell 5.1 and 7 quote native
    # arguments differently, and can double the leading quote around Program Files.
    $processInfo = New-Object System.Diagnostics.ProcessStartInfo
    $processInfo.FileName = $env:ComSpec
    $processInfo.Arguments = '/d /u /s /c ""' + $vcvars + '" x64 >nul && set"'
    $processInfo.UseShellExecute = $false
    $processInfo.CreateNoWindow = $true
    $processInfo.RedirectStandardOutput = $true
    $processInfo.RedirectStandardError = $true
    $processInfo.StandardOutputEncoding = [Text.Encoding]::Unicode
    $processInfo.StandardErrorEncoding = [Text.Encoding]::Unicode
    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $processInfo
    try {
        [void]$process.Start()
        $outputTask = $process.StandardOutput.ReadToEndAsync()
        $errorTask = $process.StandardError.ReadToEndAsync()
        $process.WaitForExit()
        $environmentOutput = $outputTask.GetAwaiter().GetResult()
        $environmentError = $errorTask.GetAwaiter().GetResult()
        if ($process.ExitCode -ne 0) {
            throw "Could not initialize MSVC x64 environment (exit $($process.ExitCode)): $environmentError"
        }
        $environment = $environmentOutput -split '\r?\n'
    } finally {
        $process.Dispose()
    }
    foreach ($line in $environment) {
        $separator = $line.IndexOf('=')
        if ($separator -gt 0) {
            [Environment]::SetEnvironmentVariable($line.Substring(0, $separator), $line.Substring($separator + 1), 'Process')
        }
    }
}
if ($env:VSCMD_ARG_TGT_ARCH -and $env:VSCMD_ARG_TGT_ARCH -ne "x64") {
    throw "Use an x64 MSVC developer shell; the current target is $env:VSCMD_ARG_TGT_ARCH."
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
$exe = Join-Path $OutputDirectory "ThinFlexPatch.exe"
$object = Join-Path $OutputDirectory "thinflex_patch.obj"
$source = Join-Path $PSScriptRoot "native/thinflex_patch.cpp"
$arguments = @('/nologo', '/std:c++17', '/O2', '/MT', '/EHsc', '/W4', '/WX', '/utf-8', '/DNDEBUG', '/DUNICODE', '/D_UNICODE', "/Fo$object", "/Fe$exe")
if ($fixtureBuild) { $arguments += @('/DTHINFLEX_TESTING', "/FI$TestFixtureHeader") }
$arguments += @($source, '/link', '/MACHINE:X64', '/OPT:REF', '/OPT:ICF', '/INCREMENTAL:NO', 'bcrypt.lib')
# MSVC consumes CL/_CL_ implicitly. Ignore inherited flags so fixture macros or
# forced includes from another build cannot leak into the production binary.
$savedCl = [Environment]::GetEnvironmentVariable('CL', 'Process')
$savedClSuffix = [Environment]::GetEnvironmentVariable('_CL_', 'Process')
try {
    [Environment]::SetEnvironmentVariable('CL', $null, 'Process')
    [Environment]::SetEnvironmentVariable('_CL_', $null, 'Process')
    & cl.exe @arguments
    if ($LASTEXITCODE -ne 0) { throw "ThinFlex native compilation failed ($LASTEXITCODE)." }
} finally {
    [Environment]::SetEnvironmentVariable('CL', $savedCl, 'Process')
    [Environment]::SetEnvironmentVariable('_CL_', $savedClSuffix, 'Process')
}
if (-not (Test-Path -LiteralPath $exe)) { throw "Compiler did not create ThinFlexPatch.exe." }
Remove-Item -LiteralPath $object -ErrorAction SilentlyContinue
Write-Output "Built $exe"
