# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Extract both actual transports for same-machine native batch A/B."""
import json
import hashlib
from pathlib import Path
from generate_ipc_transport_test import generate, FILES, ROOT
from generate_buffer_contract_test import method
from prepare_ipc_baseline import prepare


def baseline(source,output):
    # Common OS adapters/disabled diagnostics come from the new fixture generator.
    generate(ROOT/'.deps/dxvk-remix',output)
    util=source/'bridge/src/util'
    hashes={}
    for name in FILES:
        if name=='data_ring_contract.h':continue
        text=(util/name).read_text(encoding='utf-8')
        hashes[name]=hashlib.sha256(text.encode()).hexdigest()
        if name=='util_ipcchannel.h':text=text.replace('#include "util_blockingcircularqueue.h"','')
        (output/name).write_text(text,encoding='utf-8')
    header=(util/'util_bridgecommand.h').read_text(encoding='utf-8')
    cpp=(util/'util_bridgecommand.cpp').read_text(encoding='utf-8')
    bridge=header[header.index('using namespace bridge_util;'):]
    bridge=bridge.replace('public:\n  static void init(','''public:
  static void install(WriterChannel* writer, ReaderChannel* reader) {
    s_pWriterChannel=writer;s_pReaderChannel=reader;s_cmdUID=0;
  }
  static void init(''',1)
    bodies=[]
    for marker in ('DECL_BRIDGE_FUNC(void, syncDataQueue,','DECL_BRIDGE_FUNC(Header, pop_front)',
                   'DECL_BRIDGE_FUNC(bridge_util::Result, waitForCommand,'):
        start,end=method(cpp,marker);bodies.append(cpp[start:end])
    prefix=cpp[cpp.index('namespace {'):cpp.index('DECL_BRIDGE_FUNC(void, init,')]
    definitions=cpp[cpp.index('#define DECL_COMMAND_FUNC'):]
    support=(ROOT/'tests/ipc_transport_support.h').read_text().replace('std::atomic<bool> gbBridgeRunning {true};','bool gbBridgeRunning=true;')
    server=(source/'bridge/src/server/main.cpp').read_text(encoding='utf-8')
    a=server.index('    *DeviceBridge::getReaderChannel().serverDataPos =');b=server.index('    const auto count = DeviceBridge::end_read_data();',a)
    complete='bool gOverwriteConditionAlreadyActive=false;\nvoid benchmarkComplete() {\n'+server[a:b]+'    DeviceBridge::end_read_data();\n}\n'
    complete=complete.replace('DeviceBridge::','Bridge<BridgeId::Device>::')
    generated='#define IPC_OLD_BASELINE\n'+support+'\n'+bridge+'\n'+prefix+'\n'+'\n'.join(bodies)+'\n'+definitions+'\n'+complete+'\n#include "ipc_performance_cases.cpp"\n'
    (output/'ipc_transport.cpp').write_text(generated,encoding='utf-8')
    hashes['util_bridgecommand.h']=hashlib.sha256(header.encode()).hexdigest()
    hashes['util_bridgecommand.cpp']=hashlib.sha256(cpp.encode()).hexdigest()
    hashes['server/main.cpp']=hashlib.sha256(server.encode()).hexdigest()
    (output/'source-manifest.json').write_text(json.dumps({'source_sha256':hashes,'scope':'actual old transport and exact Device consumption progress block'},indent=2)+'\n')

if __name__=='__main__':
    old=prepare()
    baseline(old,ROOT/'.deps/ipc-perf-A')
    generate(ROOT/'.deps/dxvk-remix',ROOT/'.deps/ipc-perf-B')
    p=ROOT/'.deps/ipc-perf-B/ipc_transport.cpp'
    p.write_text(p.read_text().replace('#include "ipc_transport_cases.cpp"','#include "ipc_performance_cases.cpp"'))
