# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Exercise production Client hook installation, DirectInput results and Query delegation."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def method(contents, marker):
    if contents.count(marker) != 1:
        raise ValueError(f'Unexpected method layout: {marker}')
    start = contents.index(marker)
    brace = contents.index('{', start)
    depth = 1
    end = brace + 1
    while depth and end < len(contents):
        depth += (contents[end] == '{') - (contents[end] == '}')
        end += 1
    if depth:
        raise ValueError('Unclosed production method')
    return start, end


def replace_once(contents, before, after):
    if contents.count(before) != 1:
        raise ValueError(f'Unexpected negative-control layout: {before}')
    return contents.replace(before, after, 1)


def generate(source, output, negative_control=None):
    client = source / 'bridge/src/client'
    di = (client / 'di_hook.cpp').read_text(encoding='utf-8')
    query = (client / 'd3d9_query.cpp').read_text(encoding='utf-8')
    pieces = []
    for marker in ['static void InputWinHooksAttach()', 'static void InputWinHooksDetach()']:
        start, end = method(di, marker)
        pieces.append(di[start:end])
    pieces.append('class DirectInput7Hook { public:')
    pieces.append('inline static Create OrigDirectInputCreateA = createA;')
    pieces.append('inline static Create OrigDirectInputCreateW = createW;')
    for marker in ['static void LogCreateResult(', 'static HRESULT WINAPI HookedDirectInputCreateA(',
                   'static HRESULT WINAPI HookedDirectInputCreateW(']:
        start, end = method(di, marker)
        pieces.append(di[start:end])
    pieces.append('};')
    for marker in ['ULONG Direct3DQuery9_LSS::AddRef()', 'ULONG Direct3DQuery9_LSS::Release()']:
        start, end = method(query, marker)
        pieces.append(query[start:end])
    production = '\n'.join(pieces)
    if negative_control == 'thread-hook':
        production = replace_once(
            production,
            'attachWinHook(WH_KEYBOARD,    HookedKeyboardProc),',
            'attachWinHook(WH_KEYBOARD,    HookedKeyboardProc),\n'
            '    attachWinHook(WH_KEYBOARD_LL, HookedLowLevelKeyboardProc),')
    elif negative_control == 'hook-error':
        production = replace_once(production,
            'const DWORD error = GetLastError();', 'const DWORD error = 0;')
    elif negative_control == 'null-unhook':
        production = replace_once(production,
            'if (hook) { UnhookWindowsHookEx(hook); }', 'UnhookWindowsHookEx(hook);')
    elif negative_control == 'directinput':
        for api in ('A', 'W'):
            production = replace_once(production,
                f'LogCreateResult("DirectInputCreate{api}", dwVersion, result);', '')
            production = replace_once(production,
                f'const HRESULT result = OrigDirectInputCreate{api}',
                'if (dwVersion != 0x0700) {\n'
                '      Logger::warn(format_string("Unsupported DirectInput version: %d.%d.",\n'
                '        dwVersion >> 8, dwVersion & 0xff));\n'
                '    }\n'
                f'    const HRESULT result = OrigDirectInputCreate{api}')
    elif negative_control == 'query':
        for name in ('AddRef', 'Release'):
            production = replace_once(production,
                f'ULONG Direct3DQuery9_LSS::{name}() {{\n  LogFunctionCall();',
                f'ULONG Direct3DQuery9_LSS::{name}() {{\n  LogMissingFunctionCall();')
    fixture = (ROOT / 'tests/input_hooks_test.cpp').read_text(encoding='utf-8')
    marker = '// PRODUCTION_METHODS'
    if fixture.count(marker) != 1:
        raise ValueError('Unexpected input hook fixture layout')
    output.parent.mkdir(parents=True, exist_ok=True)
    if negative_control == 'thread-hook':
        fixture = fixture.replace('#include <cstdarg>',
            '#define OLD_THREAD_HOOK\n#include <cstdarg>', 1)
    output.write_text(fixture.replace(marker, production), encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / '.deps/dxvk-remix')
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--negative-control', choices=(
        'thread-hook', 'hook-error', 'null-unhook', 'directinput', 'query'))
    args = parser.parse_args()
    generate(args.source, args.output, args.negative_control)
