# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([Parameter(Mandatory = $true)][string]$GameDirectory)
$ErrorActionPreference = 'Stop'
$packageRoot = if ((Test-Path (Join-Path $PSScriptRoot 'bin/d3d9.dll')) -or (Test-Path (Join-Path $PSScriptRoot 'bin/dxvk_d3d9.dll'))) { $PSScriptRoot } else { Split-Path $PSScriptRoot -Parent }
$clientNames = @('bin/d3d9.dll', 'bin/dxvk_d3d9.dll')
$sourceClients = @($clientNames | Where-Object { Test-Path -LiteralPath (Join-Path $packageRoot $_) })
$targetClients = @($clientNames | Where-Object { Test-Path -LiteralPath (Join-Path $GameDirectory $_) })
if ($sourceClients.Count -ne 1) { throw 'The package must contain exactly one Client filename.' }
if ($targetClients.Count -ne 1) { throw 'Expected exactly one installed Client (d3d9.dll or dxvk_d3d9.dll). Resolve missing or ambiguous DLLs before enabling diagnostics.' }
$client = $sourceClients[0]
if (!(Test-Path (Join-Path $GameDirectory 'left4dead2.exe'))) { throw 'Select the Left 4 Dead 2 game directory containing left4dead2.exe.' }
if (Get-Process -Name left4dead2,L4D2Bridge32,L4D2Bridge64 -ErrorAction SilentlyContinue) { throw 'Exit the game and Bridge Host before installing.' }
$files = @($client, 'bin/.l4d2bridge/L4D2Bridge32.exe', 'bin/.l4d2bridge/L4D2Bridge64.exe')
$targets = @{}
foreach ($file in $files) { $targets[$file] = $file }
$targets[$client] = $targetClients[0]
foreach ($file in $files) {
  if (!(Test-Path (Join-Path $packageRoot $file))) { throw "Matched package file missing: $file" }
}
$manifest = Get-Content (Join-Path $packageRoot 'SHA256.json') -Raw -Encoding UTF8 | ConvertFrom-Json
foreach ($file in $files) {
  $expected = $manifest.PSObject.Properties[$file].Value
  if (!$expected -or (Get-FileHash (Join-Path $packageRoot $file) -Algorithm SHA256).Hash.ToLower() -ne $expected) { throw "Package checksum mismatch: $file" }
}
$config = Join-Path $GameDirectory 'bin/.l4d2bridge/bridge.conf'
if (!(Test-Path $config)) { throw 'Install the normal Bridge package first; this update preserves its backend and configuration.' }
$backup = Join-Path $GameDirectory ('bin/.l4d2bridge/backups/color-diagnostics-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
New-Item -ItemType Directory -Path $backup | Out-Null
Copy-Item $config (Join-Path $backup 'bridge.conf')
foreach ($file in $files) {
  $target = Join-Path $GameDirectory $targets[$file]
  if (Test-Path $target) { Copy-Item $target (Join-Path $backup (Split-Path $targets[$file] -Leaf)) }
}
foreach ($file in $files) { Copy-Item (Join-Path $packageRoot $file) (Join-Path $GameDirectory $targets[$file]) -Force }
$content = [System.IO.File]::ReadAllText($config, [System.Text.Encoding]::UTF8)
# Remove earlier entries for these four diagnostic settings before appending.
$content = [regex]::Replace($content, '(?m)^\s*(client|server)\.(colorDiagnostics|colorSnapshotMs)\s*=.*(?:\r?\n|$)', '')
$content = $content.TrimEnd() + "`r`n`r`nclient.colorDiagnostics = True`r`nserver.colorDiagnostics = True`r`nclient.colorSnapshotMs = 5000`r`nserver.colorSnapshotMs = 5000`r`n"
[System.IO.File]::WriteAllText($config, $content, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Installed matched Bridge binaries and enabled color diagnostics. Backup: $backup"
Write-Host 'Keep the existing Steam launch options. Test local single-player, then a server, and exit normally.'
