# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

"""Validate PE architectures before assembling a non-deploying test package."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import struct

ROOT = Path(__file__).resolve().parents[1]


def machine(path):
    data = path.read_bytes()
    if len(data) < 64 or data[:2] != b"MZ":
        raise ValueError(f"Not a PE file: {path}")
    offset = struct.unpack_from("<I", data, 60)[0]
    if data[offset:offset + 4] != b"PE\0\0":
        raise ValueError(f"Invalid PE signature: {path}")
    return struct.unpack_from("<H", data, offset + 4)[0]


def package(source, dxvk, output):
    client_output = output.parent / "l4d2-client-only"
    host_output = output.parent / "l4d2-host-only"
    cpu_output = output.parent / "l4d2-cpu-update"
    inputs = {
        "bin/dxvk_d3d9.dll": (source / "bridge/_compDebugOptimized_x86/src/client/d3d9.dll", 0x14c),
        "bin/.l4d2bridge/L4D2Bridge64.exe": (source / "bridge/_compDebugOptimized_x64/src/server/L4D2Bridge64.exe", 0x8664),
        "bin/.l4d2bridge/d3d9vk_x64.dll": (dxvk, 0x8664),
    }
    # Validate all inputs before creating output. Never deploy into a game directory.
    for path, expected in inputs.values():
        if machine(path) != expected:
            raise ValueError(f"Wrong architecture: {path}")
    for destination in (output, client_output, host_output, cpu_output):
        if destination.exists():
            raise FileExistsError(f"Output already exists; preserve or move it first: {destination}")
    output.mkdir(parents=True, exist_ok=False)
    hashes = {}
    for relative, (path, _) in inputs.items():
        destination = output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, destination)
        hashes[relative] = hashlib.sha256(destination.read_bytes()).hexdigest()
    shutil.copy2(ROOT / "config/bridge.conf", output / "bin/.l4d2bridge/bridge.conf")
    shutil.copy2(ROOT / "docs/TESTING.md", output / "TESTING.md")
    shutil.copy2(ROOT / "docs/MEMORY-DIAGNOSTICS.md", output / "MEMORY-DIAGNOSTICS.md")
    shutil.copy2(ROOT / "docs/FIRST-GAME-VALIDATION.md", output / "FIRST-GAME-VALIDATION.md")
    for filename in ("README.md", "VERSION", "LICENSE", "THIRD_PARTY.md"):
        shutil.copy2(ROOT / filename, output / filename)
    # Preserve the README's relative documentation and patch links in the package.
    shutil.copytree(ROOT / "docs", output / "docs")
    shutil.copytree(ROOT / "patches", output / "patches")
    licenses = output / "licenses"
    licenses.mkdir()
    shutil.copy2(source / "bridge/LICENSE-MIT", licenses / "Bridge-MIT.txt")
    shutil.copy2(source / "bridge/ThirdPartyLicenses.txt", licenses / "Bridge-third-party.txt")
    shutil.copy2(ROOT / "licenses/DXVK-LICENSE.txt", licenses / "DXVK-LICENSE.txt")
    (output / "SHA256.json").write_text(json.dumps(hashes, indent=2) + "\n")
    (client_output / "bin").mkdir(parents=True, exist_ok=False)
    shutil.copy2(output / "bin/dxvk_d3d9.dll", client_output / "bin/dxvk_d3d9.dll")
    shutil.copy2(ROOT / "docs/MEMORY-DIAGNOSTICS.md", client_output / "MEMORY-DIAGNOSTICS.md")
    (client_output / "licenses").mkdir()
    for filename in ("Bridge-MIT.txt", "Bridge-third-party.txt"):
        shutil.copy2(licenses / filename, client_output / "licenses" / filename)
    shutil.copy2(licenses / "DXVK-LICENSE.txt", client_output / "licenses/DXVK-LICENSE.txt")
    for filename in ("VERSION", "LICENSE", "THIRD_PARTY.md"):
        shutil.copy2(ROOT / filename, client_output / filename)
    (client_output / "SHA256.json").write_text(json.dumps({
        "bin/dxvk_d3d9.dll": hashes["bin/dxvk_d3d9.dll"],
    }, indent=2) + "\n")
    host_relative = "bin/.l4d2bridge/L4D2Bridge64.exe"
    (host_output / "bin/.l4d2bridge").mkdir(parents=True, exist_ok=False)
    shutil.copy2(output / host_relative, host_output / host_relative)
    shutil.copy2(ROOT / "docs/HOST-MEMORY-DIAGNOSTICS.md", host_output / "HOST-MEMORY-DIAGNOSTICS.md")
    (host_output / "licenses").mkdir()
    for filename in ("Bridge-MIT.txt", "Bridge-third-party.txt", "DXVK-LICENSE.txt"):
        shutil.copy2(licenses / filename, host_output / "licenses" / filename)
    for filename in ("VERSION", "LICENSE", "THIRD_PARTY.md"):
        shutil.copy2(ROOT / filename, host_output / filename)
    (host_output / "SHA256.json").write_text(json.dumps({
        host_relative: hashes[host_relative],
    }, indent=2) + "\n")
    cpu_hashes = {}
    for relative in ("bin/dxvk_d3d9.dll", host_relative):
        destination = cpu_output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(output / relative, destination)
        cpu_hashes[relative] = hashes[relative]
    shutil.copy2(ROOT / "docs/CPU-QUEUE-TEST.md", cpu_output / "CPU-QUEUE-TEST.md")
    shutil.copytree(licenses, cpu_output / "licenses")
    for filename in ("VERSION", "LICENSE", "THIRD_PARTY.md"):
        shutil.copy2(ROOT / filename, cpu_output / filename)
    (cpu_output / "SHA256.json").write_text(json.dumps(cpu_hashes, indent=2) + "\n")
    print(f"L4D2 D3D9 Bridge v{(ROOT / 'VERSION').read_text().strip()}: {output}")
    print(f"Client-only update: {client_output}; preserves the installed host and DXVK")
    print(f"Host diagnostics update: {host_output}; preserves the installed client, DXVK and configuration")
    print(f"CPU queue update: {cpu_output}; update both bridge binaries together")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--dxvk", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=ROOT / "dist/l4d2-bridge")
    args = parser.parse_args()
    package(args.source.resolve(), args.dxvk.resolve(), args.output.resolve())
