# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Extract the three production Host branches without duplicating their logic."""
import argparse
from pathlib import Path

KINDS = ("GetSwapChain", "Reset", "ResetEx")


def prepare(source, output, negative_control=None):
    host = (source / "bridge/src/server/main.cpp").read_text(encoding="utf-8")
    notices = host[:host.index("#include")]
    cases = []
    for kind in KINDS:
        marker = f"      case IDirect3DDevice9Ex_{kind}:\n"
        if host.count(marker) != 1:
            raise ValueError(f"Expected one Host branch: {kind}")
        start = host.index(marker)
        case = host[start:host.index("\n      }", start) + 8]
        if negative_control == kind:
            release = "        if (pSwapChain) { pSwapChain->Release(); }"
            if case.count(release) != 1:
                raise ValueError(f"Cannot restore old temporary reference handling: {kind}")
            old = "" if kind == "GetSwapChain" else "        pSwapChain->Release();"
            case = case.replace(release, old)
        cases.append(case)
    macro_start = host.index("#define SEND_OPTIONAL_SERVER_RESPONSE(")
    response_macro = host[macro_start:host.index("\n\n", macro_start)]
    output.mkdir(parents=True, exist_ok=True)
    for name, contents in (("device_reset_lifetime_host.h", "\n".join(cases)),
                           ("device_reset_lifetime_response.h", response_macro)):
        (output / name).write_text(notices + contents + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--negative-control", choices=KINDS)
    args = parser.parse_args()
    prepare(args.source, args.output, args.negative_control)
