# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Extract actual resource lifecycle, buffer locking and Host dispatch for tests."""
import argparse
import re
from pathlib import Path

KINDS = ("VertexBuffer", "IndexBuffer", "RenderTarget", "DepthStencilSurface",
         "OffscreenPlainSurface", "RenderTargetEx", "OffscreenPlainSurfaceEx", "DepthStencilSurfaceEx")
NEGATIVE_CONTROLS = (*KINDS, "offset", "policy", "host")


def function(text, signature):
    if text.count(signature) != 1:
        raise ValueError(f"Expected one function: {signature}")
    start = text.index(signature)
    return text[start:text.index("\n}\n", start) + 3]


def prepare(source, output, negative_control=None):
    client = source / "bridge/src/client"
    device = (client / "d3d9_device.cpp").read_text(encoding="utf-8")
    notices = device[:device.index('#include "pch.h"')]
    methods, declarations, backend, dispatcher, host_cases = [], [], [], [], []
    host = (source / "bridge/src/server/main.cpp").read_text(encoding="utf-8")
    for kind in KINDS:
        create = function(device, f"HRESULT Direct3DDevice9Ex_LSS<EnableSync>::Create{kind}(")
        signature = create[:create.index(" {")].replace("Direct3DDevice9Ex_LSS<EnableSync>::", "")
        declarations.append("  " + signature + ";")
        parameters = signature[signature.index("(") + 1:-1].split(", ")
        names = [re.search(r"(\w+)$", parameter).group(1) for parameter in parameters]
        output_name = next(name for name in names if name.startswith("pp"))
        arguments = [name for name in names if name not in (output_name, "pSharedHandle")]
        backend.append("  " + signature + " {\n    (void)pSharedHandle;\n    return createBackend({" +
                       ", ".join(f"static_cast<uint64_t>({name})" for name in arguments) +
                       "}, " + output_name + ");\n  }\n")
        values = {"Length": "dimension", "Width": "dimension", "Height": "8", "Usage": "D3DUSAGE_DYNAMIC",
                  "FVF": "0", "Format": "D3DFMT_INDEX16" if kind == "IndexBuffer" else "D3DFMT_A8R8G8B8",
                  "Pool": "D3DPOOL_DEFAULT", "MultiSample": "D3DMULTISAMPLE_NONE", "MultisampleQuality": "0",
                  "Lockable": "TRUE", "Discard": "FALSE", "pSharedHandle": "sharedHandle",
                  "ppVertexBuffer": "output ? &output->vertex : nullptr", "ppIndexBuffer": "output ? &output->index : nullptr",
                  "ppSurface": "output ? &output->surface : nullptr"}
        dispatcher.append(f"    case Kind::{kind}: return device.Create{kind}(" + ", ".join(values[name] for name in names) + ");")
        if negative_control == kind:
            marker = "  // NV-DXVK start: Failed creation returns a null output and releases its client wrapper."
            if create.count(marker) != 1:
                raise ValueError(f"Cannot restore original failure path: {kind}")
            create = create[:create.index(marker)] + f'  WAIT_FOR_OPTIONAL_CREATE_FUNCTION_SERVER_RESPONSE("Create{kind}()", D3DERR_INVALIDCALL, currentUID);\n}}\n'
        methods.append("template<bool EnableSync>\n" + create)
        start = host.index(f"      case IDirect3DDevice9Ex_Create{kind}:\n")
        case = host[start:host.index("\n      }", start) + 8]
        if negative_control == "host" and kind == "VertexBuffer":
            marker = "        // NV-DXVK start: Forward recoverable creation failures to the client."
            begin = case.index(marker)
            end = case.index("        // NV-DXVK end", begin) + len("        // NV-DXVK end")
            case = case[:begin] + "        assert(SUCCEEDED(hresult));" + case[end:]
        host_cases.append(case)
    wrappers = []
    for kind, stem in (("VertexBuffer", "d3d9_vertexbuffer"), ("IndexBuffer", "d3d9_indexbuffer"), ("Surface", "d3d9_surface")):
        name = f"Direct3D{kind}9_LSS"
        header = (client / f"{stem}.h").read_text(encoding="utf-8")
        implementation = (client / f"{stem}.cpp").read_text(encoding="utf-8")
        fields = re.findall(r"^  bool m_serverCreated = [^;]+;", header, re.MULTILINE)
        cancellation = re.findall(r"^  void cancelServerCreation\(\) \{[^\n]+\}", header, re.MULTILINE)
        if len(fields) != 1 or len(cancellation) != 1:
            raise ValueError(f"Creation state changed: {stem}")
        if kind == "Surface":
            base = "Direct3DResource9_LSS<IDirect3DSurface9>"
            data = """  const D3DSURFACE_DESC m_desc;
  const bool m_bUseSharedHeap = false;
  SharedHeap::AllocId m_bufferId = SharedHeap::kInvalidId;
  PagefileShadow m_shadow;
  bool m_isBackBuffer;
  std::unique_ptr<l4d2_residency::Entry> m_residency;
  std::shared_ptr<l4d2_retention::Parent> m_retention;
  uint32_t m_readbackMip = 0;
  void initializeShadowDiagnostics();
"""
            constructor = "  Direct3DSurface9_LSS(BaseDirect3DDevice9Ex_LSS*, const D3DSURFACE_DESC&, bool = false, l4d2_control::Category = l4d2_control::Category::IndependentSurface);\n  ~Direct3DSurface9_LSS() override;"
            methods.append(function(implementation, "Direct3DSurface9_LSS::Direct3DSurface9_LSS("))
            methods.append(function(implementation, "void Direct3DSurface9_LSS::initializeShadowDiagnostics()"))
            methods.append(function(implementation, "Direct3DSurface9_LSS::~Direct3DSurface9_LSS()"))
        else:
            base = f"LockableBuffer<IDirect3D{kind}9>"
            data = ""
            start = header.index(f"  {name}(BaseDirect3DDevice9Ex_LSS*")
            constructor = header[start:header.index("\n  }", start) + 4]
            constructor += f"\n  using {base}::lock;\n  using {base}::unlock;"
        wrappers.append(f"class {name}: public {base} {{\n  void onDestroy() override;\n{fields[0]}\n{data}public:\n{cancellation[0]}\n{constructor}\n  ULONG Release() override;\n}};\n")
        methods.append(function(implementation, f"ULONG {name}::Release()"))
        methods.append(function(implementation, f"void {name}::onDestroy()"))
    lockable = (client / "lockable_buffer.h").read_text(encoding="utf-8")
    lockable = lockable[lockable.index("template <typename T>"):]
    if negative_control == "offset":
        start = lockable.index("    // NV-DXVK start: Validate the offset before forming pointers or subtracting it.")
        end = lockable.index("    // NV-DXVK end", start) + len("    // NV-DXVK end")
        lockable = lockable[:start] + lockable[end:]
    elif negative_control == "policy":
        if lockable.count("m_bUseSharedHeap(getSharedHeapPolicy(desc))") != 1:
            raise ValueError("Cannot restore uninitialized policy descriptor")
        lockable = lockable.replace("m_bUseSharedHeap(getSharedHeapPolicy(desc))", "m_bUseSharedHeap(getSharedHeapPolicy(m_desc))")
    base = (client / "base.h").read_text(encoding="utf-8")
    start = base.index("  STDMETHOD_(ULONG, Release)(THIS) {", base.index("class D3DBase:"))
    release = base[start:base.index("\n  }", start) + 4]
    release = release.replace("STDMETHOD_(ULONG, Release)(THIS)", "ULONG Release() override")
    macros = (source / "bridge/src/util/util_bridgecommand.h").read_text(encoding="utf-8")
    macros = macros[macros.index("#define WAIT_FOR_SERVER_RESPONSE("):macros.index("using namespace bridge_util;")]
    start = host.index("#define SEND_OPTIONAL_CREATE_FUNCTION_SERVER_RESPONSE(")
    server_macro = host[start:host.index("\n\n", start)]
    output.mkdir(parents=True, exist_ok=True)
    artifacts = {
        "resource_release.h": release,
        "resource_lockable.h": lockable,
        "resource_wrappers.h": "\n".join(wrappers),
        "resource_methods.h": macros + "\n".join(methods),
        "resource_declarations.h": "\n".join(declarations),
        "resource_backend.h": "\n".join(backend),
        "resource_dispatch.h": "\n".join(dispatcher),
        "resource_host.h": "\n".join(host_cases),
        "resource_server_macro.h": server_macro,
    }
    for name, content in artifacts.items():
        (output / name).write_text(notices + content + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--negative-control", choices=NEGATIVE_CONTROLS)
    args = parser.parse_args()
    prepare(args.source, args.output, args.negative_control)
