# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Attach already verified experimental ZIPs to their matching release draft."""
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import urllib.request
import zipfile

from separate_l4n_release import separate


def api(repository, path):
    return json.loads(subprocess.check_output(
        ['gh', 'api', f'repos/{repository}/{path}'], text=True))


def publish():
    root = Path(__file__).resolve().parents[1]
    version = (root / 'VERSION').read_text().strip()
    if not re.fullmatch(r'\d+\.\d+\.\d+-dev\.\d+', version):
        raise ValueError('Only explicitly versioned development prereleases are supported')
    repository = os.environ['L4D2_PUBLISH_REPOSITORY']
    zip_commit = os.environ['L4D2_ZIP_COMMIT']
    if not re.fullmatch(r'[0-9a-f]{40}', zip_commit):
        raise ValueError('The ZIP source must be an immutable Git commit')
    checksums = json.loads(os.environ['L4D2_ZIP_CHECKSUMS'])
    names = {f'l4d2-bridge-v{version}.zip', f'l4d2-bridge-patch-v{version}.zip'}
    if set(checksums) != names or not all(re.fullmatch(r'[0-9a-f]{64}', value) for value in checksums.values()):
        raise ValueError('Supply exactly the full and matched-update ZIP checksums')
    tag = 'v' + version
    releases = api(repository, 'releases?per_page=100')
    matches = [release for release in releases if release['tag_name'] == tag]
    if len(matches) != 1 or not matches[0]['draft'] or not matches[0]['prerelease']:
        raise ValueError('The matching experimental release must already exist as a draft')
    release = matches[0]
    if any(asset['name'] not in names | {f'l4d2-bridge-l4n-v{version}.zip', 'SHA256SUMS.txt'} for asset in release['assets']):
        raise ValueError('Refusing to alter a draft with unrelated assets')
    reference = api(repository, f'git/ref/tags/{tag}')['object']
    if reference['type'] == 'tag':
        reference = api(repository, 'git/tags/' + reference['sha'])['object']
    if reference['type'] != 'commit':
        raise ValueError('The version tag must resolve to a commit')
    tagged_commit = reference['sha']
    output = root / 'dist/publish-existing-prerelease'
    output.mkdir(parents=True, exist_ok=True)
    for name, expected in sorted(checksums.items()):
        destination = output / name
        url = f'https://raw.githubusercontent.com/{repository}/{zip_commit}/{name}'
        with urllib.request.urlopen(url, timeout=60) as response:
            data = response.read()
        if hashlib.sha256(data).hexdigest() != expected:
            raise ValueError('ZIP checksum mismatch: ' + name)
        destination.write_bytes(data)
        with zipfile.ZipFile(destination) as archive:
            prefix = name[:-4]
            receipt = json.loads(archive.read(prefix + '/BUILD-INFO.json'))
            if receipt['version'] != version or receipt['source_commit'] != tagged_commit:
                raise ValueError('Package source/version does not match the release tag')
            manifest = json.loads(archive.read(prefix + '/SHA256.json'))
            for relative, digest in manifest.items():
                if hashlib.sha256(archive.read(prefix + '/' + relative)).hexdigest() != digest:
                    raise ValueError('Binary checksum mismatch: ' + relative)
            ci = receipt['build_environment']['ci']
            run = api(repository, f'actions/runs/{ci["id"]}')
            if run['conclusion'] != 'success' or run['head_sha'] != tagged_commit:
                raise ValueError('The package must come from successful native CI for this tag')
    # ZIP-only downloads can bundle L4N; Release assets always separate it.
    artifacts = separate([output / name for name in sorted(names)], output / 'release', version)
    checksum_file = output / 'release/SHA256SUMS.txt'
    checksum_file.write_text(''.join(f'{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.name}\n' for path in sorted(artifacts)))
    subprocess.run(['gh', 'release', 'upload', tag, '--repo', repository, '--clobber',
        *[str(path) for path in artifacts], str(checksum_file)], check=True)
    uploaded = api(repository, f'releases/{release["id"]}')
    expected_assets = {path.name: path for path in [*artifacts, checksum_file]}
    if len(uploaded['assets']) != len(expected_assets):
        raise ValueError('The complete independent-component release was not uploaded')
    for asset in uploaded['assets']:
        file = expected_assets[asset['name']]
        if asset['state'] != 'uploaded' or asset['size'] != file.stat().st_size:
            raise ValueError('Incomplete release asset: ' + asset['name'])
        if asset.get('digest') and asset['digest'] != 'sha256:' + hashlib.sha256(file.read_bytes()).hexdigest():
            raise ValueError('Server release checksum mismatch: ' + asset['name'])
    subprocess.run(['gh', 'release', 'edit', tag, '--repo', repository,
        '--draft=false', '--prerelease', '--latest=false'], check=True)
    print('Published verified experimental prerelease:', tag)


if __name__ == '__main__':
    publish()
