# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Make Release ZIPs with an independent optional L4N component."""
import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import zipfile


def separate(inputs, output, version):
    prepared = []
    plugin = None
    identity = None
    for source in inputs:
        source = Path(source)
        prefix = source.stem
        with zipfile.ZipFile(source) as archive:
            files = {}
            for entry in archive.infolist():
                if entry.is_dir():
                    continue
                path = PurePosixPath(entry.filename)
                if path.is_absolute() or '..' in path.parts or not path.parts or path.parts[0] != prefix:
                    raise ValueError('Invalid package member: ' + entry.filename)
                relative = str(path.relative_to(prefix))
                if relative in files:
                    raise ValueError('Duplicate package member: ' + relative)
                files[relative] = archive.read(entry)
        receipt = json.loads(files['BUILD-INFO.json'])
        current = (receipt['version'], receipt['build_id'], receipt['source_commit'])
        if current[0] != version or (identity is not None and current != identity):
            raise ValueError('Release inputs must have matching source/version/build identity')
        identity = current
        hashes = json.loads(files['SHA256.json'])
        for name, digest in hashes.items():
            if hashlib.sha256(files[name]).hexdigest() != digest:
                raise ValueError('Package hash mismatch: ' + name)
        for name in list(files):
            if PurePosixPath(name).name != 'L4D2BridgePlugin.dll':
                continue
            if plugin is not None and plugin != files[name]:
                raise ValueError('Mismatched L4N plugins in Release inputs')
            plugin = files.pop(name)
            hashes.pop(name, None)
        prepared.append((source.name, files, receipt, hashes))
    if not prepared:
        raise ValueError('Supply the prepared full and/or patch packages')
    plugin_name = f'l4d2-bridge-l4n-v{version}.zip'
    plugin_files = None
    if plugin is not None:
        first = prepared[0][1]
        plugin_files = {'bin/neko/plugins/L4D2BridgePlugin.dll': plugin}
        for name in ['LICENSE', 'THIRD_PARTY.md', 'docs/L4N-BRIDGE-CONTROLS.md']:
            if name in first:
                plugin_files[name] = first[name]
        plugin_files['README.md'] = (
            f'# Optional L4N Bridge controls {version}\n\n'
            'Close L4D2, then merge bin/neko/plugins into the game directory. '
            'Requires L4N SDK v2 HUD support. Bridge works without this plugin. '
            'This package does not install Bridge, DXVK or ReShade. '
            'Host/Presenter changes require a full game restart.\n').encode()
        hashes = {'bin/neko/plugins/L4D2BridgePlugin.dll': hashlib.sha256(plugin).hexdigest()}
        receipt = dict(prepared[0][2], kind='optional-l4n-plugin', optional_plugin=True,
                       distribution='release', files=hashes)
        plugin_files['SHA256.json'] = (json.dumps(hashes, indent=2) + '\n').encode()
        plugin_files['BUILD-INFO.json'] = (json.dumps(receipt, indent=2) + '\n').encode()
    destinations = [Path(output) / item[0] for item in prepared]
    if plugin_files is not None:
        destinations.append(Path(output) / plugin_name)
    if any(path.exists() for path in destinations):
        raise FileExistsError('Release output already exists; preserve it before repackaging')
    Path(output).mkdir(parents=True, exist_ok=True)

    def write(path, files):
        with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
            for name, data in sorted(files.items()):
                archive.writestr(path.stem + '/' + name, data)

    for index, (_, files, receipt, hashes) in enumerate(prepared):
        receipt.update(optional_plugin=False, distribution='release', files=hashes)
        if plugin_files is not None:
            receipt['separate_plugin_asset'] = plugin_name
        files['BUILD-INFO.json'] = (json.dumps(receipt, indent=2) + '\n').encode()
        files['SHA256.json'] = (json.dumps(hashes, indent=2) + '\n').encode()
        write(destinations[index], files)
    if plugin_files is not None:
        write(destinations[-1], plugin_files)
    return destinations


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--version', required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('inputs', nargs='+', type=Path)
    args = parser.parse_args()
    for result in separate(args.inputs, args.output, args.version):
        print(result)
