# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param(
  [ValidateSet('x86','x64')][string]$CompileArchitecture,
  [string]$SourceDirectory = (Join-Path (Split-Path $PSScriptRoot -Parent) '.deps/dxvk-remix'),
  [string]$OutputDirectory = (Join-Path (Split-Path $PSScriptRoot -Parent) '.deps/input-hooks-test')
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$SourceDirectory = (Resolve-Path -LiteralPath $SourceDirectory).Path
New-Item -ItemType Directory -Force $OutputDirectory | Out-Null
$OutputDirectory = (Resolve-Path -LiteralPath $OutputDirectory).Path
if (!$CompileArchitecture) {
  foreach ($architecture in @('x86','x64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -CompileArchitecture $architecture -SourceDirectory $SourceDirectory -OutputDirectory $OutputDirectory
    if ($LASTEXITCODE -ne 0) { throw "Client input/logging tests failed: $architecture" }
  }
  exit 0
}
. (Join-Path $SourceDirectory 'bridge/build_common.ps1')
SetupVS -Platform $CompileArchitecture -VcVarsVer '14.29'
$controls = @{
  'thread-hook' = 'Unexpected global hook or installation arguments'
  'hook-error' = 'Hook error not captured immediately'
  'null-unhook' = 'Unhook called with null handle'
  'directinput' = 'Quiet success formatted a log'
  'query' = 'Query lifecycle delegation or log classification changed'
}
foreach ($variant in @('current','thread-hook','hook-error','null-unhook','directinput','query')) {
  $testDir = Join-Path $OutputDirectory "$variant-$CompileArchitecture"
  New-Item -ItemType Directory -Force $testDir | Out-Null
  $generated = Join-Path $testDir 'actual_input_hooks.cpp'
  $extractArgs = @("$PSScriptRoot/generate_input_hooks_test.py", '--source', $SourceDirectory, '--output', $generated)
  if ($variant -ne 'current') { $extractArgs += @('--negative-control', $variant) }
  & python @extractArgs
  if ($LASTEXITCODE -ne 0) { throw "Input hook source generation failed: $variant" }
  Push-Location $testDir
  try {
    & cl.exe /nologo /std:c++17 /EHsc /O2 /MT /W4 /WX $generated /Fe:input-hooks-test.exe
    if ($LASTEXITCODE -ne 0) { throw "Input hook regression compilation failed: $variant" }
    # Capture expected stderr failures without PowerShell 5.1 converting them
    # into terminating NativeCommandError records under ErrorActionPreference.
    $testProcess = [System.Diagnostics.Process]::new()
    $testProcess.StartInfo.FileName = Join-Path $testDir 'input-hooks-test.exe'
    $testProcess.StartInfo.UseShellExecute = $false
    $testProcess.StartInfo.CreateNoWindow = $true
    $testProcess.StartInfo.RedirectStandardOutput = $true
    $testProcess.StartInfo.RedirectStandardError = $true
    try {
      if (!$testProcess.Start()) { throw "Failed to start input hook test: $variant" }
      $testOutput = $testProcess.StandardOutput.ReadToEnd() + $testProcess.StandardError.ReadToEnd()
      $testProcess.WaitForExit()
      $testExit = $testProcess.ExitCode
    } finally { $testProcess.Dispose() }
    $testOutput | Write-Host
    if ($variant -eq 'current') {
      if ($testExit -ne 0) { throw 'Input hook/log classification regression failed' }
    } elseif ($testExit -ne 1 -or ($testOutput -join "`n") -notmatch [regex]::Escape($controls[$variant])) {
      throw "Input hook regression did not detect the old defect: $variant"
    }
  } finally { Pop-Location }
}
