# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
. (Join-Path $source 'bridge/build_common.ps1')
$output = Join-Path $repoRoot '.deps/pageblock-gc-test'
New-Item -ItemType Directory -Force $output | Out-Null
Push-Location $output
try {
  foreach ($arch in @('x86', 'x64')) {
    SetupVS -Platform $arch -VcVarsVer '14.29'
    & cl.exe /nologo /std:c++17 /EHsc /W4 /WX "/I$source/bridge/src/server" "/I$source/bridge/src/client" "/I$source/bridge/src/util" "$repoRoot/tests/pageblock_residency.cpp" "/Fe:pageblock-$arch.exe" /link bcrypt.lib
    if ($LASTEXITCODE -ne 0) { throw "PageBlock GC $arch compilation failed" }
    & ".\pageblock-$arch.exe"
    if ($LASTEXITCODE -ne 0) { throw "PageBlock GC $arch tests failed: $LASTEXITCODE" }
  }
  SetupVS -Platform x86 -VcVarsVer '14.29'
  & cl.exe /nologo /std:c++17 /EHsc /W4 /WX /wd4100 "/I$source/bridge/src/util" "$repoRoot/tests/l4n_plugin.cpp" /Fe:l4n-plugin-test.exe /link '/EXPORT:L4D2BridgePageBlockControl=_L4D2BridgePageBlockControl@8'
  if ($LASTEXITCODE -ne 0) { throw 'L4N v2 test compilation failed' }
  & ./l4n-plugin-test.exe (Join-Path $repoRoot '.deps/l4n-plugin/L4D2BridgePlugin.dll')
  if ($LASTEXITCODE -ne 0) { throw "L4N v2 callback tests failed: $LASTEXITCODE" }
} finally { Pop-Location }
