# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('x86', 'x64')][string]$Platform)
$ErrorActionPreference = 'Stop'
if (!$Platform) {
  foreach ($arch in @('x86', 'x64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -Platform $arch
    if ($LASTEXITCODE -ne 0) { throw "Reset contract test failed for $arch" }
  }
  exit 0
}
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
. (Join-Path $source 'bridge/build_common.ps1')
SetupVS -Platform $Platform -VcVarsVer '14.29'
$output = Join-Path $repoRoot ".deps/reset-test-$Platform"
New-Item -ItemType Directory -Force $output | Out-Null
Push-Location $output
try {
  & cl.exe /nologo /std:c++17 /EHsc /W4 /WX /DNOMINMAX "/I$source/bridge/src/util" "/I$source/bridge/src/server" "$repoRoot/tests/device_reset.cpp" /Fe:reset-test.exe
  if ($LASTEXITCODE -ne 0) { throw 'Reset test compilation failed' }
  & .\reset-test.exe
  if ($LASTEXITCODE -ne 0) { throw 'Reset test failed' }
} finally { Pop-Location }
