# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

param(
  [ValidateSet('x86', 'x64')][string]$CompileArchitecture,
  [switch]$Benchmark,
  [ValidateRange(2, 30)][int]$BenchmarkRounds = 6,
  [ValidateRange(100000, 50000000)][int]$BenchmarkMessages = 2000000
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
$testDir = Join-Path $repoRoot '.deps/queue-test'
New-Item -ItemType Directory -Force $testDir | Out-Null
if ($CompileArchitecture) {
  . (Join-Path $source 'bridge/build_common.ps1')
  SetupVS -Platform $CompileArchitecture -VcVarsVer '14.29'
  Push-Location $testDir
  try {
    & cl.exe /nologo /std:c++17 /EHsc /W4 /WX "/I$source/bridge/src/util" "$repoRoot/tests/command_queue.cpp" "/Fe:queue-test-$CompileArchitecture.exe"
    if ($LASTEXITCODE -ne 0) { throw "Queue test compilation failed for $CompileArchitecture" }
    if ($Benchmark) {
      # The two benchmark headers differ only by the successful-peek SC fence.
      $productionHeader = [IO.File]::ReadAllText((Join-Path $source 'bridge/src/util/util_atomiccircularqueue.h')).Replace("`r`n", "`n")
      $needle = "          result = Result::Success;`n          return m_data[currentWrite];"
      if ([regex]::Matches($productionHeader, [regex]::Escape($needle)).Count -ne 1 -or
          $productionHeader.Contains('std::atomic_thread_fence(std::memory_order_seq_cst);')) {
        throw 'Expected the production peek implementation with no standalone SC fence'
      }
      $oldHeader = $productionHeader.Replace($needle,
        "          std::atomic_thread_fence(std::memory_order_seq_cst);`n$needle")
      foreach ($variant in @('current', 'old-fence')) {
        $includeDir = Join-Path $testDir "include-$variant"
        New-Item -ItemType Directory -Force $includeDir | Out-Null
        $header = if ($variant -eq 'current') { $productionHeader } else { $oldHeader }
        [IO.File]::WriteAllText((Join-Path $includeDir 'util_atomiccircularqueue.h'),
          $header, [Text.UTF8Encoding]::new($false))
        & cl.exe /nologo /std:c++17 /O2 /EHsc /W4 /WX "/I$includeDir" "/I$source/bridge/src/util" "$repoRoot/tests/command_queue_benchmark.cpp" "/Fo:queue-benchmark-$variant-$CompileArchitecture.obj" "/Fe:queue-benchmark-$variant-$CompileArchitecture.exe"
        if ($LASTEXITCODE -ne 0) { throw "Queue benchmark compilation failed: $variant $CompileArchitecture" }
      }
      $compiler = Get-Item (Get-Command cl.exe).Source
      [ordered]@{
        architecture = $CompileArchitecture
        compiler = $compiler.FullName
        compiler_version = $compiler.VersionInfo.FileVersion
        flags = '/std:c++17 /O2 /EHsc /W4 /WX'
      } | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $testDir "benchmark-compiler-$CompileArchitecture.json") -Encoding UTF8
    }
  } finally { Pop-Location }
} else {
  foreach ($arch in @('x86', 'x64')) {
    $compileArgs = @('-NoProfile', '-File', $PSCommandPath, '-CompileArchitecture', $arch)
    if ($Benchmark) { $compileArgs += '-Benchmark' }
    & powershell.exe @compileArgs
    if ($LASTEXITCODE -ne 0) { throw "Queue test compilation failed for $arch" }
  }
  foreach ($arch in @('x86', 'x64')) {
    $peer = if ($arch -eq 'x86') { 'x64' } else { 'x86' }
    & (Join-Path $testDir "queue-test-$arch.exe") (Join-Path $testDir "queue-test-$peer.exe")
    if ($LASTEXITCODE -ne 0) { throw "Queue test failed for $arch -> $peer" }
  }
  if ($Benchmark) {
    & (Join-Path $PSScriptRoot 'benchmark_command_queue.ps1') -TestDirectory $testDir -Rounds $BenchmarkRounds -Messages $BenchmarkMessages
  }
}
