# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('client32','host32','host64')][string]$CompileRole,[ValidateSet('A','B','C','F','R')][string]$Variant)
$ErrorActionPreference='Stop'
$repoRoot=Split-Path $PSScriptRoot -Parent
$source=Join-Path $repoRoot '.deps/dxvk-remix'
if($CompileRole){
  $testDir=Join-Path $repoRoot ".deps/ipc-perf-$Variant"
  $arch=if($CompileRole -eq 'host64'){'x64'}else{'x86'}
  . (Join-Path $source 'bridge/build_common.ps1')
  SetupVS -Platform $arch -VcVarsVer '14.29'
  $assemblyDir=Join-Path $testDir "assembly-$CompileRole"
  New-Item -ItemType Directory -Force $assemblyDir | Out-Null
  Push-Location $testDir
  try{
    $roleFlags=if($CompileRole -eq 'host32'){@('/DREMIX_BRIDGE_X86_SERVER','/DREMIX_BRIDGE_SERVER')}else{@()}
    & cl.exe /nologo /std:c++17 /EHsc /O2 /W3 /FAs "/Fa:$assemblyDir\" /DNOMINMAX /DWIN32 @roleFlags "/I$testDir" "/I$repoRoot/tests" ipc_transport.cpp util_sharedmemory.cpp util_semaphore.cpp data_diagnostics.cpp exception_diagnostics.cpp "/Fe:perf-$CompileRole.exe" /link ole32.lib psapi.lib
    if($LASTEXITCODE -ne 0){throw "Performance compilation failed $Variant $CompileRole"}
  }finally{Pop-Location}
}else{
  python "$repoRoot/scripts/generate_ipc_performance_test.py"
  if($LASTEXITCODE -ne 0){throw 'Performance extraction failed'}
  foreach($v in @('A','B','F','R','C')){foreach($role in @('client32','host32','host64')){
    & powershell.exe -NoProfile -File $PSCommandPath -CompileRole $role -Variant $v
    if($LASTEXITCODE -ne 0){throw "Performance compile failed $v $role"}
  }}
  python "$repoRoot/scripts/run_ipc_performance.py"
  if($LASTEXITCODE -ne 0){throw 'Performance regression failed'}
}
