# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param(
  [ValidateSet('x86','x64')][string]$CompileArchitecture,
  [string]$SourceDirectory = (Join-Path (Split-Path $PSScriptRoot -Parent) '.deps/dxvk-remix'),
  [string]$OutputDirectory = (Join-Path (Split-Path $PSScriptRoot -Parent) '.deps/function-logging-test'),
  [switch]$Benchmark
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$SourceDirectory = (Resolve-Path -LiteralPath $SourceDirectory).Path
New-Item -ItemType Directory -Force $OutputDirectory | Out-Null
$OutputDirectory = (Resolve-Path -LiteralPath $OutputDirectory).Path
if (!$CompileArchitecture) {
  foreach ($architecture in @('x86','x64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -CompileArchitecture $architecture -SourceDirectory $SourceDirectory -OutputDirectory $OutputDirectory
    if ($LASTEXITCODE -ne 0) { throw "Function logging tests failed: $architecture" }
  }
  if ($Benchmark) {
    & (Join-Path $PSScriptRoot 'benchmark_function_logging.ps1') -TestDirectory $OutputDirectory
  }
  exit 0
}
. (Join-Path $SourceDirectory 'bridge/build_common.ps1')
SetupVS -Platform $CompileArchitecture -VcVarsVer '14.29'
foreach ($variant in @('current','old-signature')) {
  $testDir = Join-Path $OutputDirectory "$variant-$CompileArchitecture"
  New-Item -ItemType Directory -Force $testDir | Out-Null
  $extractArgs = @("$PSScriptRoot/prepare_function_logging_test.py", $SourceDirectory, $testDir)
  if ($variant -eq 'old-signature') { $extractArgs += '--old-signature' }
  & python @extractArgs
  if ($LASTEXITCODE -ne 0) { throw "Function logging extraction failed: $variant" }
  Push-Location $testDir
  try {
    # Match the production optimized static CRT and keep constructor/caller in
    # separate translation units. /GL would invalidate this isolated call cost.
    & cl.exe /nologo /std:c++17 /EHsc /W4 /WX /O2 /MT /DDEBUGOPT "/I$testDir" "/I$repoRoot/tests" `
      "$repoRoot/tests/function_logging.cpp" "$repoRoot/tests/function_logging_runtime.cpp" /Fe:function-logging.exe
    if ($LASTEXITCODE -ne 0) { throw "Function logging compilation failed: $variant" }
    if ($variant -eq 'current') {
      & ./function-logging.exe
      if ($LASTEXITCODE -ne 0) { throw 'Production function logging regression failed' }
    } else {
      & ./function-logging.exe --semantics-only
      if ($LASTEXITCODE -ne 0) { throw 'Old logger semantics changed; the allocation control is not comparable' }
      # cmd redirects stderr without PowerShell 5 treating expected native
      # stderr as a terminating ErrorRecord under ErrorActionPreference=Stop.
      & cmd.exe /d /c 'function-logging.exe > regression-output.txt 2>&1'
      $controlExit = $LASTEXITCODE
      $controlOutput = Get-Content -LiteralPath 'regression-output.txt' -Raw
      Write-Host $controlOutput
      if ($controlExit -ne 1 -or $controlOutput -notmatch 'Disabled logger allocated for function names') {
        throw 'Function logging regression missed the old allocation cost or failed for another reason'
      }
    }
  } finally {
    Pop-Location
  }
}
