# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('x86','x64')][string]$CompileArchitecture)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
$testDir = Join-Path $repoRoot '.deps/ipc-baseline'
if ($CompileArchitecture) {
  . (Join-Path $source 'bridge/build_common.ps1')
  SetupVS -Platform $CompileArchitecture -VcVarsVer '14.29'
  Push-Location $testDir
  try {
    & cl.exe /nologo /std:c++17 /EHsc /O2 /W4 /WX ipc_baseline.cpp "/Fe:baseline-$CompileArchitecture.exe"
    if ($LASTEXITCODE -ne 0) { throw 'IPC baseline compilation failed' }
    & ".\baseline-$CompileArchitecture.exe"
    if ($LASTEXITCODE -ne 0) { throw 'Old IPC defect was not reproduced' }
  } finally { Pop-Location }
} else {
  python "$repoRoot/scripts/prepare_ipc_baseline.py"
  if ($LASTEXITCODE -ne 0) { throw 'Pinned IPC baseline preparation failed' }
  python "$repoRoot/scripts/generate_ipc_baseline_test.py" --source "$repoRoot/.deps/ipc-v1.2.1"
  if ($LASTEXITCODE -ne 0) { throw 'IPC extraction failed' }
  foreach ($arch in @('x86','x64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -CompileArchitecture $arch
    if ($LASTEXITCODE -ne 0) { throw "IPC baseline failed for $arch" }
  }
}
