# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param(
  [ValidateSet('x86','x64')][string]$CompileArchitecture,
  [switch]$Benchmark
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
$testDir = Join-Path $repoRoot '.deps/surface-test'
New-Item -ItemType Directory -Force $testDir | Out-Null
if (-not $CompileArchitecture) {
  foreach ($arch in @('x86','x64')) {
    $childOptions = @('-NoProfile', '-File', $PSCommandPath, '-CompileArchitecture', $arch)
    if ($Benchmark) { $childOptions += '-Benchmark' }
    & powershell.exe @childOptions
    if ($LASTEXITCODE -ne 0) { throw "Surface test failed: $arch" }
  }
  return
}
. (Join-Path $source 'bridge/build_common.ps1')
SetupVS -Platform $CompileArchitecture -VcVarsVer '14.29'
Push-Location $testDir
try {
  $variants = if ($Benchmark) { @('optimized','row-reference') } else { @('optimized','row-reference','pitch-negative') }
  foreach ($variant in $variants) {
    $extractOptions = @("$PSScriptRoot/prepare_surface_test.py", $source, $testDir)
    if ($variant -eq 'row-reference') { $extractOptions += '--copy-reference' }
    if ($variant -eq 'pitch-negative') { $extractOptions += '--negative-control' }
    python @extractOptions
    if ($LASTEXITCODE -ne 0) { throw "Surface method extraction failed: $variant" }
    $options = @('/nologo','/std:c++17','/EHsc','/W4','/WX',"/I$testDir","/I$source/bridge/src/util",
      "$repoRoot/tests/surface_upload.cpp", "/Fe:surface-$CompileArchitecture-$variant.exe")
    if ($Benchmark) { $options += @('/O2','/DSURFACE_COPY_BENCHMARK') }
    & cl.exe @options
    if ($LASTEXITCODE -ne 0) { throw "Surface test compilation failed: $variant" }
    if ($variant -eq 'pitch-negative') {
      # Preserve expected stderr without PowerShell 5 treating it as a fatal ErrorRecord.
      & cmd.exe /d /c "surface-$CompileArchitecture-$variant.exe > pitch-negative-output.txt 2>&1"
      $controlExit = $LASTEXITCODE
      $controlOutput = Get-Content -LiteralPath 'pitch-negative-output.txt' -Raw
      Write-Host $controlOutput
      if ($controlExit -ne 1 -or $controlOutput -notmatch 'upload payload differs from row reference') {
        throw 'Surface pitch control failed for an unexpected reason or missed the regression'
      }
    } else {
      & (Join-Path $testDir "surface-$CompileArchitecture-$variant.exe")
      if ($LASTEXITCODE -ne 0) { throw "Surface regression failed: $variant" }
    }
  }
  if (-not $Benchmark) { return }
  $results = @()
  for ($round = 1; $round -le 5; ++$round) {
    $order = if ($round % 2) { @('row-reference','optimized') } else { @('optimized','row-reference') }
    foreach ($variant in $order) {
      $lines = & (Join-Path $testDir "surface-$CompileArchitecture-$variant.exe") --benchmark $variant $round
      if ($LASTEXITCODE -ne 0) { throw "Surface copy benchmark failed: $variant/$round" }
      foreach ($line in $lines) {
        Write-Output $line
        if ($line -match '^surface-copy variant=(\S+) round=(\d+) format=(\d+) width=(\d+) height=(\d+) bytes=(\d+) iterations=(\d+) copy_total_us=([\d.]+) copy_us_per_iteration=([\d.]+)$') {
          $results += [pscustomobject]@{
            architecture = $CompileArchitecture; variant = $Matches[1]; round = [int]$Matches[2];
            format = [long]$Matches[3]; width = [int]$Matches[4]; height = [int]$Matches[5];
            bytes = [long]$Matches[6]; iterations = [int]$Matches[7];
            copy_total_us = [double]::Parse($Matches[8], [cultureinfo]::InvariantCulture);
            copy_us_per_iteration = [double]::Parse($Matches[9], [cultureinfo]::InvariantCulture)
          }
        }
      }
    }
  }
  if ($results.Count -ne 50) { throw 'Surface copy benchmark produced incomplete measurements' }
  $results | Export-Csv -LiteralPath (Join-Path $testDir "surface-copy-$CompileArchitecture.csv") -NoTypeInformation -Encoding utf8
  $results | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $testDir "surface-copy-$CompileArchitecture.json") -Encoding utf8
} finally {
  python "$PSScriptRoot/prepare_surface_test.py" $source $testDir
  if ($LASTEXITCODE -ne 0) { Write-Error 'Failed to restore actual surface methods' }
  Pop-Location
}
