# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('client32','host32','host64')][string]$CompileRole)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
$testDir = Join-Path $repoRoot '.deps/ipc-transport'
if ($CompileRole) {
  $arch = if ($CompileRole -eq 'host64') { 'x64' } else { 'x86' }
  . (Join-Path $source 'bridge/build_common.ps1')
  SetupVS -Platform $arch -VcVarsVer '14.29'
  Push-Location $testDir
  try {
    $roleFlags = if ($CompileRole -eq 'host32') { @('/DREMIX_BRIDGE_X86_SERVER','/DREMIX_BRIDGE_SERVER') } else { @() }
    & cl.exe /nologo /std:c++17 /EHsc /O2 /W3 /DNOMINMAX /DWIN32 @roleFlags "/I$testDir" "/I$repoRoot/tests" ipc_transport.cpp util_sharedmemory.cpp util_semaphore.cpp data_diagnostics.cpp exception_diagnostics.cpp "/Fe:transport-$CompileRole.exe" /link ole32.lib psapi.lib
    if ($LASTEXITCODE -ne 0) { throw "Transport compile failed: $CompileRole" }
  } finally { Pop-Location }
} else {
  python "$repoRoot/scripts/generate_ipc_transport_test.py"
  if ($LASTEXITCODE -ne 0) { throw 'Transport extraction failed' }
  foreach ($role in @('client32','host32','host64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -CompileRole $role
    if ($LASTEXITCODE -ne 0) { throw "Transport compilation failed for $role" }
  }
  python "$repoRoot/scripts/run_ipc_transport.py"
  if ($LASTEXITCODE -ne 0) { throw 'Native transport assertions failed' }
}
