# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Historical upstream validation module; its multi-package publishing CLI is disabled."""
import base64
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import subprocess
import zipfile


def api(path):
    return json.loads(subprocess.check_output(['gh', 'api', path]))


def contents(repo, commit, name):
    item = api(f'repos/{repo}/contents/{name}?ref={commit}')
    return base64.b64decode(item['content'])


def read_package(path):
    with zipfile.ZipFile(path) as archive:
        if archive.testzip() is not None:
            raise ValueError('Corrupt artifact')
        files = {}
        for item in archive.infolist():
            if item.is_dir():
                continue
            name = PurePosixPath(item.filename)
            if name.is_absolute() or '..' in name.parts or '\\' in item.filename or item.filename in files:
                raise ValueError('Invalid or duplicate archive member')
            files[item.filename] = archive.read(item)
    hashes = json.loads(files['SHA256.json'])
    for name, expected in hashes.items():
        if hashlib.sha256(files[name]).hexdigest() != expected:
            raise ValueError('Binary checksum mismatch: ' + name)
    return files


def verify_core(files, version, commit, kind):
    receipt = json.loads(files['BUILD-INFO.json'])
    if files['VERSION'].decode().strip() != version or receipt['version'] != version:
        raise ValueError('Artifact version mismatch')
    if receipt['source_commit'] != commit or receipt['kind'] != kind or receipt['distribution'] != 'release':
        raise ValueError('Artifact source or kind mismatch')
    patch_hash = hashlib.sha256(files['patches/l4d2-bridge.patch']).hexdigest()
    if receipt['patch_sha256'] != patch_hash or receipt['build_id'] != f'l4d2-{version}+{patch_hash[:16]}':
        raise ValueError('Patch/build identity mismatch')
    hashes = json.loads(files['SHA256.json'])
    if receipt['files'] != hashes or receipt['optional_plugin']:
        raise ValueError('Invalid core receipt')
    if any(PurePosixPath(name).name == 'L4D2BridgePlugin.dll' for name in files):
        raise ValueError('L4N plugin must be a separate release asset')
    expected = {
        'bin/dxvk_d3d9.dll': 0x14c,
        'bin/.l4d2bridge/L4D2Bridge32.exe': 0x14c,
        'bin/.l4d2bridge/L4D2Bridge64.exe': 0x8664,
    }
    if kind == 'full':
        expected.update({'bin/.l4d2bridge/d3d9vk_x86.dll': 0x14c,
                         'bin/.l4d2bridge/d3d9vk_x64.dll': 0x8664})
        if 'bin/.l4d2bridge/bridge.conf' not in files:
            raise ValueError('Full package needs default configuration')
    if {name for name in files if name.startswith('bin/') and name != 'bin/.l4d2bridge/bridge.conf'} != set(expected):
        raise ValueError('Unexpected runtime package files')
    if set(hashes) != set(expected):
        raise ValueError('Every runtime binary must be in the checksum manifest')
    if kind != 'full' and 'bin/.l4d2bridge/bridge.conf' in files:
        raise ValueError('Update must preserve runtime configuration')
    for name, machine in expected.items():
        binary = files[name]
        offset = int.from_bytes(binary[60:64], 'little')
        if binary[:2] != b'MZ' or binary[offset:offset + 4] != b'PE\0\0' or int.from_bytes(binary[offset + 4:offset + 6], 'little') != machine:
            raise ValueError('PE architecture mismatch: ' + name)
        if name.endswith('L4D2Bridge32.exe') and not int.from_bytes(binary[offset + 22:offset + 24], 'little') & 0x20:
            raise ValueError('x86 Host must be LAA')
        if name in expected and 'd3d9vk_' not in name and receipt['build_id'].encode() not in binary:
            raise ValueError('Binary build identity mismatch: ' + name)
    return receipt


def patch_section(data, name):
    marker = f'diff --git a/{name} b/{name}\n'.encode()
    start = data.index(marker)
    end = data.find(b'\ndiff --git ', start + len(marker))
    return data[start:end if end >= 0 else len(data)]


def main():
    repo = os.environ['GH_REPO']
    version = os.environ['RELEASE_VERSION']
    run_id = os.environ['BUILD_RUN_ID']
    plugin_run_id = os.environ.get('L4N_BUILD_RUN_ID', '')
    include_plugin = os.environ.get('INCLUDE_L4N', 'true').lower()
    if include_plugin not in ('true', 'false'):
        raise ValueError('INCLUDE_L4N must be true or false')
    if not re.fullmatch(r'\d+\.\d+\.\d+', version) or not run_id.isdigit() or (plugin_run_id and not plugin_run_id.isdigit()):
        raise ValueError('Invalid version or build run ID')

    def tested(run):
        result = api(f'repos/{repo}/actions/runs/{run}')
        if result['conclusion'] != 'success' or result['name'] != 'Build L4D2 D3D9 Bridge':
            raise ValueError('Build did not pass the expected workflow')
        return result

    run = tested(run_id)
    commit = run['head_sha']
    releases = api(f'repos/{repo}/releases?per_page=100')
    matching = [item for item in releases if item['tag_name'] == 'v' + version]
    if len(matching) != 1 or not matching[0]['draft'] or matching[0]['target_commitish'] != commit:
        raise ValueError('Need one draft targeting the tested commit')

    def download(build, name, destination):
        artifacts = api(f'repos/{repo}/actions/runs/{build}/artifacts?per_page=100')['artifacts']
        matches = [item for item in artifacts if item['name'] == name and not item['expired']]
        if len(matches) != 1:
            raise ValueError('Missing or ambiguous artifact: ' + name)
        path = Path(destination)
        with path.open('wb') as output:
            subprocess.run(['gh', 'api', matches[0]['archive_download_url']], stdout=output, check=True)
        return path

    outputs = []
    receipts = []
    for name, kind in [(f'l4d2-bridge-patch-v{version}', 'matched-update'), (f'l4d2-bridge-v{version}', 'full')]:
        path = download(run_id, name, name + '.zip')
        receipts.append(verify_core(read_package(path), version, commit, kind))
        outputs.append(path)
    if receipts[0]['build_id'] != receipts[1]['build_id'] or receipts[0]['patch_sha256'] != receipts[1]['patch_sha256']:
        raise ValueError('Core artifacts are not a matched build')

    if include_plugin == 'true':
        plugin_name = f'l4d2-bridge-l4n-v{version}.zip'
        if plugin_run_id:
            previous = tested(plugin_run_id)
            old_commit = previous['head_sha']
            for name in ['plugins/l4n/L4D2BridgePlugin.cpp', 'plugins/l4n/sdk/l4n_plugin.h']:
                if contents(repo, old_commit, name) != contents(repo, commit, name):
                    raise ValueError('L4N source changed; build the plugin rather than reuse it')
            previous_patch = contents(repo, old_commit, 'patches/l4d2-bridge.patch')
            current_patch = contents(repo, commit, 'patches/l4d2-bridge.patch')
            for name in ['bridge/src/util/bridge_control.h', 'bridge/src/util/pageblock_control.h']:
                if patch_section(previous_patch, name) != patch_section(current_patch, name):
                    raise ValueError('Control ABI changed; revalidate the plugin')
            old_version = contents(repo, old_commit, 'VERSION').decode().strip()
            previous_path = download(plugin_run_id, f'l4d2-bridge-v{old_version}', 'reused-plugin-source.zip')
            old_files = read_package(previous_path)
            plugin = old_files['optional/L4N/L4D2BridgePlugin.dll']
            relative = 'bin/neko/plugins/L4D2BridgePlugin.dll'
            hashes = {relative: hashlib.sha256(plugin).hexdigest()}
            plugin_files = {relative: plugin, 'VERSION': (version + '\n').encode()}
            for name in ['LICENSE', 'THIRD_PARTY.md', 'docs/L4N-BRIDGE-CONTROLS.md']:
                plugin_files[name] = contents(repo, commit, name)
            plugin_files['README.md'] = (
                f'# Optional L4N Bridge controls {version}\n\n'
                'Close L4D2, then merge bin/neko/plugins into the game directory. '
                'Requires L4N SDK v2 HUD support. Bridge works without this plugin. '
                'See [controls](docs/L4N-BRIDGE-CONTROLS.md). '
                'The unchanged DLL is reused from a tested build; provenance is in BUILD-INFO.json.\n').encode()
            receipt = {'version': version, 'kind': 'optional-l4n-plugin', 'distribution': 'release',
                       'source_commit': old_commit, 'compatible_bridge_commit': commit,
                       'reused_binary': True, 'build_run_id': int(plugin_run_id), 'files': hashes}
            plugin_files['SHA256.json'] = (json.dumps(hashes, indent=2) + '\n').encode()
            plugin_files['BUILD-INFO.json'] = (json.dumps(receipt, indent=2) + '\n').encode()
            path = Path(plugin_name)
            with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
                for name, data in sorted(plugin_files.items()):
                    archive.writestr(name, data)
        else:
            path = download(run_id, plugin_name[:-4], plugin_name)
        plugin_files = read_package(path)
        plugin_receipt = json.loads(plugin_files['BUILD-INFO.json'])
        plugin = plugin_files['bin/neko/plugins/L4D2BridgePlugin.dll']
        offset = int.from_bytes(plugin[60:64], 'little')
        if plugin_files['VERSION'].decode().strip() != version or plugin_receipt['version'] != version or plugin_receipt['kind'] != 'optional-l4n-plugin':
            raise ValueError('Invalid independent plugin package')
        if plugin[:2] != b'MZ' or plugin[offset:offset + 4] != b'PE\0\0' or int.from_bytes(plugin[offset + 4:offset + 6], 'little') != 0x14c:
            raise ValueError('L4N plugin must be x86 PE')
        if [name for name in plugin_files if name.startswith('bin/')] != ['bin/neko/plugins/L4D2BridgePlugin.dll']:
            raise ValueError('Plugin asset contains Bridge or backend files')
        if plugin_receipt['files'] != json.loads(plugin_files['SHA256.json']) or set(plugin_receipt['files']) != {'bin/neko/plugins/L4D2BridgePlugin.dll'}:
            raise ValueError('Invalid plugin checksum receipt')
        outputs.append(path)
    sums = Path('SHA256SUMS.txt')
    sums.write_text(''.join(f'{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.name}\n' for path in outputs))
    subprocess.run(['gh', 'release', 'upload', 'v' + version, *map(str, outputs), str(sums), '--clobber'], check=True)
    assets = api(f"repos/{repo}/releases/{matching[0]['id']}")['assets']
    for path in [*outputs, sums]:
        if not any(item['name'] == path.name and item['size'] == path.stat().st_size for item in assets):
            raise ValueError('Uploaded asset size mismatch')
    subprocess.run(['gh', 'release', 'edit', 'v' + version, '--draft=false', '--prerelease=false', '--latest'], check=True)


if __name__ == '__main__':
    raise SystemExit('Historical validation module only. Publish the single full package with upstream-release.yml.')
