// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once

#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <map>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace thinflex {

struct Json {
  enum class Kind { Null, Boolean, Number, String, Array, Object };
  Kind kind = Kind::Null;
  bool boolean = false;
  double numeric = 0;
  std::string text;
  std::vector<Json> elements;
  std::map<std::string, Json> members;

  static Json booleanValue(bool value) { Json j; j.kind = Kind::Boolean; j.boolean = value; return j; }
  static Json number(std::uint64_t value) { Json j; j.kind = Kind::Number; j.numeric = static_cast<double>(value); return j; }
  static Json string(std::string value) { Json j; j.kind = Kind::String; j.text = std::move(value); return j; }
  static Json array() { Json j; j.kind = Kind::Array; return j; }
  static Json object() { Json j; j.kind = Kind::Object; return j; }

  bool operator==(const Json& other) const {
    if (kind != other.kind) return false;
    switch (kind) {
      case Kind::Null: return true;
      case Kind::Boolean: return boolean == other.boolean;
      case Kind::Number: return numeric == other.numeric;
      case Kind::String: return text == other.text;
      case Kind::Array: return elements == other.elements;
      case Kind::Object: return members == other.members;
    }
    return false;
  }
};

inline std::string jsonQuote(const std::string& text) {
  constexpr char hex[] = "0123456789abcdef";
  std::string result = "\"";
  for (unsigned char c : text) {
    switch (c) {
      case '"': result += "\\\""; break;
      case '\\': result += "\\\\"; break;
      case '\b': result += "\\b"; break;
      case '\f': result += "\\f"; break;
      case '\n': result += "\\n"; break;
      case '\r': result += "\\r"; break;
      case '\t': result += "\\t"; break;
      default:
        if (c < 0x20) {
          result += "\\u00";
          result += hex[c >> 4]; result += hex[c & 15];
        } else {
          result += static_cast<char>(c);
        }
    }
  }
  return result + '"';
}

// Only the program's generated manifest is serialized; its numbers are exact
// nonnegative integers. Parsed input is compared structurally, never rewritten.
inline std::string jsonWrite(const Json& value) {
  switch (value.kind) {
    case Json::Kind::Null: return "null";
    case Json::Kind::Boolean: return value.boolean ? "true" : "false";
    case Json::Kind::Number: return std::to_string(static_cast<std::uint64_t>(value.numeric));
    case Json::Kind::String: return jsonQuote(value.text);
    case Json::Kind::Array: {
      std::string result = "[";
      for (const auto& item : value.elements) {
        if (result.size() > 1) result += ',';
        result += jsonWrite(item);
      }
      return result + ']';
    }
    case Json::Kind::Object: {
      std::string result = "{";
      for (const auto& item : value.members) {
        if (result.size() > 1) result += ',';
        result += jsonQuote(item.first) + ':' + jsonWrite(item.second);
      }
      return result + '}';
    }
  }
  throw std::runtime_error("Invalid internal JSON value");
}

class JsonReader {
  const std::string& input;
  std::size_t cursor = 0;

  [[noreturn]] static void reject() { throw std::runtime_error("Invalid JSON manifest"); }
  void whitespace() {
    while (cursor < input.size() && (input[cursor] == ' ' || input[cursor] == '\t'
        || input[cursor] == '\r' || input[cursor] == '\n')) ++cursor;
  }
  bool take(char expected) {
    if (cursor < input.size() && input[cursor] == expected) { ++cursor; return true; }
    return false;
  }
  std::uint32_t hex4() {
    if (input.size() - cursor < 4) reject();
    std::uint32_t value = 0;
    for (unsigned i = 0; i < 4; ++i) {
      unsigned char c = static_cast<unsigned char>(input[cursor++]);
      unsigned digit;
      if (c >= '0' && c <= '9') digit = c - '0';
      else if (c >= 'a' && c <= 'f') digit = c - 'a' + 10;
      else if (c >= 'A' && c <= 'F') digit = c - 'A' + 10;
      else { reject(); }
      value = value * 16 + digit;
    }
    return value;
  }
  static void utf8(std::string& out, std::uint32_t value) {
    if (value < 0x80) out += static_cast<char>(value);
    else if (value < 0x800) {
      out += static_cast<char>(0xc0 | (value >> 6));
      out += static_cast<char>(0x80 | (value & 63));
    } else if (value < 0x10000) {
      out += static_cast<char>(0xe0 | (value >> 12));
      out += static_cast<char>(0x80 | ((value >> 6) & 63));
      out += static_cast<char>(0x80 | (value & 63));
    } else {
      out += static_cast<char>(0xf0 | (value >> 18));
      out += static_cast<char>(0x80 | ((value >> 12) & 63));
      out += static_cast<char>(0x80 | ((value >> 6) & 63));
      out += static_cast<char>(0x80 | (value & 63));
    }
  }
  std::string string() {
    if (!take('"')) reject();
    std::string result;
    while (cursor < input.size()) {
      unsigned char c = static_cast<unsigned char>(input[cursor++]);
      if (c == '"') return result;
      if (c < 0x20) reject();
      if (c != '\\') { result += static_cast<char>(c); continue; }
      if (cursor == input.size()) reject();
      switch (input[cursor++]) {
        case '"': result += '"'; break;
        case '\\': result += '\\'; break;
        case '/': result += '/'; break;
        case 'b': result += '\b'; break;
        case 'f': result += '\f'; break;
        case 'n': result += '\n'; break;
        case 'r': result += '\r'; break;
        case 't': result += '\t'; break;
        case 'u': {
          auto value = hex4();
          if (value >= 0xd800 && value <= 0xdbff) {
            if (!take('\\') || !take('u')) reject();
            const auto low = hex4();
            if (low < 0xdc00 || low > 0xdfff) reject();
            value = 0x10000 + ((value - 0xd800) << 10) + low - 0xdc00;
          } else if (value >= 0xdc00 && value <= 0xdfff) reject();
          utf8(result, value); break;
        }
        default: reject();
      }
    }
    reject();
  }
  Json number() {
    const auto begin = cursor;
    take('-');
    if (!take('0')) {
      if (cursor == input.size() || input[cursor] < '1' || input[cursor] > '9') reject();
      while (cursor < input.size() && input[cursor] >= '0' && input[cursor] <= '9') ++cursor;
    }
    if (take('.')) {
      const auto digits = cursor;
      while (cursor < input.size() && input[cursor] >= '0' && input[cursor] <= '9') ++cursor;
      if (cursor == digits) reject();
    }
    if (take('e') || take('E')) {
      if (!take('+')) take('-');
      const auto digits = cursor;
      while (cursor < input.size() && input[cursor] >= '0' && input[cursor] <= '9') ++cursor;
      if (cursor == digits) reject();
    }
    const auto token = input.substr(begin, cursor - begin);
    char* end = nullptr;
    const double value = std::strtod(token.c_str(), &end);
    if (end != token.c_str() + token.size() || !std::isfinite(value)) reject();
    Json result; result.kind = Json::Kind::Number; result.numeric = value; return result;
  }
  Json value(unsigned depth) {
    if (depth > 64) reject();
    whitespace();
    if (cursor == input.size()) reject();
    if (input[cursor] == '"') return Json::string(string());
    if (take('{')) {
      Json result = Json::object(); whitespace();
      if (take('}')) return result;
      do {
        whitespace(); auto key = string(); whitespace();
        if (!take(':')) reject();
        auto item = value(depth + 1);
        if (!result.members.emplace(std::move(key), std::move(item)).second) reject();
        whitespace();
        if (take('}')) return result;
      } while (take(','));
      reject();
    }
    if (take('[')) {
      Json result = Json::array(); whitespace();
      if (take(']')) return result;
      do {
        result.elements.push_back(value(depth + 1)); whitespace();
        if (take(']')) return result;
      } while (take(','));
      reject();
    }
    if (input.compare(cursor, 4, "true") == 0) { cursor += 4; return Json::booleanValue(true); }
    if (input.compare(cursor, 5, "false") == 0) { cursor += 5; return Json::booleanValue(false); }
    if (input.compare(cursor, 4, "null") == 0) { cursor += 4; return {}; }
    return number();
  }

public:
  explicit JsonReader(const std::string& text) : input(text) {}
  Json parse() {
    auto result = value(0); whitespace();
    if (cursor != input.size()) reject();
    return result;
  }
};

} // namespace thinflex
