// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <bcrypt.h>

#include <algorithm>
#include <array>
#include <cstdio>
#include <cwchar>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>
#include "json.hpp"

namespace {
using Bytes = std::vector<unsigned char>;
using thinflex::Json;

#ifdef THINFLEX_TESTING
constexpr const char* ExpectedSha = THINFLEX_TEST_INPUT_SHA256;
constexpr const char* Cert0Sha = THINFLEX_TEST_CERT0_SHA256;
constexpr const char* Cert1Sha = THINFLEX_TEST_CERT1_SHA256;
#else
constexpr const char* ExpectedSha = "3f5f5b0f539e8ad22bcfc4381be41571257c0c29e8061057682f9b8525ca7b85";
constexpr const char* Cert0Sha = "859cfcd52bdaed18440376f4c50fa8277a8958664f7404d5fbe1c6b08afa6bc9";
constexpr const char* Cert1Sha = "d8d96d4de552931f312d6587e0a6d6404f670da835af225d0800b6a098812c04";
#endif
constexpr std::uint32_t Timestamp = 0x6a440dd6;
constexpr std::uint32_t OldImageSize = 0x453000;
constexpr std::uint32_t PoolRva = OldImageSize;
constexpr std::uint32_t CacheRva = 0xb2940;
constexpr std::uint32_t EntrySize = 32;
constexpr std::uint32_t EntryCount = 65536;
constexpr std::uint32_t PoolSize = EntrySize * EntryCount;
constexpr std::uint32_t AddRvas[] = {0x10cd, 0x540b, 0xded1, 0x11083, 0x112d7};
constexpr const char* Warning =
    "EXPERIMENTAL ENGINE PATCH: this is not a Bridge DLL; not yet game validated. "
    "The modified copy's original Authenticode signature is no longer valid. "
    "Original certificate/overlay bytes are preserved; no files are installed.";

void require(bool condition, const std::string& message) {
  if (!condition) throw std::runtime_error(message);
}

[[noreturn]] void windowsError(const char* operation) {
  const auto error = GetLastError();
  throw std::runtime_error(std::string(operation) + " (Windows error " + std::to_string(error) + ")");
}

class Handle {
public:
  HANDLE value;
  explicit Handle(HANDLE handle) : value(handle) {}
  ~Handle() { if (value != INVALID_HANDLE_VALUE) CloseHandle(value); }
  Handle(const Handle&) = delete;
  Handle& operator=(const Handle&) = delete;
};

std::string hex(const unsigned char* bytes, std::size_t size) {
  constexpr char digits[] = "0123456789abcdef";
  std::string result;
  result.reserve(size * 2);
  for (std::size_t i = 0; i < size; ++i) {
    result += digits[bytes[i] >> 4]; result += digits[bytes[i] & 15];
  }
  return result;
}

std::string sha256(const unsigned char* bytes, std::size_t size) {
  struct Algorithm {
    BCRYPT_ALG_HANDLE handle = nullptr;
    ~Algorithm() { if (handle) BCryptCloseAlgorithmProvider(handle, 0); }
  } algorithm;
  require(BCryptOpenAlgorithmProvider(&algorithm.handle, BCRYPT_SHA256_ALGORITHM, nullptr, 0) >= 0,
      "Cannot initialize SHA256 provider");
  DWORD objectSize = 0, received = 0;
  require(BCryptGetProperty(algorithm.handle, BCRYPT_OBJECT_LENGTH,
      reinterpret_cast<PUCHAR>(&objectSize), static_cast<ULONG>(sizeof(objectSize)), &received, 0) >= 0,
      "Cannot query SHA256 provider");
  Bytes object(objectSize);
  struct Hash {
    BCRYPT_HASH_HANDLE handle = nullptr;
    ~Hash() { if (handle) BCryptDestroyHash(handle); }
  } hash;
  require(BCryptCreateHash(algorithm.handle, &hash.handle, object.data(), objectSize, nullptr, 0, 0) >= 0,
      "Cannot initialize SHA256 hash");
  while (size) {
    const auto chunk = static_cast<ULONG>(std::min<std::size_t>(size, 1024 * 1024));
    require(BCryptHashData(hash.handle, const_cast<PUCHAR>(bytes), chunk, 0) >= 0, "SHA256 update failed");
    bytes += chunk; size -= chunk;
  }
  std::array<unsigned char, 32> digest{};
  require(BCryptFinishHash(hash.handle, digest.data(), static_cast<ULONG>(digest.size()), 0) >= 0,
      "SHA256 finish failed");
  return hex(digest.data(), digest.size());
}

std::string sha256(const Bytes& data) { return sha256(data.data(), data.size()); }

Bytes readFile(const std::wstring& path) {
  Handle handle(CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
      OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr));
  if (handle.value == INVALID_HANDLE_VALUE) windowsError("Cannot read file");
  LARGE_INTEGER size{};
  if (!GetFileSizeEx(handle.value, &size)) windowsError("Cannot read file size");
  // The pinned DLL is 634672 bytes. Bound malformed input/manifest allocation.
  require(size.QuadPart >= 0 && size.QuadPart <= 16 * 1024 * 1024, "Input file exceeds supported size");
  Bytes result(static_cast<std::size_t>(size.QuadPart));
  std::size_t done = 0;
  while (done < result.size()) {
    DWORD count = 0;
    const auto chunk = static_cast<DWORD>(std::min<std::size_t>(result.size() - done, 1024 * 1024));
    if (!ReadFile(handle.value, result.data() + done, chunk, &count, nullptr)) windowsError("Cannot read file bytes");
    require(count != 0, "Unexpected end of file");
    done += count;
  }
  return result;
}

void bounds(const Bytes& data, std::size_t offset, std::size_t size) {
  require(offset <= data.size() && size <= data.size() - offset, "Truncated PE image");
}

std::uint16_t u16(const Bytes& data, std::size_t offset) {
  bounds(data, offset, 2);
  return static_cast<std::uint16_t>(data[offset] | (std::uint16_t(data[offset + 1]) << 8));
}

std::uint32_t u32(const Bytes& data, std::size_t offset) {
  bounds(data, offset, 4);
  return std::uint32_t(data[offset]) | (std::uint32_t(data[offset + 1]) << 8)
      | (std::uint32_t(data[offset + 2]) << 16) | (std::uint32_t(data[offset + 3]) << 24);
}

Bytes little(std::uint32_t value, std::size_t size = 4) {
  Bytes result(size);
  for (std::size_t i = 0; i < size; ++i) result[i] = static_cast<unsigned char>(value >> (8 * i));
  return result;
}

struct Section {
  std::string name;
  std::uint32_t size, rva, rawSize, rawOffset, flags;
};

struct PE {
  std::size_t pe, optional, newHeader, security;
  std::vector<Section> sections;
};

PE readPE(const Bytes& data) {
  require(data.size() >= 0x40 && data[0] == 'M' && data[1] == 'Z', "Not a DOS/PE image");
  PE result{};
  result.pe = u32(data, 0x3c);
  bounds(data, result.pe, 24);
  require(u32(data, result.pe) == 0x4550, "Invalid PE header");
  const auto coff = result.pe + 4;
  require(u16(data, coff) == 0x14c && u16(data, coff + 2) == 4
      && u32(data, coff + 4) == Timestamp && u16(data, coff + 16) == 224,
      "Unexpected x86 PE build/layout");
  require(u32(data, coff + 8) == 0 && u32(data, coff + 12) == 0
      && (u16(data, coff + 18) & 0x2000), "Unexpected COFF symbols or non-DLL image");
  result.optional = result.pe + 24;
  const auto optional = result.optional;
  const auto sectionTable = optional + 224;
  bounds(data, sectionTable, 5 * 40);
  require(u16(data, optional) == 0x10b, "Expected PE32 image");
  require(u32(data, optional + 32) == 0x1000 && u32(data, optional + 36) == 0x200
      && u32(data, optional + 56) == OldImageSize && u32(data, optional + 60) == 0x400,
      "Unexpected PE alignment or image size");
  require(u32(data, optional + 92) == 16, "Unexpected PE data directories");
  result.security = optional + 96 + 4 * 8;
  require(u32(data, result.security) == 0x98298 && u32(data, result.security + 4) == 0x2c98,
      "Unexpected certificate directory");
  const char* names[] = {".text", ".rdata", ".data", ".reloc"};
  std::uint64_t minRaw = std::numeric_limits<std::uint32_t>::max(), maxRaw = 0;
  for (unsigned i = 0; i < 4; ++i) {
    const auto offset = sectionTable + i * 40;
    std::string name(reinterpret_cast<const char*>(data.data() + offset), 8);
    while (!name.empty() && name.back() == '\0') name.pop_back();
    Section s{name, u32(data, offset + 8), u32(data, offset + 12),
        u32(data, offset + 16), u32(data, offset + 20), u32(data, offset + 36)};
    require(s.name == names[i], "Unexpected section names/order");
    require(s.rawOffset % 0x200 == 0 && s.rawSize % 0x200 == 0 && s.rva % 0x1000 == 0,
        "Misaligned section");
    require(s.rawOffset >= 0x400 && std::uint64_t(s.rawOffset) + s.rawSize <= data.size(),
        "Invalid raw section extent");
    require(std::uint64_t(s.rva) + std::max(s.size, s.rawSize) <= OldImageSize, "Invalid virtual section extent");
    require(u32(data, offset + 24) == 0 && u32(data, offset + 28) == 0
        && u16(data, offset + 32) == 0 && u16(data, offset + 34) == 0,
        "Unexpected section relocation/debug pointers");
    if (!result.sections.empty()) {
      const auto& previous = result.sections.back();
      require(std::uint64_t(previous.rawOffset) + previous.rawSize == s.rawOffset, "Unexpected section gap/overlap");
      require(std::uint64_t(previous.rva) + std::max(previous.size, previous.rawSize) <= s.rva,
          "Overlapping virtual sections");
    }
    minRaw = std::min(minRaw, std::uint64_t(s.rawOffset));
    maxRaw = std::max(maxRaw, std::uint64_t(s.rawOffset) + s.rawSize);
    result.sections.push_back(s);
  }
  require(minRaw == 0x400, "Unexpected first raw section");
  result.newHeader = sectionTable + 4 * 40;
  require(result.newHeader == 0x280 && result.newHeader + 40 <= 0x400, "No expected spare section header");
  require(std::all_of(data.begin() + result.newHeader, data.begin() + result.newHeader + 40,
      [](unsigned char c) { return c == 0; }), "Spare section header is not empty");
  require(maxRaw == 0x95600, "Unexpected overlay start");
  require(data.size() == 0x9af30, "Unexpected overlay/file length");
  const std::size_t certOffsets[] = {0x95600, 0x98298};
  const char* certHashes[] = {Cert0Sha, Cert1Sha};
  for (unsigned i = 0; i < 2; ++i) {
    const auto offset = certOffsets[i];
    bounds(data, offset, 0x2c98);
    require(u32(data, offset) == 0x2c98 && u16(data, offset + 4) == 0x200 && u16(data, offset + 6) == 2,
        "Unexpected WIN_CERTIFICATE layout");
    require(sha256(data.data() + offset, 0x2c98) == certHashes[i], "Unknown certificate/overlay bytes");
  }
  return result;
}

std::size_t rvaOffset(const PE& pe, std::uint32_t rva, std::size_t size) {
  for (const auto& section : pe.sections) {
    if (rva >= section.rva && std::uint64_t(rva - section.rva) + size <= section.rawSize) {
      require((section.flags & 0x20000000) != 0, "Patch site is not executable");
      return section.rawOffset + (rva - section.rva);
    }
  }
  throw std::runtime_error("Patch RVA is not backed by file bytes");
}

std::uint32_t checksum(const Bytes& data, std::size_t checksumOffset) {
  std::uint32_t result = 0;
  for (std::size_t offset = 0; offset < data.size(); offset += 2) {
    if (offset >= checksumOffset && offset < checksumOffset + 4) continue;
    result += data[offset] | ((offset + 1 < data.size() ? data[offset + 1] : 0) << 8);
    result = (result & 0xffff) + (result >> 16);
  }
  result = (result & 0xffff) + (result >> 16);
  return result + static_cast<std::uint32_t>(data.size());
}

struct Patch {
  Bytes bytes;
  Json manifest;
  std::string digest;
};

Patch patchImage(const Bytes& original) {
  const auto originalDigest = sha256(original);
  require(originalDigest == ExpectedSha, "Unsupported input SHA256; only the pinned original DLL is accepted");
  const auto pe = readPE(original);
  const auto limitOffset = rvaOffset(pe, 0x1083, 10);
  const Bytes limit{0x81, 0xb9, 0x34, 0x53, 0x07, 0x00, 0x10, 0x27, 0x00, 0x00};
  require(std::equal(limit.begin(), limit.end(), original.begin() + limitOffset), "Unexpected thin-pool limit instruction");
  std::vector<std::size_t> addOffsets;
  const Bytes add{0x05, 0x9a, 0x3a, 0x00, 0x00};
  for (auto rva : AddRvas) {
    const auto offset = rvaOffset(pe, rva, 5);
    require(std::equal(add.begin(), add.end(), original.begin() + offset), "Unexpected thin-pool address instruction");
    addOffsets.push_back(offset);
  }
  static_assert((PoolRva - CacheRva) % EntrySize == 0, "Pool entry alignment");
  constexpr auto newIndex = (PoolRva - CacheRva) / EntrySize;
  Patch patch{original, Json::object(), {}};
  struct Change { std::size_t offset, length; Json record; };
  std::vector<Change> changes;
  auto edit = [&](const std::string& label, std::size_t offset, const Bytes& replacement) {
    bounds(patch.bytes, offset, replacement.size());
    for (const auto& previous : changes)
      require(offset + replacement.size() <= previous.offset || offset >= previous.offset + previous.length, "Overlapping edits");
    Json record = Json::object();
    record.members["label"] = Json::string(label);
    record.members["file_offset"] = Json::number(offset);
    record.members["length"] = Json::number(replacement.size());
    record.members["before_hex"] = Json::string(hex(patch.bytes.data() + offset, replacement.size()));
    record.members["after_hex"] = Json::string(hex(replacement.data(), replacement.size()));
    std::copy(replacement.begin(), replacement.end(), patch.bytes.begin() + offset);
    changes.push_back({offset, replacement.size(), std::move(record)});
  };
  edit("thin pool limit: 10000 to 65536", limitOffset + 6, little(EntryCount));
  for (std::size_t i = 0; i < addOffsets.size(); ++i) {
    char label[80];
    std::snprintf(label, sizeof(label), "thin pool address at RVA 0x%x", static_cast<unsigned>(AddRvas[i]));
    edit(label, addOffsets[i] + 1, little(newIndex));
  }
  edit("NumberOfSections", pe.pe + 6, little(5, 2));
  const auto uninitialized = u32(original, pe.optional + 12);
  require(uninitialized <= 0xffffffffU - PoolSize, "Uninitialized size would overflow");
  edit("SizeOfUninitializedData", pe.optional + 12, little(uninitialized + PoolSize));
  edit("SizeOfImage", pe.optional + 56, little(PoolRva + PoolSize));
  Bytes header(40, 0);
  constexpr std::array<unsigned char, 6> sectionName{{'.', 'c', 'f', 'l', 'e', 'x'}};
  std::copy(sectionName.begin(), sectionName.end(), header.begin());
  auto headerWord = [&](std::size_t offset, std::uint32_t value) {
    const auto word = little(value); std::copy(word.begin(), word.end(), header.begin() + offset);
  };
  headerWord(8, PoolSize); headerWord(12, PoolRva); headerWord(36, 0xc0000080);
  edit(".cflex zero-filled RW section", pe.newHeader, header);
  edit("PE CheckSum (not an Authenticode signature)", pe.optional + 64, little(checksum(patch.bytes, pe.optional + 64)));
  require(std::equal(original.begin() + 0x95600, original.end(), patch.bytes.begin() + 0x95600), "Certificate/overlay preservation failed");
  require(std::equal(original.begin() + pe.security, original.begin() + pe.security + 8,
      patch.bytes.begin() + pe.security), "Security directory preservation failed");
  patch.digest = sha256(patch.bytes);
  auto& m = patch.manifest.members;
  m["format_version"] = Json::number(1);
  m["warning"] = Json::string(Warning);
  m["scope"] = Json::string("Thin flex pool only; 32-byte entries; legal indices 0..65535; no Bridge or game installation changes");
  m["original_sha256"] = Json::string(originalDigest);
  m["output_sha256"] = Json::string(patch.digest);
  m["original_size"] = Json::number(original.size());
  m["output_size"] = Json::number(patch.bytes.size());
  m["pe_timestamp"] = Json::number(Timestamp);
  m["pool_rva"] = Json::number(PoolRva);
  m["pool_entries"] = Json::number(EntryCount);
  m["pool_entry_bytes"] = Json::number(EntrySize);
  m["cache_relative_entry_offset"] = Json::number(newIndex);
  m["authenticode_signature_valid_after_patch"] = Json::booleanValue(false);
  m["certificate_and_overlay_bytes_preserved"] = Json::booleanValue(true);
  m["game_validated"] = Json::booleanValue(false);
  std::sort(changes.begin(), changes.end(), [](const Change& a, const Change& b) { return a.offset < b.offset; });
  Json records = Json::array();
  for (auto& change : changes) records.elements.push_back(std::move(change.record));
  m["changes"] = std::move(records);
  return patch;
}

std::wstring absolutePath(const std::wstring& path) {
  const auto required = GetFullPathNameW(path.c_str(), 0, nullptr, nullptr);
  if (!required) windowsError("Cannot resolve path");
  std::vector<wchar_t> buffer(required);
  const auto written = GetFullPathNameW(path.c_str(), required, buffer.data(), nullptr);
  if (!written || written >= required) windowsError("Cannot resolve path");
  return std::wstring(buffer.data(), written);
}

void absent(const std::wstring& path) {
  if (GetFileAttributesW(path.c_str()) != INVALID_FILE_ATTRIBUTES)
    throw std::runtime_error("Refusing to overwrite existing file");
  const auto error = GetLastError();
  require(error == ERROR_FILE_NOT_FOUND || error == ERROR_PATH_NOT_FOUND, "Cannot check destination file");
}

// Keep handles open until both files are complete. Rollback deletes only the
// file object this process created; a racing writer's path is never unlinked.
class CreatedFile {
  Handle handle;
  bool committed = false;
public:
  explicit CreatedFile(const std::wstring& path)
      : handle(CreateFileW(path.c_str(), GENERIC_WRITE | DELETE, 0, nullptr, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, nullptr)) {
    if (handle.value == INVALID_HANDLE_VALUE) windowsError("Cannot exclusively create destination");
  }
  ~CreatedFile() {
    if (!committed) {
      FILE_DISPOSITION_INFO disposition{TRUE};
      SetFileInformationByHandle(handle.value, FileDispositionInfo, &disposition,
          static_cast<DWORD>(sizeof(disposition)));
    }
  }
  void write(const unsigned char* data, std::size_t size) {
    while (size) {
      const auto chunk = static_cast<DWORD>(std::min<std::size_t>(size, 1024 * 1024));
      DWORD written = 0;
      if (!WriteFile(handle.value, data, chunk, &written, nullptr)) windowsError("Cannot write destination");
      require(written != 0, "Destination write made no progress");
      data += written; size -= written;
    }
  }
  void flush() { if (!FlushFileBuffers(handle.value)) windowsError("Cannot flush destination"); }
  void commit() { committed = true; }
};

#ifdef THINFLEX_TESTING
bool fault(const wchar_t* requested) {
  wchar_t value[64]{};
  const auto size = GetEnvironmentVariableW(L"THINFLEX_TEST_FAULT", value, 64);
  return size > 0 && size < 64 && std::wcscmp(value, requested) == 0;
}

void competingFile(const std::wstring& path) {
  CreatedFile competing(path);
  constexpr unsigned char text[] = "competing writer\n";
  competing.write(text, sizeof(text) - 1);
  competing.flush(); competing.commit();
}
#endif

Patch create(const std::wstring& source, const std::wstring& output, const std::wstring& manifest) {
  const auto sourcePath = absolutePath(source), outputPath = absolutePath(output), manifestPath = absolutePath(manifest);
  require(CompareStringOrdinal(sourcePath.c_str(), -1, outputPath.c_str(), -1, TRUE) != CSTR_EQUAL
      && CompareStringOrdinal(sourcePath.c_str(), -1, manifestPath.c_str(), -1, TRUE) != CSTR_EQUAL
      && CompareStringOrdinal(outputPath.c_str(), -1, manifestPath.c_str(), -1, TRUE) != CSTR_EQUAL,
      "Input, output and manifest paths must be distinct");
  absent(outputPath); absent(manifestPath);
  auto patch = patchImage(readFile(sourcePath));
  const auto metadata = thinflex::jsonWrite(patch.manifest) + '\n';
#ifdef THINFLEX_TESTING
  if (fault(L"output_race")) competingFile(outputPath);
#endif
  CreatedFile result(outputPath);
#ifdef THINFLEX_TESTING
  if (fault(L"manifest_race")) competingFile(manifestPath);
#endif
  CreatedFile record(manifestPath);
#ifdef THINFLEX_TESTING
  if (fault(L"output_write")) {
    result.write(patch.bytes.data(), 17); throw std::runtime_error("Injected output write failure");
  }
#endif
  result.write(patch.bytes.data(), patch.bytes.size());
#ifdef THINFLEX_TESTING
  if (fault(L"manifest_write")) {
    record.write(reinterpret_cast<const unsigned char*>(metadata.data()), 17);
    throw std::runtime_error("Injected manifest write failure");
  }
#endif
  record.write(reinterpret_cast<const unsigned char*>(metadata.data()), metadata.size());
  result.flush(); record.flush();
  result.commit(); record.commit();
  return patch;
}

Patch verify(const std::wstring& source, const std::wstring& output, const std::wstring& manifest) {
  auto patch = patchImage(readFile(source));
  require(readFile(output) == patch.bytes, "Output bytes differ from the exact expected experimental patch");
  const auto bytes = readFile(manifest);
  const std::string text(bytes.begin(), bytes.end());
  require(!text.empty() && MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, text.data(),
      static_cast<int>(text.size()), nullptr, 0) > 0, "Manifest is not valid UTF-8");
  require(thinflex::JsonReader(text).parse() == patch.manifest, "Manifest differs from the recomputed patch record");
  return patch;
}

void usage() {
  std::puts("ThinFlexPatch.exe create INPUT OUTPUT --experimental-engine-patch [--manifest MANIFEST]\n"
      "ThinFlexPatch.exe verify INPUT OUTPUT MANIFEST\n"
      "Create and verify a separate experimental DLL copy; no files are installed.\n");
  std::puts(Warning);
}
} // namespace

int wmain(int argc, wchar_t** argv) {
  try {
    if (argc < 2) { usage(); return 2; }
    const std::wstring command = argv[1];
    if (command == L"--help" || command == L"-h") { usage(); return 0; }
    require(command == L"create" || command == L"verify", "Expected create or verify command");
    std::vector<std::wstring> paths;
    std::wstring manifest;
    bool optIn = false, positionalOnly = false, sawManifest = false;
    for (int i = 2; i < argc; ++i) {
      const std::wstring arg = argv[i];
      if (!positionalOnly && (arg == L"--help" || arg == L"-h")) { usage(); return 0; }
      if (!positionalOnly && arg == L"--") { positionalOnly = true; continue; }
      if (!positionalOnly && command == L"create" && arg == L"--experimental-engine-patch") {
        optIn = true; continue;
      }
      if (!positionalOnly && command == L"create" && arg == L"--manifest") {
        require(!sawManifest && i + 1 < argc, "Expected a single --manifest path");
        manifest = argv[++i]; sawManifest = true; continue;
      }
      require(positionalOnly || arg.empty() || arg[0] != L'-', "Unknown command option");
      paths.push_back(arg);
    }
    Patch patch;
    if (command == L"create") {
      require(paths.size() == 2, "Create requires input and output paths");
      require(optIn, "Explicit --experimental-engine-patch opt-in is required");
      if (!sawManifest) manifest = paths[1] + L".manifest.json";
      patch = create(paths[0], paths[1], manifest);
    } else {
      require(paths.size() == 3, "Verify requires input, output and manifest paths");
      patch = verify(paths[0], paths[1], paths[2]);
    }
    std::puts(Warning);
    std::printf("%s: SHA256 %s\n", command == L"create" ? "create" : "verify", patch.digest.c_str());
    return 0;
  } catch (const std::exception& error) {
    std::fprintf(stderr, "Rejected: %s\n", error.what());
    return 1;
  } catch (...) {
    std::fprintf(stderr, "Rejected: unexpected internal error\n");
    return 1;
  }
}
